// AUTO-GENERATED by scripts/testing-v2/codemod.mjs — do not edit the legacy source.
// Source: tests/auto-retry-policy.test.ts
// Bucket: v2-core | Method: codemod | Classification: needs-withEnv
// Review: mutates process.env — wrap in withEnv(patch, fn) to restore in finally

import { guardProcessEnv } from "./helpers/env-guard.js";
guardProcessEnv();

/**
 * Unit tests for the auto-retry policy decisions invoked by
 * `SessionManager.maybeAutoRetryTransient()`.
 *
 * Strategy: rather than constructing a full SessionManager (which requires
 * RPC bridges, project stores, etc), we replicate the policy decision tree
 * here as a pure function `decideRetryPolicy()` that delegates classification
 * to the SAME exported helpers the manager uses
 * (`isTransientReviewError`, `isProviderBackoffError`, `nextBackoffDelay`).
 *
 * If the building blocks behave correctly, the manager is a thin scheduler
 * around them; this test pins the contract those building blocks must
 * satisfy for the manager to implement the design correctly.
 *
 * Behaviour pinned here:
 *   1. Provider overload / rate-limit errors → effectively unbounded retries,
 *      exponential backoff capped at 300_000 ms.
 *   2. Non-provider transient errors → bounded at 3 attempts (1s, 2s, 4s).
 *   3. Generic unexpected agent errors → bounded at 3 attempts (1s, 5s, 60s)
 *      and delivered through the same auto retry path as the Retry button.
 *   4. Deterministic/non-retryable errors → no auto-retry.
 *
 * Runs via `npm run test:unit` (Node test runner).
 */
import { afterEach, describe, it, vi } from "vitest";
// __v2_realtimers_net: forks are shared (isolate:false) — never leak fake timers.
afterEach(() => { vi.useRealTimers(); });
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import {
	isTransientReviewError,
	isProviderBackoffError,
} from "../../src/server/agent/verification-logic.ts";
import { nextBackoffDelay } from "../../src/server/agent/session-setup.ts";

const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), "auto-retry-policy-test-"));
process.env.BOBBIT_DIR = tmpRoot;

const { SessionManager } = await import("../../src/server/agent/session-manager.ts");
const { PromptQueue } = await import("../../src/server/agent/prompt-queue.ts");
const { EventBuffer } = await import("../../src/server/agent/event-buffer.ts");
const { initAuthorSidecarDir } = await import("../../src/server/agent/author-sidecar.ts");

initAuthorSidecarDir(tmpRoot, {
	secretsDir: path.join(tmpRoot, "private-secrets"),
	hmacKey: Buffer.alloc(32, 0x45),
});

// ── Policy under test ──────────────────────────────────────────────────────

const PROVIDER_BACKOFF_MAX_MS = 300_000;
const TRANSIENT_MAX_ATTEMPTS = 3;

type RetryDecision =
	| { retry: false; reason: "non-transient" | "exhausted" }
	| { retry: true; delayMs: number; reason: "provider-backoff" | "transient-error"; attempt: number };

function decideRetryPolicy(
	errMsg: string,
	priorAttempts: number,
	opts?: { random?: () => number },
): RetryDecision {
	if (!errMsg || !isTransientReviewError(errMsg)) {
		return { retry: false, reason: "non-transient" };
	}
	const attempt = priorAttempts + 1;
	if (isProviderBackoffError(errMsg)) {
		const delayMs = nextBackoffDelay(attempt, {
			baseMs: 1000,
			maxMs: PROVIDER_BACKOFF_MAX_MS,
			jitterRatio: 0.2,
			random: opts?.random ?? (() => 0.5),
		});
		return { retry: true, delayMs, reason: "provider-backoff", attempt };
	}
	// Bounded path — current behaviour: 1s, 2s, 4s, stop.
	if (attempt > TRANSIENT_MAX_ATTEMPTS) {
		return { retry: false, reason: "exhausted" };
	}
	const delayMs = 1000 * Math.pow(2, attempt - 1);
	return { retry: true, delayMs, reason: "transient-error", attempt };
}

// ── Fixtures ───────────────────────────────────────────────────────────────

const OVERLOAD_JSON =
	'Error: {"type":"error","error":{"details":null,"type":"overloaded_error","message":"Overloaded"},"request_id":"req_011Cb3PkGgaYHToky3UNLG2i"}';
const RATE_LIMIT_JSON = '{"type":"rate_limit_error","message":"Rate limited"}';
const JSON_GLITCH =
	"Error: Expected ',' or '}' after property value in JSON at position 320";
const NETWORK_BLIP = "Error: read ECONNRESET";
const GENERIC_UNEXPECTED = "The system encountered an unexpected error.";

const managers: any[] = [];

type TestClient = {
	readyState: number;
	bufferedAmount: number;
	sent: any[];
	send(data: string): void;
	close(code?: number, reason?: string): void;
};

function makeClient(): TestClient {
	return {
		readyState: 1,
		bufferedAmount: 0,
		sent: [],
		send(data: string) { this.sent.push(JSON.parse(data)); },
		close() { this.readyState = 3; },
	};
}

function makeManager(): any {
	const manager: any = new SessionManager();
	manager._testStore = {
		update: vi.fn(() => {}),
		get: vi.fn(() => undefined),
	};
	managers.push(manager);
	return manager;
}

function cleanupManager(manager: any): void {
	if (manager._statusHeartbeatTimer) {
		clearInterval(manager._statusHeartbeatTimer);
		manager._statusHeartbeatTimer = null;
	}
	for (const session of manager.sessions?.values?.() ?? []) {
		if (session.pendingAutoRetryTimer) clearTimeout(session.pendingAutoRetryTimer);
	}
	manager.sessionsWithConnectedClients?.clear();
	manager.sessions?.clear();
}

function putRetryStateSession(manager: any, overrides: Record<string, any> = {}): { session: any; client: TestClient; prompt: any } {
	const client = makeClient();
	const prompt = vi.fn(async () => ({ success: true }));
	const session = {
		id: `s-auto-retry-${Math.random().toString(36).slice(2)}`,
		title: "Auto retry policy test",
		titleGenerated: true,
		cwd: tmpRoot,
		status: "idle",
		statusVersion: 0,
		createdAt: Date.now(),
		lastActivity: Date.now(),
		clients: new Set([client]),
		promptQueue: new PromptQueue(),
		eventBuffer: new EventBuffer(),
		rpcClient: { prompt },
		lastTurnErrored: true,
		lastTurnErrorMessage: GENERIC_UNEXPECTED,
		lastPromptText: "retry the last user request",
		turnHadToolCalls: false,
		consecutiveErrorTurns: 1,
		transientRetryAttempts: 0,
		lifecycleGeneration: 0,
		...overrides,
	};
	manager.sessions.set(session.id, session);
	return { session, client, prompt };
}

function autoRetryPendingEvents(session: any): any[] {
	return session.eventBuffer
		.getAll()
		.map((entry: any) => entry.event)
		.filter((event: any) => event?.type === "auto_retry_pending");
}

afterEach(() => {
	while (managers.length > 0) cleanupManager(managers.pop());
});

// ── Provider-backoff path: effectively unbounded ──────────────────────────

describe("decideRetryPolicy — provider overload / rate-limit", () => {
	it("schedules a retry for the overloaded_error JSON sample", () => {
		const r = decideRetryPolicy(OVERLOAD_JSON, 0);
		assert.equal(r.retry, true);
		assert.equal((r as any).reason, "provider-backoff");
		assert.equal((r as any).attempt, 1);
	});

	it("schedules a retry for rate_limit_error", () => {
		const r = decideRetryPolicy(RATE_LIMIT_JSON, 0);
		assert.equal(r.retry, true);
		assert.equal((r as any).reason, "provider-backoff");
	});

	it("schedules a retry for HTTP 429 / 529", () => {
		for (const msg of ["HTTP 429 Too Many Requests", "status 429", "HTTP 529", "statusCode: 529"]) {
			const r = decideRetryPolicy(msg, 0);
			assert.equal(r.retry, true, `expected retry for: ${msg}`);
			assert.equal((r as any).reason, "provider-backoff", `expected provider-backoff for: ${msg}`);
		}
	});

	it("does NOT stop at the 3-attempt bounded cap for overload errors", () => {
		// Attempts well past TRANSIENT_MAX_ATTEMPTS still retry.
		for (const prior of [3, 5, 10, 50, 100, 1000]) {
			const r = decideRetryPolicy(OVERLOAD_JSON, prior);
			assert.equal(r.retry, true, `expected retry at priorAttempts=${prior}`);
			assert.equal((r as any).reason, "provider-backoff");
		}
	});

	it("backoff grows 1s → 2s → 4s → 8s with no jitter (random=0.5)", () => {
		const delays = [0, 1, 2, 3].map(prior => {
			const r = decideRetryPolicy(OVERLOAD_JSON, prior, { random: () => 0.5 });
			assert.equal(r.retry, true);
			return (r as any).delayMs as number;
		});
		assert.deepEqual(delays, [1000, 2000, 4000, 8000]);
	});

	it("caps delay at 300_000 ms (5 minutes) for large attempt numbers", () => {
		// random=0.5 → multiplier=1.0 → raw_capped = min(2^(n-1)*1000, 300_000)
		for (const prior of [9, 10, 20, 100]) {
			const r = decideRetryPolicy(OVERLOAD_JSON, prior, { random: () => 0.5 });
			const delayMs = (r as any).delayMs as number;
			assert.ok(delayMs <= PROVIDER_BACKOFF_MAX_MS, `cap violated at prior=${prior}: ${delayMs}`);
		}
		// Specifically: prior=9 → attempt=10 → raw=512_000 → capped to 300_000.
		const r10 = decideRetryPolicy(OVERLOAD_JSON, 9, { random: () => 0.5 });
		assert.equal((r10 as any).delayMs, 300_000);
	});

	it("applies ±20% jitter (random=0 → 0.8x, random→1 → 1.2x, bounded by cap)", () => {
		const low = decideRetryPolicy(OVERLOAD_JSON, 0, { random: () => 0 });
		assert.equal((low as any).delayMs, 800);

		const high = decideRetryPolicy(OVERLOAD_JSON, 0, { random: () => 0.999999 });
		const hd = (high as any).delayMs as number;
		assert.ok(hd > 1190 && hd <= 1200, `expected ~1200, got ${hd}`);

		// Jitter applied at the cap must still respect the cap.
		const capHigh = decideRetryPolicy(OVERLOAD_JSON, 20, { random: () => 0.999999 });
		assert.ok((capHigh as any).delayMs <= PROVIDER_BACKOFF_MAX_MS);
	});
});

// ── Bounded path: existing behaviour preserved ────────────────────────────

describe("decideRetryPolicy — non-provider transient (bounded)", () => {
	it("schedules a retry for JSON parse glitches with 1s/2s/4s delays", () => {
		const delays = [0, 1, 2].map(prior => {
			const r = decideRetryPolicy(JSON_GLITCH, prior);
			assert.equal(r.retry, true);
			assert.equal((r as any).reason, "transient-error");
			return (r as any).delayMs as number;
		});
		assert.deepEqual(delays, [1000, 2000, 4000]);
	});

	it("schedules a retry for ECONNRESET (network blip) — bounded", () => {
		const r = decideRetryPolicy(NETWORK_BLIP, 0);
		assert.equal(r.retry, true);
		assert.equal((r as any).reason, "transient-error");
	});

	it("STOPS after 3 attempts for non-provider transient errors", () => {
		const r3 = decideRetryPolicy(JSON_GLITCH, 2); // attempt 3
		assert.equal(r3.retry, true);

		const r4 = decideRetryPolicy(JSON_GLITCH, 3); // attempt 4 → exhausted
		assert.equal(r4.retry, false);
		assert.equal((r4 as any).reason, "exhausted");

		const rN = decideRetryPolicy(NETWORK_BLIP, 10);
		assert.equal(rN.retry, false);
		assert.equal((rN as any).reason, "exhausted");
	});

	it("Validation-failed-for-tool errors follow the bounded path", () => {
		const r = decideRetryPolicy(
			'Validation failed for tool "verification_result": ...',
			0,
		);
		assert.equal(r.retry, true);
		assert.equal((r as any).reason, "transient-error");
	});
});

// ── Generic unexpected errors: bounded scheduler path ─────────────────────

describe("SessionManager generic unexpected auto-retry policy", () => {
	it("schedules generic unexpected agent errors at 1s/5s/60s while preserving Retry state", () => {
		const manager = makeManager();
		const { session } = putRetryStateSession(manager);
		for (const [attempt, expectedDelayMs] of [
			[1, 1000],
			[2, 5000],
			[3, 60_000],
		] as const) {
			manager.maybeAutoRetryTransient(session);

			assert.equal(session.lastTurnErrored, true, "the chat Retry affordance should remain available while auto-retry is pending");
			assert.ok(
				session.pendingAutoRetryTimer,
				`expected generic unexpected error to schedule auto-retry attempt ${attempt}`,
			);
			const pending = autoRetryPendingEvents(session).at(-1);
			assert.ok(pending, "expected auto_retry_pending event for generic unexpected error");
			assert.equal(pending.retryDelayMs, expectedDelayMs);
			assert.equal(pending.attempt, attempt);

			clearTimeout(session.pendingAutoRetryTimer);
			session.pendingAutoRetryTimer = undefined;
		}
	});

	it("uses the pending timer to call the existing auto retry path after the first 1s generic retry", async () => {
		vi.useFakeTimers({ toFake: ["setTimeout"] });
		const manager = makeManager();
		const baseText = "please retry this user request";
		const { session, prompt } = putRetryStateSession(manager, {
			lastPromptText: baseText,
		});

		manager.maybeAutoRetryTransient(session);

		assert.ok(session.pendingAutoRetryTimer, "expected a pending auto-retry timer for generic unexpected errors");
		assert.equal(session.transientRetryAttempts, 1, "the pending timer should retain the first retry attempt");
		assert.equal(session.lastPromptText, baseText, "retry bookkeeping should retain the unprefixed base text");
		vi.advanceTimersByTime(999);
		assert.equal(prompt.mock.calls.length, 0, "auto retry should not fire before its 1s delay");

		vi.advanceTimersByTime(1);
		await Promise.resolve();
		await Promise.resolve();

		assert.equal(prompt.mock.calls.length, 1, "generic auto retry should dispatch through retryLastPrompt(..., { auto: true })");
		assert.equal(
			prompt.mock.calls[0][0],
			`[System]: ${baseText}`,
			"the system-owned retry should prefix only the exact provider-facing text",
		);
		assert.equal(session.pendingAutoRetryTimer, undefined, "the fired auto-retry timer should be cleared");
		assert.equal(session.transientRetryAttempts, 1, "the auto retry should preserve its bounded retry attempt state");
		assert.equal(session.lastPromptText, baseText, "the provider prefix must not enter retry bookkeeping");
		assert.equal(session.promptQueue.length, 0, "the provider prefix must not create a durable queue row");
		assert.equal(session.lastTurnErrored, false, "retryLastPrompt should clear error state once the auto retry starts");
		assert.equal(session.status, "streaming");
	});

	it("schedules fetch failed transport errors through the visible bounded auto-retry path", () => {
		for (const message of ["fetch failed", "TypeError: fetch failed"]) {
			const manager = makeManager();
			const { session } = putRetryStateSession(manager, {
				lastTurnErrorMessage: message,
			});

			manager.maybeAutoRetryTransient(session);

			assert.ok(
				session.pendingAutoRetryTimer,
				`expected pendingAutoRetryTimer for ${message}`,
			);
			const pending = autoRetryPendingEvents(session).at(-1);
			assert.ok(pending, `expected auto_retry_pending for ${message}`);
			assert.equal(pending.retryDelayMs, 1000, `expected first bounded retry delay for ${message}`);
			assert.equal(pending.attempt, 1, `expected first bounded retry attempt for ${message}`);
			assert.equal(session.lastTurnErrored, true, `expected Retry affordance preserved for ${message}`);

			clearTimeout(session.pendingAutoRetryTimer);
			session.pendingAutoRetryTimer = undefined;
		}
	});

	it("stops after the third generic unexpected retry and leaves manual Retry available", () => {
		const manager = makeManager();
		const { session } = putRetryStateSession(manager);
		for (let i = 0; i < 3; i++) {
			manager.maybeAutoRetryTransient(session);
			if (session.pendingAutoRetryTimer) clearTimeout(session.pendingAutoRetryTimer);
			session.pendingAutoRetryTimer = undefined;
		}
		const emittedBeforeExhaustion = autoRetryPendingEvents(session).length;

		manager.maybeAutoRetryTransient(session);

		assert.equal(session.pendingAutoRetryTimer, undefined);
		assert.equal(
			autoRetryPendingEvents(session).length,
			emittedBeforeExhaustion,
			"exhausted generic auto-retry must not emit a new pending event",
		);
		assert.equal(session.lastTurnErrored, true, "after exhaustion the session should still expose manual Retry");
	});

	it("does not auto-retry deterministic generic-looking failures", () => {
		const nonRetryable = [
			"Authentication failed: invalid API key for provider",
			"Configuration error: model provider is not configured",
			"No API key found for openrouter",
			"Permission denied while reading workspace file",
			"User aborted the request",
			"Content policy violation: disallowed content",
			"ValidationError: invalid session id",
			"The system encountered an unexpected error: missing API key",
		];

		for (const message of nonRetryable) {
			const manager = makeManager();
			const { session } = putRetryStateSession(manager, {
				lastTurnErrorMessage: message,
			});

			manager.maybeAutoRetryTransient(session);

			assert.equal(session.pendingAutoRetryTimer, undefined, `did not expect auto-retry for: ${message}`);
			assert.equal(autoRetryPendingEvents(session).length, 0, `did not expect auto_retry_pending for: ${message}`);
		}
	});
});

// ── Non-transient: no retry ───────────────────────────────────────────────

describe("decideRetryPolicy — non-transient", () => {
	it("does not retry on empty error message", () => {
		const r = decideRetryPolicy("", 0);
		assert.equal(r.retry, false);
		assert.equal((r as any).reason, "non-transient");
	});

	it("does not retry on TypeError / generic JS error", () => {
		const r = decideRetryPolicy(
			"TypeError: cannot read properties of null",
			0,
		);
		assert.equal(r.retry, false);
		assert.equal((r as any).reason, "non-transient");
	});

	it("does not retry on a real review failure", () => {
		const r = decideRetryPolicy(
			"LLM review failed: 'reviewer' role not found in role store.",
			0,
		);
		assert.equal(r.retry, false);
	});
});
