// AUTO-GENERATED by scripts/testing-v2/codemod.mjs — do not edit the legacy source.
// Source: tests/headquarters-config-alias.test.ts
// Bucket: v2-core | Method: codemod | Classification: needs-withEnv
// Review: mutates process.env — wrap in withEnv(patch, fn) to restore in finally

import { afterAll, beforeAll, describe, it, vi } from "vitest";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {
	bobbitConfigDir,
	bobbitDir,
	bobbitStateDir,
	getProjectRoot,
	headquartersDir,
	normalProjectBobbitDir,
	setProjectRoot,
} from "../../src/server/bobbit-dir.ts";
import { ConfigCascade } from "../../src/server/agent/config-cascade.ts";
import { ProjectContext } from "../../src/server/agent/project-context.ts";
import {
	HEADQUARTERS_PROJECT_ID,
	HEADQUARTERS_PROJECT_NAME,
	ProjectRegistry,
	SYSTEM_PROJECT_ID,
} from "../../src/server/agent/project-registry.ts";
import { createMemFs } from "../harness/mem-fs.js";

const fixtureRoot = path.resolve("/memfs/headquarters-config-alias");
const originalProjectRoot = getProjectRoot();
const memoryFs = createMemFs();
const fsSpies: Array<{ mockRestore(): void }> = [];

beforeAll(() => {
	(memoryFs as any).rmdirSync = (value: fs.PathLike) => memoryFs.rmSync(value, { recursive: true, force: true });
	const methods = [
		"existsSync", "mkdirSync", "readFileSync", "writeFileSync", "appendFileSync",
		"readdirSync", "statSync", "lstatSync", "renameSync", "rmSync", "rmdirSync", "unlinkSync", "copyFileSync",
	] as const;
	for (const method of methods) {
		fsSpies.push((vi.spyOn as any)(fs, method).mockImplementation((...args: unknown[]) => (memoryFs as any)[method](...args)));
	}
	fsSpies.push(vi.spyOn(fs, "realpathSync").mockImplementation(((value: fs.PathLike) => {
		const resolved = path.resolve(String(value));
		if (!memoryFs.existsSync(resolved)) throw Object.assign(new Error(`ENOENT: realpath '${resolved}'`), { code: "ENOENT" });
		return resolved;
	}) as typeof fs.realpathSync));
	fsSpies.push(vi.spyOn(fs, "accessSync").mockImplementation(((value: fs.PathLike) => {
		if (!memoryFs.existsSync(value)) throw Object.assign(new Error(`ENOENT: access '${value}'`), { code: "ENOENT" });
	}) as typeof fs.accessSync));
	memoryFs.mkdirSync(fixtureRoot, { recursive: true });
});

afterAll(() => {
	setProjectRoot(originalProjectRoot);
	for (const spy of fsSpies.reverse()) spy.mockRestore();
});

function fixturePath(label: string): string {
	return path.join(fixtureRoot, label);
}

function minimalProject(id: string, name: string, rootPath: string, extra: Record<string, unknown> = {}) {
	return {
		id,
		name,
		rootPath,
		createdAt: Date.now(),
		colorLight: "#000000",
		colorDark: "#ffffff",
		...extra,
	} as any;
}

function tool(name: string, description: string) {
	return { name, description, group: "custom", hasRenderer: false } as any;
}

function withEnv<T>(updates: Record<string, string | undefined>, fn: () => T): T {
	const old = new Map(Object.keys(updates).map((key) => [key, process.env[key]]));
	try {
		for (const [key, value] of Object.entries(updates)) {
			if (value === undefined) delete process.env[key]; else process.env[key] = value;
		}
		return fn();
	} finally {
		for (const [key, value] of old) {
			if (value === undefined) delete process.env[key]; else process.env[key] = value;
		}
	}
}

describe("Headquarters storage and config aliasing", () => {
	it("bobbit-dir helpers split Headquarters from normal same-root project storage", async () => {
		const serverRoot = fixturePath("server-root");

		withEnv({ BOBBIT_DIR: undefined, BOBBIT_PI_DIR: undefined }, () => {
			setProjectRoot(serverRoot);
			assert.equal(path.resolve(headquartersDir()), path.resolve(path.join(serverRoot, ".bobbit", "headquarters")));
			assert.equal(path.resolve(bobbitDir()), path.resolve(path.join(serverRoot, ".bobbit", "headquarters")));
			assert.equal(path.resolve(bobbitStateDir()), path.resolve(path.join(serverRoot, ".bobbit", "headquarters", "state")));
			assert.equal(path.resolve(bobbitConfigDir()), path.resolve(path.join(serverRoot, ".bobbit", "headquarters", "config")));
			assert.equal(path.resolve(normalProjectBobbitDir(serverRoot)), path.resolve(path.join(serverRoot, ".bobbit")));
		});
	});

	it("BOBBIT_DIR and BOBBIT_PI_DIR override the Headquarters directory itself", async () => {
		const serverRoot = fixturePath("override-root");
		const custom = fixturePath("custom-hq");
		const legacy = fixturePath("legacy-hq");
		setProjectRoot(serverRoot);

		withEnv({ BOBBIT_DIR: custom, BOBBIT_PI_DIR: legacy }, () => {
			assert.equal(path.resolve(headquartersDir()), path.resolve(custom));
			assert.equal(path.resolve(bobbitStateDir()), path.resolve(path.join(custom, "state")));
			assert.equal(path.resolve(bobbitConfigDir()), path.resolve(path.join(custom, "config")));
		});

		withEnv({ BOBBIT_DIR: undefined, BOBBIT_PI_DIR: legacy }, () => {
			assert.equal(path.resolve(headquartersDir()), path.resolve(legacy));
			assert.equal(path.resolve(bobbitStateDir()), path.resolve(path.join(legacy, "state")));
			assert.equal(path.resolve(bobbitConfigDir()), path.resolve(path.join(legacy, "config")));
		});
	});

	it("ProjectContext stores Headquarters under Headquarters dir and normal same-root projects under <root>/.bobbit", async () => {
		const serverRoot = fixturePath("context-root");
		fs.mkdirSync(serverRoot, { recursive: true });

		withEnv({ BOBBIT_DIR: undefined, BOBBIT_PI_DIR: undefined }, () => {
			setProjectRoot(serverRoot);
			const headquartersRoot = path.join(serverRoot, ".bobbit", "headquarters");
			const hq = new ProjectContext(minimalProject(HEADQUARTERS_PROJECT_ID, HEADQUARTERS_PROJECT_NAME, headquartersRoot, { kind: "headquarters" }));
			const normal = new ProjectContext(minimalProject("normal", "Normal", serverRoot));

			assert.equal(path.resolve(hq.bobbitDir), path.resolve(bobbitDir()));
			assert.equal(path.resolve(hq.stateDir), path.resolve(bobbitStateDir()));
			assert.equal(path.resolve(hq.configDir), path.resolve(bobbitConfigDir()));
			assert.equal(path.resolve(hq.bobbitDir), path.resolve(headquartersRoot));

			assert.equal(path.resolve(normal.bobbitDir), path.resolve(path.join(serverRoot, ".bobbit")));
			assert.equal(path.resolve(normal.stateDir), path.resolve(path.join(serverRoot, ".bobbit", "state")));
			assert.equal(path.resolve(normal.configDir), path.resolve(path.join(serverRoot, ".bobbit", "config")));
		});
	});

	it("ConfigCascade treats projectId=headquarters as server scope for roles, tools, and tool policies", async () => {
		const serverRole = {
			name: "hq-role",
			label: "Server HQ Role",
			promptTemplate: "server prompt",
			accessory: "none",
			model: "server/model",
			thinkingLevel: "medium",
			createdAt: 0,
			updatedAt: 0,
		} as any;
		const projectRole = {
			...serverRole,
			label: "Project Shadow Role",
			promptTemplate: "project prompt",
			model: "project/model",
			thinkingLevel: "high",
		} as any;

		const serverTool = tool("hq-tool", "server tool");
		const projectTool = tool("hq-tool", "project shadow tool");
		const hqWorkflow = { id: "hq-flow", name: "HQ Flow", gates: [{ id: "plan", name: "Plan" }] } as any;

		const builtins = {
			getRoles: () => [],
			getTools: () => [],
			getToolGroupPolicies: () => ({}),
		} as any;
		const serverStores = {
			getRoles: () => [serverRole],
			getTools: () => [serverTool],
			getToolGroupPolicies: () => ({ shell: "ask" as const }),
		} as any;
		let projectContextReads = 0;
		const fakePcm = {
			getOrCreate: (id: string) => {
				if (id !== HEADQUARTERS_PROJECT_ID) return undefined;
				projectContextReads++;
				return {
					roleStore: {
						getAllLocal: () => [projectRole],
						getLocal: () => projectRole,
					},
					toolManager: { getLocalTools: () => [projectTool] },
					toolGroupPolicyStore: { getAll: () => ({ shell: "never" as const }) },
					workflowStore: { getAllLocal: () => [hqWorkflow] },
				};
			},
		} as any;

		// Explicit empty pack roots avoid scanning the real home/default pack trees;
		// every layer needed by this declaration is the pre-authored snapshot above.
		const emptyPackRoot = fixturePath("immutable-empty-pack-root");
		const cascade = new ConfigCascade(builtins, serverStores, fakePcm, undefined, undefined, emptyPackRoot, emptyPackRoot);

		const role = cascade.resolveRoles(HEADQUARTERS_PROJECT_ID).find((entry: any) => entry.item.name === "hq-role");
		assert.ok(role);
		assert.equal(role!.origin, "server");
		assert.equal(role!.item.promptTemplate, "server prompt");
		assert.equal(cascade.resolveRoleModel("hq-role", HEADQUARTERS_PROJECT_ID), "server/model");
		assert.equal(cascade.resolveRoleThinkingLevel("hq-role", HEADQUARTERS_PROJECT_ID), "medium");
		assert.equal(cascade.resolveRolePromptTemplate("hq-role", HEADQUARTERS_PROJECT_ID), "server prompt");

		const resolvedTool = cascade.resolveTools(HEADQUARTERS_PROJECT_ID).find((entry: any) => entry.item.name === "hq-tool");
		assert.ok(resolvedTool);
		assert.equal(resolvedTool!.origin, "server");
		assert.equal(resolvedTool!.item.description, "server tool");

		const policies = cascade.resolveToolGroupPolicies(HEADQUARTERS_PROJECT_ID);
		assert.equal(policies.shell.origin, "server");
		assert.equal(policies.shell.policy, "ask");

		assert.equal(cascade.resolveWorkflows().length, 0, "server scope still has no workflows");
		const workflows = cascade.resolveWorkflows(HEADQUARTERS_PROJECT_ID);
		assert.equal(workflows.length, 1, "Headquarters workflow lookup remains project-scoped");
		assert.equal(workflows[0].origin, "project");
		assert.equal(workflows[0].item.id, "hq-flow");
		assert.ok(projectContextReads > 0, "workflow exception should still read the Headquarters project context");
	});
});

describe("ProjectRegistry Headquarters ordering", () => {
	it("ensureHeadquartersProject creates stable Headquarters as a reorderable project", async () => {
		const stateDir = fixturePath("registry-state");
		const configDir = fixturePath("registry-config");
		const serverRoot = fixturePath("registry-root");
		const bRoot = fixturePath("registry-b");
		// Vitest retries the same declaration in-process. Restore the immutable
		// empty snapshot first so a failed attempt cannot poison the next one.
		for (const dir of [stateDir, configDir, serverRoot, bRoot]) memoryFs.rmSync(dir, { recursive: true, force: true });
		const hqRoot = path.join(serverRoot, ".bobbit", "headquarters");
		const systemRoot = path.join(stateDir, "system-project");
		for (const dir of [stateDir, configDir, systemRoot, hqRoot, bRoot]) fs.mkdirSync(dir, { recursive: true });

		const registry = new ProjectRegistry(stateDir);
		registry.registerSystemProject(systemRoot);
		(registry as any).ensureHeadquartersProject(hqRoot, { stateDir, configDir });

		const hq = registry.get(HEADQUARTERS_PROJECT_ID) as any;
		assert.ok(hq, "Headquarters should be registered by stable id");
		assert.equal(hq.name, HEADQUARTERS_PROJECT_NAME);
		assert.equal(hq.kind, "headquarters");
		assert.equal(path.resolve(hq.rootPath), path.resolve(hqRoot));
		assert.notEqual(hq.hidden, true);
		assert.notEqual(hq.provisional, true);
		assert.equal(hq.position, 0, "Headquarters participates in user-controlled ordering (anchored first only by default)");

		// Seed the two normal records from an immutable post-registration snapshot.
		// Registration/preflight has its own owners; this declaration exercises only
		// Headquarters identity and ordering, without probing the host filesystem.
		const sameRootNormal = minimalProject("same-root-normal", "Server Root Normal", serverRoot, { position: 1 });
		const b = minimalProject("normal-b", "B", bRoot, { position: 2 });
		(registry as any).projects.set(sameRootNormal.id, sameRootNormal);
		(registry as any).projects.set(b.id, b);
		(registry as any).normalizeVisiblePositions();
		registry.save();
		// Headquarters is now a first-class reorderable project and MUST be included
		// in the reorder payload alongside the normal projects.
		const reordered = registry.setVisibleOrder([b.id, HEADQUARTERS_PROJECT_ID, sameRootNormal.id]);
		assert.deepEqual(reordered.map(project => project.id), [b.id, HEADQUARTERS_PROJECT_ID, sameRootNormal.id]);
		assert.deepEqual(
			registry.list().filter(project => !project.hidden && project.id !== SYSTEM_PROJECT_ID).map(project => project.id),
			[b.id, HEADQUARTERS_PROJECT_ID, sameRootNormal.id],
		);
		assert.throws(
			() => registry.setVisibleOrder([b.id, sameRootNormal.id]),
			/stale/i,
			"reorder payloads must include Headquarters now that it participates in ordering",
		);
		assert.throws(
			() => registry.register("HQ Dir", hqRoot, { acceptCanonical: true }),
			/Headquarters|immutable/i,
			"normal projects cannot be registered at the physical Headquarters directory",
		);

		// When Headquarters is hidden from project lists it is excluded from the
		// reorder scope: the client omits it, so setVisibleOrder must accept a
		// payload without it, preserve its slot, and reorder only the normals.
		registry.setVisibleOrder([HEADQUARTERS_PROJECT_ID, sameRootNormal.id, b.id]);
		const hiddenReordered = registry.setVisibleOrder([b.id, sameRootNormal.id], { excludeIds: [HEADQUARTERS_PROJECT_ID] });
		assert.deepEqual(
			hiddenReordered.map(project => project.id),
			[HEADQUARTERS_PROJECT_ID, b.id, sameRootNormal.id],
			"Headquarters keeps its slot while the excluded reorder repositions the normals",
		);
	});
});
