// AUTO-GENERATED by scripts/testing-v2/codemod.mjs — do not edit the legacy source.
// Source: tests/oauth-complete-empty-code.test.ts
// Bucket: v2-core | Method: codemod | Classification: needs-withEnv
// Review: mutates process.env — wrap in withEnv(patch, fn) to restore in finally

import { guardProcessEnv } from "./helpers/env-guard.js";
guardProcessEnv();

/**
 * Unit test for `oauthComplete` in `src/server/auth/oauth.ts`.
 *
 * Contract:
 *   - Empty `authCode`              → { success: false, error: "code required" }.
 *   - Whitespace-only `authCode`    → { success: false, error: "code required" }.
 *   - Unknown `flowId`              → { success: false, error: "Unknown or expired flow ID" }.
 */
import { afterEach, describe, it } from "vitest";
import assert from "node:assert/strict";
import type { AuthInteraction, Credential, Models } from "@earendil-works/pi-ai";
import { mkdtempSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

const tmp = mkdtempSync(path.join(tmpdir(), "bobbit-oauth-empty-"));
mkdirSync(path.join(tmp, "agent"), { recursive: true });
process.env.BOBBIT_AGENT_DIR = path.join(tmp, "agent");

const { oauthCancel, oauthComplete, oauthStart } = await import("../../src/server/auth/oauth.js");
const activeAnthropicFlowIds = new Set<string>();
const OFFLINE_FETCH: typeof fetch = async () => {
	throw new Error("OAuth tests must not call a provider");
};

interface PendingLogin {
	aborts: number;
}

/**
 * Avoid Pi's process-wide loopback listener: the injected public Models seam
 * still receives Bobbit's AbortSignal, so empty input exercises cancellation.
 */
function abortAwareAnthropicModels(pending: PendingLogin): Pick<Models, "login"> {
	return {
		login: ((_provider: string, _type: string, interaction: AuthInteraction) => {
			interaction.notify({
				type: "auth_url",
				url: "https://example.invalid/authorize",
				instructions: "Mocked OAuth interaction",
			});
			const signal = interaction.signal;
			if (!signal) return Promise.reject(new Error("Bobbit must provide an OAuth abort signal"));
			return new Promise<Credential>((_resolve, reject) => {
				const abort = () => {
					pending.aborts++;
					const reason = signal.reason;
					reject(reason instanceof Error ? reason : new Error("OAuth flow cancelled"));
				};
				signal.addEventListener("abort", abort, { once: true });
				if (signal.aborted) abort();
			});
		}) as Models["login"],
	};
}

async function startAnthropicFlow(): Promise<{ start: Awaited<ReturnType<typeof oauthStart>>; pending: PendingLogin }> {
	const pending: PendingLogin = { aborts: 0 };
	const start = await oauthStart("anthropic", OFFLINE_FETCH, abortAwareAnthropicModels(pending));
	activeAnthropicFlowIds.add(start.flowId);
	return { start, pending };
}

afterEach(async () => {
	for (const flowId of activeAnthropicFlowIds) oauthCancel(flowId, "anthropic");
	activeAnthropicFlowIds.clear();
	// Allow Pi's aborted login promise to settle before the next test acquires
	// the intentional process-wide Anthropic callback-port lease.
	for (let i = 0; i < 20; i++) await Promise.resolve();
});

describe("oauthComplete — input validation", () => {
	it("unknown flowId → 'Unknown or expired flow ID'", async () => {
		const res = await oauthComplete("flow-does-not-exist", "anything");
		assert.deepEqual(res, { success: false, error: "Unknown or expired flow ID" });
	});

	// The empty-code branch lives downstream of the flow lookup. We can't
	// register a real flow without an upstream provider, but the flow lookup
	// fails first for unknown ids. We therefore start an Anthropic flow through
	// the injected abort-aware Models seam, then complete it with empty/
	// whitespace codes. The Anthropic branch enforces "code required" while
	// releasing the pending interaction.
	it("empty authCode for a real flow → 'code required' and cancels the interaction", async () => {
		const { start, pending } = await startAnthropicFlow();
		assert.ok(start.flowId, "flow id should be returned");

		const res = await oauthComplete(start.flowId, "");
		assert.deepEqual(res, { success: false, error: "code required" });
		assert.equal(pending.aborts, 1, "empty completion must cancel the pending OAuth interaction");

		const retry = await startAnthropicFlow();
		assert.ok(retry.start.flowId, "cancellation must release the Anthropic flow lease for an immediate retry");
	});

	it("whitespace-only authCode for a real flow → 'code required' and cancels the interaction", async () => {
		const { start, pending } = await startAnthropicFlow();
		const res = await oauthComplete(start.flowId, "   \t\n  ");
		assert.deepEqual(res, { success: false, error: "code required" });
		assert.equal(pending.aborts, 1, "whitespace completion must cancel the pending OAuth interaction");
	});
});
