// AUTO-GENERATED by scripts/testing-v2/codemod.mjs — do not edit the legacy source.
// Source: tests/pi-extension-discovery.test.ts
// Bucket: v2-core | Method: codemod | Classification: clean

import { describe, it } from "vitest";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {
	discoverPiExtensionTools,
	discoverPiExtensionToolsSync,
	PI_EXTENSION_DISCOVERY_RESULT_MARKER,
	type PiExtensionDiscoveryBackend,
	type PiExtensionDiscoveryProbeRequest,
	type PiExtensionDiscoveryProbeResult,
} from "../../src/server/agent/pi-extension-discovery.js";
import {
	computePiExtensionDiscoveryCacheKey,
	computePiExtensionDiscoveryCacheKeyWithDiagnostics,
	PI_EXTENSION_DISCOVERY_HASH_LIMITS,
	loadPiExtensionContributionsWithDiscovery,
	loadPiExtensionContributionsWithDiscoverySync,
} from "../../src/server/agent/pi-extension-contributions.js";

function tempDir(prefix = "bobbit-pi-ext-discovery-"): string {
	return fs.mkdtempSync(path.join(os.tmpdir(), prefix));
}

function write(file: string, text: string): string {
	fs.mkdirSync(path.dirname(file), { recursive: true });
	fs.writeFileSync(file, text, "utf-8");
	return file;
}

function probeResult(overrides: Partial<PiExtensionDiscoveryProbeResult> = {}): PiExtensionDiscoveryProbeResult {
	return { stdout: "", stderr: "", exitCode: 0, timedOut: false, ...overrides };
}

function marked(payload: unknown, prefix = ""): PiExtensionDiscoveryProbeResult {
	return probeResult({ stdout: `${prefix}${PI_EXTENSION_DISCOVERY_RESULT_MARKER}${JSON.stringify(payload)}\n` });
}

function backend(
	result: PiExtensionDiscoveryProbeResult | ((request: PiExtensionDiscoveryProbeRequest) => PiExtensionDiscoveryProbeResult),
	calls: PiExtensionDiscoveryProbeRequest[] = [],
): PiExtensionDiscoveryBackend {
	const invoke = (request: PiExtensionDiscoveryProbeRequest): PiExtensionDiscoveryProbeResult => {
		calls.push(request);
		return typeof result === "function" ? result(request) : result;
	};
	return { run: async (request) => invoke(request), runSync: invoke };
}

function okBackend(tools: unknown[], calls: PiExtensionDiscoveryProbeRequest[] = []): PiExtensionDiscoveryBackend {
	return backend(marked({ status: "ok", tools }), calls);
}

function failedBackend(code: string, message = `${code} detail`): PiExtensionDiscoveryBackend {
	return backend(marked({ status: "failed", code, message }));
}

function manifest(piExtensions: string[]): any {
	return { schema: 2, name: "pack", contents: { piExtensions } };
}

describe("pi extension discovery", () => {
	it("skips executable probing before trust and does not invoke the backend", async () => {
		const dir = tempDir();
		try {
			const marker = path.join(dir, "executed.txt").replace(/\\/g, "\\\\");
			const entry = write(path.join(dir, "extension.mjs"), `import fs from "node:fs"; fs.writeFileSync("${marker}", "ran");`);
			const calls: PiExtensionDiscoveryProbeRequest[] = [];
			const result = await discoverPiExtensionTools(entry, {
				trustAccepted: false,
				backend: okBackend([{ name: "should_not_run" }], calls),
			});
			assert.equal(result.status, "skipped");
			assert.deepEqual(result.tools, []);
			assert.equal(calls.length, 0);
			assert.equal(fs.existsSync(path.join(dir, "executed.txt")), false);
			assert.ok(result.cacheKey);
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});

	it("parses and normalizes backend output deterministically", async () => {
		const dir = tempDir();
		try {
			const entry = write(path.join(dir, "extension.mjs"), "export default function () {}\n");
			const calls: PiExtensionDiscoveryProbeRequest[] = [];
			const result = await discoverPiExtensionTools(entry, {
				trustAccepted: true,
				timeoutMs: 321,
				cwd: dir,
				backend: backend(marked({
					status: "ok",
					tools: [
						{ name: " object_tool ", description: " object desc ", inputSchema: { type: "object" } },
						{ name: "object_tool", description: "duplicate" },
						{ name: "string_tool", description: "", inputSchema: [] },
						{ id: "ignored" },
						null,
					],
				}, "extension noise\n"), calls),
			});
			assert.equal(result.status, "ok");
			assert.deepEqual(result.tools, [
				{ name: "object_tool", description: "object desc", inputSchema: { type: "object" } },
				{ name: "string_tool" },
			]);
			assert.equal(calls.length, 1);
			assert.equal(calls[0]?.entryPath, entry);
			assert.equal(calls[0]?.timeoutMs, 321);
			assert.equal(calls[0]?.cwd, dir);
			assert.ok(result.cacheKey);
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});

	it("uses the injected sync backend without creating a probe process", () => {
		const dir = tempDir();
		try {
			const entry = write(path.join(dir, "extension.ts"), "export default function (pi: any) { pi.registerTool({ name: 'not_executed' }); }\n");
			const calls: PiExtensionDiscoveryProbeRequest[] = [];
			const result = discoverPiExtensionToolsSync(entry, {
				trustAccepted: true,
				backend: okBackend([{ name: "sync_tool", description: "from backend" }], calls),
			});
			assert.equal(result.status, "ok");
			assert.deepEqual(result.tools, [{ name: "sync_tool", description: "from backend" }]);
			assert.equal(calls.length, 1);
			assert.equal(calls[0]?.entryPath, entry);
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});

	it("threads the injected backend through async and sync contribution loaders", async () => {
		const dir = tempDir();
		try {
			const packRoot = path.join(dir, "pack");
			write(path.join(packRoot, "pi-extensions", "demo", "extension.js"), "throw new Error('must not execute in unit');\n");
			const asyncCalls: PiExtensionDiscoveryProbeRequest[] = [];
			const [asyncRow] = await loadPiExtensionContributionsWithDiscovery(packRoot, manifest(["demo"]), {
				trustAccepted: true,
				discoveryBackend: okBackend([{ name: "async_tool" }], asyncCalls),
			});
			assert.equal(asyncRow.discovery.status, "ok");
			assert.deepEqual(asyncRow.discovery.tools, [{ name: "async_tool" }]);
			assert.equal(asyncCalls.length, 1);

			const syncCalls: PiExtensionDiscoveryProbeRequest[] = [];
			const [syncRow] = loadPiExtensionContributionsWithDiscoverySync(packRoot, manifest(["demo"]), {
				trustAccepted: true,
				discoveryBackend: okBackend([{ name: "sync_tool" }], syncCalls),
			});
			assert.equal(syncRow.discovery.status, "ok");
			assert.deepEqual(syncRow.discovery.tools, [{ name: "sync_tool" }]);
			assert.equal(syncCalls.length, 1);
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});

	it("preserves static rows without invoking an untrusted discovery backend", () => {
		const dir = tempDir();
		try {
			const packRoot = path.join(dir, "pack");
			write(path.join(packRoot, "pi-extensions", "demo", "extension.js"), "throw new Error('must not execute');\n");
			const calls: PiExtensionDiscoveryProbeRequest[] = [];
			const [row] = loadPiExtensionContributionsWithDiscoverySync(packRoot, manifest(["demo"]), {
				trustAccepted: false,
				discoveryBackend: okBackend([{ name: "should_not_run" }], calls),
			});
			assert.equal(row.discovery.status, "skipped");
			assert.equal(row.discovery.diagnostic?.code, "trust_required");
			assert.equal(calls.length, 0);
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});

	it("maps backend security decisions without executing hostile fixtures", async () => {
		const dir = tempDir();
		try {
			const entry = write(path.join(dir, "extension.mjs"), "export default function () {}\n");
			for (const code of ["PROBE_FS_READ_DENIED", "PROBE_FS_WRITE_DENIED", "PROBE_FS_API_DENIED", "PROBE_CONFINEMENT_DENIED"]) {
				const result = await discoverPiExtensionTools(entry, {
					trustAccepted: true,
					backend: failedBackend(code, `${code}\nsecret detail`),
				});
				assert.equal(result.status, "failed", code);
				assert.equal(result.diagnostic?.status, "discovery-failed", code);
				assert.equal(result.diagnostic?.code, code);
				assert.equal(result.diagnostic?.message, `${code} secret detail`);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});

	it("maps timeout, unsettled-await, invalid-output, and backend exceptions", async () => {
		const dir = tempDir();
		try {
			const entry = write(path.join(dir, "extension.mjs"), "export default function () {}\n");
			const timedOut = await discoverPiExtensionTools(entry, {
				trustAccepted: true,
				timeoutMs: 77,
				backend: backend(probeResult({ timedOut: true })),
			});
			assert.equal(timedOut.diagnostic?.code, "probe_timeout");
			assert.match(timedOut.diagnostic?.message ?? "", /77ms/);

			const unsettled = discoverPiExtensionToolsSync(entry, {
				trustAccepted: true,
				backend: backend(probeResult({ stderr: "Warning: unsettled top-level await" })),
			});
			assert.equal(unsettled.diagnostic?.code, "probe_timeout");

			const invalid = discoverPiExtensionToolsSync(entry, {
				trustAccepted: true,
				backend: backend(probeResult({ stderr: "bad\n\toutput" , exitCode: 2 })),
			});
			assert.equal(invalid.diagnostic?.code, "probe_invalid_output");
			assert.match(invalid.diagnostic?.message ?? "", /bad output/);

			const throwing: PiExtensionDiscoveryBackend = {
				run: async () => { throw new Error("backend exploded\nwith detail"); },
				runSync: () => { throw new Error("backend exploded\nwith detail"); },
			};
			const thrown = await discoverPiExtensionTools(entry, { trustAccepted: true, backend: throwing });
			assert.equal(thrown.diagnostic?.code, "probe_build_failed");
			assert.equal(thrown.diagnostic?.message, "backend exploded with detail");
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});

	it("reports missing entries before invoking the backend", async () => {
		const dir = tempDir();
		try {
			const calls: PiExtensionDiscoveryProbeRequest[] = [];
			const result = await discoverPiExtensionTools(path.join(dir, "missing.mjs"), {
				trustAccepted: true,
				backend: okBackend([], calls),
			});
			assert.equal(result.status, "failed");
			assert.equal(result.diagnostic?.code, "entry_not_found");
			assert.equal(calls.length, 0);
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});

	it("does not write generated probe metadata when using the injected backend", async () => {
		const dir = tempDir();
		try {
			const entry = write(path.join(dir, "extension.mjs"), "export default function () {}\n");
			const before = fs.readdirSync(dir).sort();
			const result = await discoverPiExtensionTools(entry, { trustAccepted: true, backend: okBackend([{ name: "clean_probe" }]) });
			assert.equal(result.status, "ok");
			assert.deepEqual(fs.readdirSync(dir).sort(), before);
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});

	it("changes cache keys when local helper sources change", () => {
		const dir = tempDir();
		try {
			const entry = write(path.join(dir, "extension.mjs"), "import './helper.js'; export default function () {}\n");
			const helper = write(path.join(dir, "helper.js"), "export const value = 1;\n");
			const first = computePiExtensionDiscoveryCacheKey(entry);
			fs.writeFileSync(helper, "export const value = 2;\n", "utf-8");
			const second = computePiExtensionDiscoveryCacheKey(entry);
			assert.ok(first);
			assert.ok(second);
			assert.notEqual(first, second);
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});

	it("keeps production discovery hash defaults and bounds file count", () => {
		assert.equal(PI_EXTENSION_DISCOVERY_HASH_LIMITS.maxFiles, 1000);
		const dir = tempDir();
		try {
			const maxFiles = 3;
			const entry = write(path.join(dir, "extension.mjs"), "export default function () {}\n");
			for (let i = 0; i < maxFiles + 1; i++) write(path.join(dir, `helper-${i}.js`), `export const value${i} = ${i};\n`);
			const result = computePiExtensionDiscoveryCacheKeyWithDiagnostics(entry, { hashLimits: { maxFiles } });
			assert.equal(result.cacheKey, undefined);
			assert.equal(result.diagnostic?.code, "hash_file_count_limit");
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});

	it("bounds discovery cache key depth and per-file size", () => {
		const dir = tempDir();
		try {
			const entry = write(path.join(dir, "extension.mjs"), "export default function () {}\n");
			let nested = dir;
			for (let i = 0; i < PI_EXTENSION_DISCOVERY_HASH_LIMITS.maxDepth + 1; i++) nested = path.join(nested, `d${i}`);
			write(path.join(nested, "too-deep.js"), "export const deep = true;\n");
			assert.equal(computePiExtensionDiscoveryCacheKeyWithDiagnostics(entry).diagnostic?.code, "hash_depth_limit");

			fs.rmSync(path.join(dir, "d0"), { recursive: true, force: true });
			write(path.join(dir, "large.js"), "x".repeat(PI_EXTENSION_DISCOVERY_HASH_LIMITS.maxFileBytes + 1));
			assert.equal(computePiExtensionDiscoveryCacheKeyWithDiagnostics(entry).diagnostic?.code, "hash_file_size_limit");
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});

	it("preserves extension-level visibility when discovery fails", async () => {
		const dir = tempDir();
		try {
			const packRoot = path.join(dir, "pack");
			write(path.join(packRoot, "pi-extensions", "demo", "extension.js"), "export default function () {}\n");
			const [row] = await loadPiExtensionContributionsWithDiscovery(packRoot, manifest(["demo"]), {
				trustAccepted: true,
				discoveryBackend: failedBackend("probe_failed", "activation boom"),
			});
			assert.equal(row.discovery.status, "failed");
			assert.equal(row.discovery.tools.length, 0);
			assert.equal(row.diagnostic.status, "discovery-failed");
			assert.match(row.diagnostic.message, /activation boom/);
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
});
