// AUTO-GENERATED by scripts/testing-v2/codemod.mjs — do not edit the legacy source.
// Source: tests/project-sandbox-agent-dir-mounts.test.ts
// Bucket: v2-core | Method: codemod | Classification: clean

import { describe, it } from "vitest";
import assert from "node:assert/strict";
import path from "node:path";
import { ProjectSandbox, getAgentDirMountStaleness, getModelsJsonContentStaleness, getStateDirMountStaleness } from "../../src/server/agent/project-sandbox.js";
import { SandboxManager } from "../../src/server/agent/sandbox-manager.js";

type Call = string | [string, string];

function mount(source: string, destination: string, rw = true, mode = ""): { Source: string; Destination: string; RW: boolean; Mode: string } {
	return { Source: source, Destination: destination, RW: rw, Mode: mode };
}

function makeSandbox(): ProjectSandbox {
	return new ProjectSandbox({
		projectId: "stale-agent-dir-mounts",
		projectDir: path.join(process.cwd(), "tmp-project"),
		repoUrl: "https://example.test/repo.git",
		image: "bobbit-test-image:latest",
	});
}

function requiredStateMounts(stateDir: string) {
	return [
		mount(path.join(stateDir, "sessions"), "/bobbit-state/sessions"),
		mount(path.join(stateDir, "tool-guard"), "/bobbit-state/tool-guard"),
		mount(path.join(stateDir, "html-snapshots"), "/bobbit-state/html-snapshots"),
		mount(path.join(stateDir, "google-code-assist"), "/bobbit-state/google-code-assist", false, "ro"),
		mount(path.join(stateDir, "tool-result-error-bridge"), "/bobbit-state/tool-result-error-bridge", false, "ro"),
		mount(path.join(stateDir, "aigw-dns-guard"), "/bobbit-state/aigw-dns-guard", false, "ro"),
	];
}

describe("ProjectSandbox agent-dir mount staleness", () => {
	it("accepts mounts that match the active agent sessions dir and read-only models.json", () => {
		const expected = {
			sessionsDir: path.resolve("/agent-b/sessions"),
			modelsJson: path.resolve("/agent-b/models.json"),
			modelsJsonExists: true,
		};

		const result = getAgentDirMountStaleness([
			mount(expected.sessionsDir, "/home/node/.bobbit/agent/sessions"),
			mount(expected.modelsJson, "/home/node/.bobbit/agent/models.json", false, "ro"),
		], expected);

		assert.equal(result.stale, false, result.reason);
	});

	it("marks containers stale when sessions or models mounts point at a previous agent dir", () => {
		const expected = {
			sessionsDir: path.resolve("/agent-b/sessions"),
			modelsJson: path.resolve("/agent-b/models.json"),
			modelsJsonExists: true,
		};

		const sessionsStale = getAgentDirMountStaleness([
			mount(path.resolve("/agent-a/sessions"), "/home/node/.bobbit/agent/sessions"),
			mount(expected.modelsJson, "/home/node/.bobbit/agent/models.json", false, "ro"),
		], expected);
		assert.equal(sessionsStale.stale, true);
		assert.match(sessionsStale.reason ?? "", /sessions mount/i);

		const modelsStale = getAgentDirMountStaleness([
			mount(expected.sessionsDir, "/home/node/.bobbit/agent/sessions"),
			mount(path.resolve("/agent-a/models.json"), "/home/node/.bobbit/agent/models.json", false, "ro"),
		], expected);
		assert.equal(modelsStale.stale, true);
		assert.match(modelsStale.reason ?? "", /models\.json mount/i);
	});

	it("marks containers stale when the active agent dir has no models.json but the container still mounts one", () => {
		const expected = {
			sessionsDir: path.resolve("/agent-b/sessions"),
			modelsJson: path.resolve("/agent-b/models.json"),
			modelsJsonExists: false,
		};

		const result = getAgentDirMountStaleness([
			mount(expected.sessionsDir, "/home/node/.bobbit/agent/sessions"),
			mount(path.resolve("/agent-a/models.json"), "/home/node/.bobbit/agent/models.json", false, "ro"),
		], expected);

		assert.equal(result.stale, true);
		assert.match(result.reason ?? "", /still has an agent models\.json mount/i);
	});

	it("detects an atomically replaced models.json inode by comparing mounted content", () => {
		assert.equal(getModelsJsonContentStaleness('{"models":["new"]}', '{"models":["new"]}').stale, false);
		const stale = getModelsJsonContentStaleness('{"models":["new"]}', '{"models":["old"]}');
		assert.equal(stale.stale, true);
		assert.match(stale.reason ?? "", /atomically published host file/);
	});

	it("recreates a live container and emits normal recovery events after atomic model publication", async () => {
		const sandbox = makeSandbox();
		const calls: Call[] = [];
		const events: string[] = [];
		(sandbox as any).containerId = "old-container-id";
		(sandbox as any)._status = "ready";
		(sandbox as any)._removeContainer = async (containerId: string) => { calls.push(["remove", containerId]); };
		(sandbox as any)._initContainer = async () => { calls.push("create"); (sandbox as any).containerId = "new-container-id"; };
		sandbox.onHealthEvent((event) => events.push(`${event.type}:${event.containerId}`));

		await sandbox.refreshAgentModelMount();

		assert.deepEqual(calls, [["remove", "old-container-id"], "create"]);
		assert.deepEqual(events, ["container-died:old-container-id", "container-recovered:new-container-id"]);
		assert.equal(sandbox.getStatus().status, "ready");
	});

	it("recreates an existing project container before reconnecting when agent-dir mounts are stale", async () => {
		const sandbox = makeSandbox();
		const calls: Call[] = [];
		(sandbox as any)._findContainerByLabel = async () => "old-container-id";
		(sandbox as any)._hasStaleAgentDirMounts = async () => true;
		(sandbox as any)._isContainerImageStale = async () => { throw new Error("must not inspect image after stale mount"); };
		(sandbox as any)._isContainerRunning = async () => { throw new Error("must not reconnect stale container"); };
		(sandbox as any)._removeContainer = async (containerId: string) => { calls.push(["remove", containerId]); };
		(sandbox as any)._createContainer = async () => { calls.push("create"); (sandbox as any).containerId = "new-container-id"; };
		(sandbox as any)._runInitSequence = async () => { calls.push("init"); };

		await (sandbox as any)._initContainer();

		assert.deepEqual(calls, [["remove", "old-container-id"], "create", "init"]);
		assert.equal((sandbox as any).containerId, "new-container-id");
	});
});

describe("SandboxManager atomic model refresh", () => {
	it("refreshes every ready container once and leaves non-ready containers for normal recovery", async () => {
		const manager = new SandboxManager();
		const calls: string[] = [];
		(manager as any).sandboxes = new Map([
			["ready-a", { getStatus: () => ({ status: "ready" }), refreshAgentModelMount: async () => { calls.push("ready-a"); } }],
			["error", { getStatus: () => ({ status: "error" }), refreshAgentModelMount: async () => { calls.push("error"); } }],
			["ready-b", { getStatus: () => ({ status: "ready" }), refreshAgentModelMount: async () => { calls.push("ready-b"); } }],
		]);

		await manager.refreshAgentModelMounts();

		assert.deepEqual(calls.sort(), ["ready-a", "ready-b"]);
	});
});

describe("ProjectSandbox state mount staleness", () => {
	it("accepts the current required state mounts including read-only generated extension dirs", () => {
		const stateDir = path.resolve("/project/.bobbit/state");

		const result = getStateDirMountStaleness(requiredStateMounts(stateDir), { stateDir });

		assert.equal(result.stale, false, result.reason);
	});

	it("marks pre-upgrade containers stale when the tool-result-error bridge mount is missing", () => {
		const stateDir = path.resolve("/project/.bobbit/state");
		const mounts = requiredStateMounts(stateDir).filter((m) => m.Destination !== "/bobbit-state/tool-result-error-bridge");

		const result = getStateDirMountStaleness(mounts, { stateDir });

		assert.equal(result.stale, true);
		assert.match(result.reason ?? "", /tool-result-error-bridge/);
	});

	it("marks generated extension state mounts stale unless they are read-only", () => {
		const stateDir = path.resolve("/project/.bobbit/state");
		const mounts = requiredStateMounts(stateDir).map((m) => m.Destination === "/bobbit-state/tool-result-error-bridge"
			? mount(path.join(stateDir, "tool-result-error-bridge"), "/bobbit-state/tool-result-error-bridge")
			: m);

		const result = getStateDirMountStaleness(mounts, { stateDir });

		assert.equal(result.stale, true);
		assert.match(result.reason ?? "", /tool-result-error-bridge/);
	});

	it("marks pre-upgrade containers stale when the AIGW DNS guard mount is missing", () => {
		const stateDir = path.resolve("/project/.bobbit/state");
		const mounts = requiredStateMounts(stateDir).filter((m) => m.Destination !== "/bobbit-state/aigw-dns-guard");
		const result = getStateDirMountStaleness(mounts, { stateDir });
		assert.equal(result.stale, true);
		assert.match(result.reason ?? "", /aigw-dns-guard/);
	});

	it("recreates an existing project container before reconnecting when required state mounts are stale", async () => {
		const sandbox = makeSandbox();
		const calls: Call[] = [];
		(sandbox as any)._findContainerByLabel = async () => "old-container-id";
		(sandbox as any)._hasStaleAgentDirMounts = async () => false;
		(sandbox as any)._hasStaleStateDirMounts = async () => true;
		(sandbox as any)._isContainerImageStale = async () => { throw new Error("must not inspect image after stale state mounts"); };
		(sandbox as any)._isContainerRunning = async () => { throw new Error("must not reconnect stale container"); };
		(sandbox as any)._removeContainer = async (containerId: string) => { calls.push(["remove", containerId]); };
		(sandbox as any)._createContainer = async () => { calls.push("create"); (sandbox as any).containerId = "new-container-id"; };
		(sandbox as any)._runInitSequence = async () => { calls.push("init"); };

		await (sandbox as any)._initContainer();

		assert.deepEqual(calls, [["remove", "old-container-id"], "create", "init"]);
		assert.equal((sandbox as any).containerId, "new-container-id");
	});
});
