// AUTO-GENERATED by scripts/testing-v2/codemod.mjs — do not edit the legacy source.
// Source: tests/prompt-draft-attachments-store.test.ts
// Bucket: v2-core | Method: codemod | Classification: clean

/**
 * Unit tests for PromptDraftAttachmentsStore — client-side IndexedDB persistence
 * for unsent composer attachments (src/ui/storage/stores/prompt-draft-attachments-store.ts).
 *
 * These pin the storage *contract* — round-trip/isolation, the per-session file
 * cap, the per-session BYTE cap (which keeps the documented total cap honest even
 * for the never-evicted active session), and LRU + count/byte eviction — against
 * a tiny in-memory fake StorageBackend, so the logic is exercised without a real
 * IndexedDB. There is deliberately NO persistent gen guard here: attachment
 * drafts carry no generation field (stale-load resurrection is handled by the
 * in-flight guard in AgentInterface — see agent-interface-attachment-draft-race.test.ts).
 *
 * See docs/design/composer-draft-persistence.md §3.
 */
import { test } from "vitest";
import assert from "node:assert/strict";

import { PromptDraftAttachmentsStore } from "../../src/ui/storage/stores/prompt-draft-attachments-store.ts";
import type { Attachment } from "../../src/ui/utils/attachment-utils.ts";
import type { StorageBackend } from "../../src/ui/storage/types.ts";


/** Minimal in-memory StorageBackend — only the methods the store uses. */
function makeFakeBackend(): StorageBackend {
	const data = new Map<string, Map<string, unknown>>();
	const bucket = (name: string) => {
		let b = data.get(name);
		if (!b) data.set(name, (b = new Map()));
		return b;
	};
	return {
		async get<T>(storeName: string, key: string): Promise<T | null> {
			return (bucket(storeName).get(key) as T) ?? null;
		},
		async set<T>(storeName: string, key: string, value: T): Promise<void> {
			bucket(storeName).set(key, value);
		},
		async delete(storeName: string, key: string): Promise<void> {
			bucket(storeName).delete(key);
		},
		async keys(storeName: string): Promise<string[]> {
			return [...bucket(storeName).keys()];
		},
		async getAllFromIndex<T>(storeName: string, indexName: string, direction: "asc" | "desc" = "asc"): Promise<T[]> {
			const vals = [...bucket(storeName).values()] as Array<Record<string, unknown>>;
			vals.sort((a, b) => (a[indexName] as number) - (b[indexName] as number));
			if (direction === "desc") vals.reverse();
			return vals as T[];
		},
		async clear(storeName: string): Promise<void> {
			bucket(storeName).clear();
		},
		async has(storeName: string, key: string): Promise<boolean> {
			return bucket(storeName).has(key);
		},
		async transaction() {
			throw new Error("not used");
		},
		async getQuotaInfo() {
			return { usage: 0, quota: 0, percent: 0 };
		},
		async requestPersistence() {
			return false;
		},
	};
}

function makeStore(): { store: PromptDraftAttachmentsStore; backend: StorageBackend } {
	const backend = makeFakeBackend();
	const store = new PromptDraftAttachmentsStore();
	store.setBackend(backend);
	return { store, backend };
}

/** An attachment whose serialized footprint is ~`bytes` (driven by `content`). */
function attachment(id: string, bytes = 16): Attachment {
	return {
		id,
		type: "image",
		fileName: `${id}.png`,
		mimeType: "image/png",
		size: bytes,
		content: "a".repeat(bytes),
	};
}

test("round-trips attachments and isolates them per session", async () => {
	const { store } = makeStore();
	await store.setAttachments("s1", [attachment("a")]);
	await store.setAttachments("s2", [attachment("b")]);

	const s1 = await store.getAttachments("s1");
	const s2 = await store.getAttachments("s2");
	assert.equal(s1.length, 1);
	assert.equal(s1[0].id, "a");
	assert.equal(s2[0].id, "b");
});

test("empty / non-array input deletes the record", async () => {
	const { store } = makeStore();
	await store.setAttachments("s1", [attachment("a")]);
	await store.setAttachments("s1", []);
	assert.deepEqual(await store.getAttachments("s1"), []);
});

test("getAttachments returns [] for unknown / empty session id", async () => {
	const { store } = makeStore();
	assert.deepEqual(await store.getAttachments("nope"), []);
	assert.deepEqual(await store.getAttachments(""), []);
});

test("per-session file cap trims to MAX_FILES_PER_SESSION (10)", async () => {
	const { store } = makeStore();
	const many = Array.from({ length: 25 }, (_, i) => attachment(`f${i}`, 8));
	await store.setAttachments("s1", many);
	const got = await store.getAttachments("s1");
	assert.equal(got.length, 10);
	assert.equal(got[0].id, "f0", "keeps the first 10 in order");
	assert.equal(got[9].id, "f9");
});

test("per-session byte cap keeps the active record under MAX_BYTES_PER_SESSION (16 MB)", async () => {
	const { store } = makeStore();
	const big = 10 * 1024 * 1024; // 10 MB each → only one fits under the 16 MB cap
	await store.setAttachments("s1", [attachment("big1", big), attachment("big2", big)]);
	const got = await store.getAttachments("s1");
	// Greedy: first attachment fits (10 MB), second would push to 20 MB → dropped.
	assert.equal(got.length, 1);
	assert.equal(got[0].id, "big1");
	const bytes = got.reduce((n, a) => n + (a.content?.length ?? 0), 0);
	assert.ok(bytes <= 16 * 1024 * 1024, "persisted record must not exceed the per-session byte cap");
});

test("evicts oldest sessions past MAX_SESSIONS but never the just-written one", async () => {
	const { store } = makeStore();
	// Write 22 sessions (cap is 20) with strictly increasing updatedAt.
	for (let i = 0; i < 22; i++) {
		await store.setAttachments(`s${i}`, [attachment(`a${i}`, 8)]);
		// Nudge the clock so updatedAt is strictly ordered even on fast machines.
		await new Promise((r) => setTimeout(r, 1));
	}
	// The two oldest (s0, s1) should be evicted; the newest must survive.
	assert.deepEqual(await store.getAttachments("s0"), []);
	assert.deepEqual(await store.getAttachments("s1"), []);
	const newest = await store.getAttachments("s21");
	assert.equal(newest.length, 1, "the just-written session is never self-evicted");
});

test("evicts by total byte budget, retaining the active session", async () => {
	const { store } = makeStore();
	const big = 12 * 1024 * 1024; // 12 MB each; total cap is 64 MB
	// 6 sessions × 12 MB = 72 MB > 64 MB → at least the oldest must be evicted.
	for (let i = 0; i < 6; i++) {
		await store.setAttachments(`b${i}`, [attachment(`x${i}`, big)]);
		await new Promise((r) => setTimeout(r, 1));
	}
	// Oldest evicted; the just-written active session survives.
	assert.deepEqual(await store.getAttachments("b0"), []);
	assert.equal((await store.getAttachments("b5")).length, 1);
});
