// AUTO-GENERATED by scripts/testing-v2/codemod.mjs — do not edit the legacy source.
// Source: tests/sandbox-status.test.ts
// Bucket: v2-core | Method: codemod | Classification: clean

import { describe, it } from "vitest";
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { buildSandboxImage, checkDockerAvailability, ensureImageAgentVersion, getHostAgentVersion, getImageVersions, resolveSandboxDockerContext } from "../../src/server/agent/sandbox-status.js";

const SERVER_SOURCE = readFileSync(new URL("../../src/server/server.ts", import.meta.url), "utf8");
const DOCKERFILE_SOURCE = readFileSync(new URL("../../docker/Dockerfile", import.meta.url), "utf8");
const DOCKER_FENCE_ERROR = "SANDBOX_DOCKER_RUNNER_FENCE";

function fencedDockerRunner(calls: Array<{ file: string; args: readonly string[] }>) {
	return {
		execFile: async (file: string, args: readonly string[]) => {
			calls.push({ file, args });
			throw new Error(DOCKER_FENCE_ERROR);
		},
	};
}

describe("sandbox Docker context resolution", () => {
	it("falls back to Bobbit's bundled docker/ directory when the project cwd has none", () => {
		const projectDir = mkdtempSync(join(tmpdir(), "bobbit-sandbox-project-without-docker-"));
		try {
			const context = resolveSandboxDockerContext(projectDir);
			assert.equal(context, resolve(import.meta.dirname, "..", ".."));
		} finally {
			rmSync(projectDir, { recursive: true, force: true });
		}
	});

	it("prefers Bobbit's bundled Dockerfile over an unrelated project Dockerfile", () => {
		const projectDir = mkdtempSync(join(tmpdir(), "bobbit-sandbox-project-with-docker-"));
		try {
			mkdirSync(join(projectDir, "docker"), { recursive: true });
			writeFileSync(join(projectDir, "docker", "Dockerfile"), "FROM scratch\n", "utf-8");

			const context = resolveSandboxDockerContext(projectDir);
			assert.equal(context, resolve(import.meta.dirname, "..", ".."));
		} finally {
			rmSync(projectDir, { recursive: true, force: true });
		}
	});

	it("keeps Docker failures inside an injected command-runner seam", async () => {
		const probeCalls: Array<{ file: string; args: readonly string[] }> = [];
		const status = await checkDockerAvailability("fenced-image", undefined, fencedDockerRunner(probeCalls));
		assert.equal(status.available, false);
		assert.match(status.error ?? "", new RegExp(DOCKER_FENCE_ERROR));
		assert.deepEqual(probeCalls, [{ file: "docker", args: ["info", "--format", "{{.ServerVersion}}"] }]);

		const buildCalls: Array<{ file: string; args: readonly string[] }> = [];
		const result = await buildSandboxImage("fenced-image", resolve(import.meta.dirname, "..", ".."), fencedDockerRunner(buildCalls));
		assert.equal(result.success, false);
		assert.match(result.error ?? "", new RegExp(DOCKER_FENCE_ERROR));
		assert.equal(buildCalls.length, 1);
		assert.equal(buildCalls[0].file, "docker");
		assert.equal(buildCalls[0].args[0], "build");
	});

	it("uses its injected runner for image version inspection and rebuilding", async () => {
		const hostVersion = getHostAgentVersion();
		assert.ok(hostVersion, "the local pi-coding-agent package supplies a version");
		const calls: Array<{ file: string; args: readonly string[] }> = [];
		const recordingRunner = {
			execFile: async (file: string, args: readonly string[]) => {
				calls.push({ file, args });
				if (args[0] === "inspect") return { stdout: Buffer.from("<no value>\t<no value>"), stderr: Buffer.alloc(0) };
				if (args[0] === "build") return { stdout: Buffer.alloc(0), stderr: Buffer.alloc(0) };
				throw new Error(`unexpected Docker command: ${args.join(" ")}`);
			},
		};

		assert.equal(await ensureImageAgentVersion("fenced-image", resolve(import.meta.dirname, "..", ".."), recordingRunner), true);
		assert.deepEqual(calls.map(({ file, args }) => ({ file, command: args[0] })), [
			{ file: "docker", command: "inspect" },
			{ file: "docker", command: "build" },
		]);
		assert.deepEqual(calls[0].args, ["inspect", "--format", "{{index .Config.Labels \"bobbit.pi-agent-version\"}}\t{{index .Config.Labels \"bobbit.ast-grep-version\"}}", "fenced-image"]);
		assert.ok(calls[1].args.includes(`PI_AGENT_VERSION=${hostVersion}`));
		assert.ok(calls[1].args.includes("AST_GREP_VERSION=0.39.5"));
	});

	it("treats a stale ast-grep label as a stale image even when pi matches", async () => {
		const hostVersion = getHostAgentVersion();
		assert.ok(hostVersion);
		const calls: Array<{ file: string; args: readonly string[] }> = [];
		const recordingRunner = {
			execFile: async (file: string, args: readonly string[]) => {
				calls.push({ file, args });
				if (args[0] === "inspect") return { stdout: Buffer.from(`${hostVersion}\t0.0.0`), stderr: Buffer.alloc(0) };
				return { stdout: Buffer.alloc(0), stderr: Buffer.alloc(0) };
			},
		};

		assert.deepEqual(await getImageVersions("fenced-image", recordingRunner), { agent: hostVersion, astGrep: "0.0.0" });
		assert.equal(await ensureImageAgentVersion("fenced-image", resolve(import.meta.dirname, "..", ".."), recordingRunner), true);
		assert.equal(calls.filter(({ args }) => args[0] === "build").length, 1);
	});

	it("pins and labels the same checksum-verified sg image binary", () => {
		assert.match(DOCKERFILE_SOURCE, /ARG AST_GREP_VERSION=0\.39\.5/);
		assert.match(DOCKERFILE_SOURCE, /bobbit\.ast-grep-version=\$\{AST_GREP_VERSION\}/);
		assert.match(DOCKERFILE_SOURCE, /unzip -p \/tmp\/ast-grep\.zip sg > \/usr\/local\/bin\/sg/);
		assert.match(DOCKERFILE_SOURCE, /sha256sum -c -/);
	});

	it("threads the gateway runner to every sandbox Docker helper call site", () => {
		assert.match(SERVER_SOURCE, /checkDockerAvailability\(imageName, dockerContextRoot \?\? undefined, gatewayDeps\.commandRunner\)/);
		assert.match(SERVER_SOURCE, /buildSandboxImage\(imageName, dockerContextRoot, gatewayDeps\.commandRunner\)/);
		assert.match(SERVER_SOURCE, /ensureImageAgentVersion\(imageName, dockerContextRoot \?\? undefined, gatewayDeps\.commandRunner\)/);
		assert.match(SERVER_SOURCE, /checkDockerAvailability\(configured \? imageName : undefined, dockerContextRoot \?\? undefined, commandRunner\)/);
		assert.match(SERVER_SOURCE, /buildSandboxImage\(imageName, dockerContextRoot, commandRunner!\)/);
		assert.match(SERVER_SOURCE, /checkDockerAvailability\(undefined, undefined, commandRunner!\)/);
	});
});
