// AUTO-GENERATED by scripts/testing-v2/codemod.mjs — do not edit the legacy source.
// Source: tests/session-store-stale-load-guard.test.ts
// Bucket: v2-core | Method: codemod | Classification: needs-withEnv
// Review: migrated to injected memfs; no process.env mutation remains.

/**
 * Stale-snapshot guard regression test.
 *
 * If `sessions.json` on disk has a HIGHER epoch than what we last loaded
 * (e.g. cloud sync / antivirus restored a newer file under a running
 * gateway, or the primary was repaired manually), saveNow() must refuse to
 * write — otherwise we'd clobber newer state with stale in-memory data.
 */
import { describe, it, beforeEach } from "vitest";
import assert from "node:assert/strict";
import path from "node:path";
import { SessionStore, type PersistedSession } from "../../src/server/agent/session-store.ts";
import { createMemFs, type MemFs } from "../harness/mem-fs.ts";

type SessionStoreMemFs = MemFs & {
	openSync(file: string, flags: string): number;
	fsyncSync(fd: number): void;
	closeSync(fd: number): void;
};

function createSessionStoreMemFs(): SessionStoreMemFs {
	const memfs = createMemFs() as SessionStoreMemFs;
	let nextFd = 3;
	const fds = new Map<number, string>();
	const writeFileSync = memfs.writeFileSync.bind(memfs);
	memfs.openSync = (file: string) => {
		const fd = nextFd++;
		fds.set(fd, file);
		return fd;
	};
	(memfs as any).writeFileSync = (target: string | number, data: string | NodeJS.ArrayBufferView, encoding?: BufferEncoding) => {
		if (typeof target === "number") {
			const file = fds.get(target);
			if (!file) throw Object.assign(new Error(`EBADF: bad file descriptor, write '${target}'`), { code: "EBADF" });
			return writeFileSync(file, data, encoding as any);
		}
		return writeFileSync(target, data, encoding as any);
	};
	memfs.fsyncSync = () => {};
	memfs.closeSync = (fd: number) => { fds.delete(fd); };
	return memfs;
}

const stateDir = path.join("/state", "session-store-stale");
const STORE_FILE = path.join(stateDir, "sessions.json");
const ARCHIVED_FILE = path.join(stateDir, "sessions.archived.json");
let memfs: SessionStoreMemFs;

function makeSession(id: string): PersistedSession {
	return {
		id,
		title: `Session ${id}`,
		cwd: "/tmp/test",
		agentSessionFile: `/tmp/test/${id}.jsonl`,
		createdAt: Date.now(),
		lastActivity: Date.now(),
	};
}

describe("SessionStore stale-snapshot guard", () => {
	beforeEach(() => {
		memfs = createSessionStoreMemFs();
	});

	it("refuses to save when on-disk epoch is newer than loaded epoch", async () => {
		// Start fresh, no sessions.json on disk.
		const store = new SessionStore(stateDir, memfs);
		assert.equal(store.getLoadedEpoch(), 0);

		// External writer puts a v2 file with epoch 50 after we constructed.
		const externalPayload = {
			version: 3,
			epoch: 50,
			sessions: [{
				id: "external-1",
				title: "External",
				cwd: "/external",
				agentSessionFile: "/external/a.jsonl",
				createdAt: Date.now(),
				lastActivity: Date.now(),
			}],
		};
		memfs.writeFileSync(STORE_FILE, JSON.stringify(externalPayload, null, 2), "utf-8");

		// Capture console.error
		const errors: string[] = [];
		const origErr = console.error;
		console.error = (...args: unknown[]) => { errors.push(args.map(String).join(" ")); };

		try {
			// Trigger and await the async durability barrier for an in-memory put.
			store.put(makeSession("s-stale"));
			await assert.rejects(store.flushAsync(), /stale-snapshot|newer than loaded epoch/i);

			// On-disk file must be unchanged (still epoch 50, external-1).
			const onDisk = JSON.parse(memfs.readFileSync(STORE_FILE, "utf-8"));
			assert.equal(onDisk.epoch, 50, "on-disk epoch must remain 50 — write refused");
			assert.equal(onDisk.sessions.length, 1);
			assert.equal(onDisk.sessions[0].id, "external-1");
		} finally {
			console.error = origErr;
		}

		assert.ok(errors.some(e => /REFUSING to save/.test(e)), `expected REFUSING-to-save log line, got: ${errors.join("\n")}`);
		assert.equal(store.isStaleGuardTripped(), true);
		assert.equal(store.getWrittenEpoch(), 0, "no write succeeded");

		// Subsequent put — still no write.
		const errsBefore = errors.length;
		store.put(makeSession("s-stale-2"));
		await assert.rejects(store.flushAsync(), /stale-snapshot|newer than loaded epoch/i);
		const onDisk2 = JSON.parse(memfs.readFileSync(STORE_FILE, "utf-8"));
		assert.equal(onDisk2.epoch, 50, "second put still must not overwrite");
		assert.equal(errors.length, errsBefore, "guard latched — no further error spam");
	});

	it("refuses a stale first write from a second store instance", async () => {
		const staleStore = new SessionStore(stateDir, memfs);
		const winningStore = new SessionStore(stateDir, memfs);

		winningStore.put(makeSession("winner"));
		await winningStore.flushAsync();
		const winningRaw = memfs.readFileSync(STORE_FILE, "utf-8");

		const origErr = console.error;
		console.error = () => {};
		try {
			staleStore.put(makeSession("stale-writer"));
			await assert.rejects(staleStore.flushAsync(), /stale-snapshot|newer than loaded epoch/i);
		} finally {
			console.error = origErr;
		}

		assert.equal(staleStore.isStaleGuardTripped(), true);
		assert.equal(staleStore.getWrittenEpoch(), 0);
		assert.equal(memfs.readFileSync(STORE_FILE, "utf-8"), winningRaw, "stale writer must not alter the winner's bytes");
	});

	it("does NOT trip the guard when on-disk epoch matches what we wrote earlier", async () => {
		// Write a few sessions, flush, then put more — no external rewrite.
		const store = new SessionStore(stateDir, memfs);
		store.put(makeSession("s1"));
		store.put(makeSession("s2"));
		store.put(makeSession("s3"));
		store.put(makeSession("s4"));
		store.put(makeSession("s5"));
		await store.flushAsync();

		const after5 = JSON.parse(memfs.readFileSync(STORE_FILE, "utf-8"));
		assert.equal(after5.epoch, 1, "a burst is coalesced into one atomic publish");
		assert.equal(store.isStaleGuardTripped(), false);
		assert.equal(store.getWrittenEpoch(), 1);

		// Another durability barrier advances the epoch without tripping the guard.
		store.put(makeSession("s6"));
		await store.flushAsync();
		const after6 = JSON.parse(memfs.readFileSync(STORE_FILE, "utf-8"));
		assert.equal(after6.epoch, 2);
		assert.equal(store.isStaleGuardTripped(), false);
	});

	it("isolates stale guards and epoch validation between live and archived tiers", async () => {
		const seed = new SessionStore(stateDir, memfs);
		seed.put(makeSession("live"));
		seed.put({ ...makeSession("archived"), archived: true, archivedAt: 1 });
		await seed.flushAsync();

		const liveWriter = new SessionStore(stateDir, memfs);
		const archiveWriter = new SessionStore(stateDir, memfs);
		const archiveExternal = { version: 3, epoch: 99, sessions: [{ ...makeSession("archived"), archived: true, archivedAt: 1 }] };
		memfs.writeFileSync(ARCHIVED_FILE, JSON.stringify(archiveExternal), "utf-8");

		liveWriter.update("live", { title: "live must still publish" });
		await liveWriter.flushAsync();
		assert.equal(liveWriter.isStaleGuardTripped(), false, "an archive rewrite must not trip the live latch");
		assert.equal(JSON.parse(memfs.readFileSync(STORE_FILE, "utf-8")).sessions[0].title, "live must still publish");

		archiveWriter.update("archived", { title: "stale archive writer" });
		await assert.rejects(archiveWriter.flushAsync(), /stale-snapshot|newer than loaded epoch/i);
		assert.deepEqual(JSON.parse(memfs.readFileSync(ARCHIVED_FILE, "utf-8")), archiveExternal);

		const archiveOnlyWriter = new SessionStore(stateDir, memfs);
		const liveExternal = { version: 3, epoch: 123, sessions: [makeSession("live")] };
		memfs.writeFileSync(STORE_FILE, JSON.stringify(liveExternal), "utf-8");
		archiveOnlyWriter.update("archived", { title: "archive must still publish" });
		await archiveOnlyWriter.flushAsync();
		assert.equal(JSON.parse(memfs.readFileSync(ARCHIVED_FILE, "utf-8")).sessions[0].title, "archive must still publish");
		assert.deepEqual(JSON.parse(memfs.readFileSync(STORE_FILE, "utf-8")), liveExternal);
	});

	it("rejects a stale live-to-archive writer before it can publish an intent or erase winner ownership metadata", async () => {
		const initial = { ...makeSession("shared"), title: "unprivileged original", projectId: "old-project", teamGoalId: "old-goal", role: "coder", sandboxed: false };
		const seed = new SessionStore(stateDir, memfs);
		seed.put(initial);
		await seed.flushAsync();

		const winner = new SessionStore(stateDir, memfs);
		const stale = new SessionStore(stateDir, memfs);
		const winnerFields = { title: "secured live winner", projectId: "secure-project", teamGoalId: "secure-goal", role: "team-lead", sandboxed: true, assistantType: "goal" };
		winner.update("shared", winnerFields);
		await winner.flushAsync();
		const winningLiveBytes = memfs.readFileSync(STORE_FILE, "utf-8");
		const winningLive = JSON.parse(winningLiveBytes);
		assert.equal(winningLive.epoch, 2);
		assert.equal(memfs.existsSync(ARCHIVED_FILE), false);

		const originalError = console.error;
		console.error = () => {};
		try {
			assert.equal(stale.archive("shared"), true);
			await assert.rejects(stale.flushAsync(), /stale-snapshot|newer than loaded epoch/i);
		} finally {
			console.error = originalError;
		}

		assert.equal(stale.isTierStaleGuardTripped("live"), true);
		assert.equal(stale.isTierStaleGuardTripped("archived"), false);
		assert.equal(stale.getTierWrittenEpoch("live"), 0);
		assert.equal(stale.getTierWrittenEpoch("archived"), 0);
		assert.equal(memfs.readFileSync(STORE_FILE, "utf-8"), winningLiveBytes, "rejected stale store must not alter winner live bytes");
		assert.equal(memfs.existsSync(ARCHIVED_FILE), false, "rejected pair must not create an archive tier");
		assert.equal(memfs.existsSync(`${STORE_FILE}.split-transition`), false, "rejected pair must not publish stale transition authority");
		assert.deepEqual(winningLive.sessions, [{ ...initial, ...winnerFields }], "winner security and ownership metadata survives");
	});

	it("rejects a stale archived-to-live writer before it can publish an intent or resurrect a live row", async () => {
		const initial = { ...makeSession("shared"), title: "unprivileged archive", archived: true, archivedAt: 10, projectId: "old-project", teamGoalId: "old-goal", role: "coder", sandboxed: false };
		const seed = new SessionStore(stateDir, memfs);
		seed.put(initial);
		await seed.flushAsync();

		const winner = new SessionStore(stateDir, memfs);
		const stale = new SessionStore(stateDir, memfs);
		const winnerFields = { title: "secured archived winner", projectId: "secure-project", teamGoalId: "secure-goal", role: "reviewer", sandboxed: true, assistantType: "role" };
		winner.update("shared", winnerFields);
		await winner.flushAsync();
		const winningArchiveBytes = memfs.readFileSync(ARCHIVED_FILE, "utf-8");
		const winningArchive = JSON.parse(winningArchiveBytes);
		assert.equal(winningArchive.epoch, 2);
		assert.equal(memfs.existsSync(STORE_FILE), false);

		const originalError = console.error;
		console.error = () => {};
		try {
			stale.update("shared", { archived: false });
			await assert.rejects(stale.flushAsync(), /stale-snapshot|newer than loaded epoch/i);
		} finally {
			console.error = originalError;
		}

		assert.equal(stale.isTierStaleGuardTripped("archived"), true);
		assert.equal(stale.isTierStaleGuardTripped("live"), false);
		assert.equal(stale.getTierWrittenEpoch("live"), 0);
		assert.equal(stale.getTierWrittenEpoch("archived"), 0);
		assert.equal(memfs.readFileSync(ARCHIVED_FILE, "utf-8"), winningArchiveBytes, "rejected stale store must not alter winner archive bytes");
		assert.equal(memfs.existsSync(STORE_FILE), false, "rejected pair must not resurrect a live row");
		assert.equal(memfs.existsSync(`${STORE_FILE}.split-transition`), false, "rejected pair must not publish stale transition authority");
		assert.deepEqual(winningArchive.sessions, [{ ...initial, ...winnerFields }], "winner security and ownership metadata survives");
	});
});
