// AUTO-GENERATED by scripts/testing-v2/codemod.mjs — do not edit the legacy source.
// Source: tests/shared-worktree-guard-repro.test.ts
// Bucket: v2-core | Method: codemod | Classification: needs-withEnv
// Review: mutates process.env — wrap in withEnv(patch, fn) to restore in finally

import { guardProcessEnv } from "./helpers/env-guard.js";
guardProcessEnv();

/**
 * Reproducing tests for shared worktree cleanup guards.
 *
 * Worktrees are plain filesystem markers. The fake Git runner removes a marker
 * only when production actually issues `git worktree remove`, so these tests pin
 * both halves of the contract: shared paths survive and unshared paths remain
 * cleanable without launching Git.
 */
import { afterAll, afterEach, beforeEach, describe, it, vi } from "vitest";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import type { CommandRunner } from "../../src/server/gateway-deps.ts";

const fakeGitState = {
	commands: [] as Array<{ args: string[]; cwd?: string }>,
};

const fakeGitRunner: CommandRunner = {
	async execFile(command, args, options) {
		assert.equal(command, "git");
		fakeGitState.commands.push({
			args: [...args],
			cwd: options?.cwd === undefined ? undefined : String(options.cwd),
		});
		if (args[0] === "worktree" && args[1] === "remove") {
			fs.rmSync(String(args[2]), { recursive: true, force: true });
		}
		return { stdout: "", stderr: "" };
	},
};

// SessionManager is the single import root for this production module graph.
// BOBBIT_DIR must be isolated before any server module loads because several
// transitive singletons derive state from it.
const importStateRoot = fs.mkdtempSync(path.join(os.tmpdir(), "shared-wt-guard-import-state-"));
process.env.BOBBIT_DIR = importStateRoot;
const { SessionManager } = await import("../../src/server/agent/session-manager.ts");
const [
	{ SessionStore },
	{ GoalManager },
	{ GoalStore },
	{ handleSetupFailure },
	{ initPromptDirs },
] = await Promise.all([
	import("../../src/server/agent/session-store.ts"),
	import("../../src/server/agent/goal-manager.ts"),
	import("../../src/server/agent/goal-store.ts"),
	import("../../src/server/agent/session-setup.ts"),
	import("../../src/server/agent/system-prompt.ts"),
]);
initPromptDirs(importStateRoot);

const managers: any[] = [];
let prevBobbitDir: string | undefined;
let stateRoot = "";

function makeRepo(root: string): string {
	const repo = path.join(root, "repo");
	fs.mkdirSync(path.join(repo, ".git"), { recursive: true });
	return repo;
}

function makeWorktree(worktreePath: string): void {
	fs.mkdirSync(worktreePath, { recursive: true });
	fs.writeFileSync(path.join(worktreePath, ".git"), "gitdir: test-marker\n", "utf8");
}

function equivalentPath(worktreePath: string): string {
	const normalized = worktreePath.replace(/\\/g, "/");
	return process.platform === "win32" ? normalized.toUpperCase() : normalized;
}

function makeSession(id: string, extra: Record<string, any>): any {
	return {
		id,
		title: id,
		cwd: stateRoot,
		agentSessionFile: "",
		createdAt: Date.now(),
		lastActivity: Date.now(),
		...extra,
	};
}

function makeManager(store: any, commandRunner: any = fakeGitRunner): any {
	const manager: any = new SessionManager({ commandRunner, remoteGitPolicy: { skipRemotePush: true } });
	manager._testStore = store;
	managers.push(manager);
	return manager;
}

function fakeGitWorktreeListRunner(porcelain: string): any {
	return {
		execFile: async (command: string, args: readonly string[]) => {
			assert.equal(command, "git");
			assert.deepEqual(args, ["worktree", "list", "--porcelain"]);
			return { stdout: porcelain, stderr: "" };
		},
	};
}

function cleanupManager(manager: any): void {
	if (manager?._statusHeartbeatTimer) {
		clearInterval(manager._statusHeartbeatTimer);
		manager._statusHeartbeatTimer = null;
	}
	manager?.sessions?.clear?.();
}

describe("shared worktree guard reproductions", () => {
	beforeEach(() => {
		fakeGitState.commands.length = 0;
		stateRoot = fs.mkdtempSync(path.join(os.tmpdir(), "shared-wt-guard-state-"));
		prevBobbitDir = process.env.BOBBIT_DIR;
		process.env.BOBBIT_DIR = stateRoot;
		initPromptDirs(stateRoot);
	});

	afterEach(() => {
		while (managers.length > 0) cleanupManager(managers.pop());
		if (prevBobbitDir === undefined) delete process.env.BOBBIT_DIR;
		else process.env.BOBBIT_DIR = prevBobbitDir;
		fs.rmSync(stateRoot, { recursive: true, force: true });
	});

	afterAll(() => {
		fs.rmSync(importStateRoot, { recursive: true, force: true });
	});

	it("purging an archived session must not remove a worktree referenced by a live session cwd", async () => {
		const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "shared-wt-guard-purge-single-"));
		try {
			const repo = makeRepo(tmp);
			const sharedWorktree = path.join(tmp, "repo-wt", "session-shared");
			const branch = "session/shared-single";
			makeWorktree(sharedWorktree);

			const store = new SessionStore(stateRoot);
			store.put(makeSession("archived-a", {
				archived: true,
				archivedAt: Date.now(),
				repoPath: repo,
				branch,
				worktreePath: sharedWorktree,
				cwd: sharedWorktree,
			}));
			store.put(makeSession("live-b", {
				cwd: equivalentPath(sharedWorktree),
				worktreePath: undefined,
				branch: "session/live-different-branch",
			}));

			const manager = makeManager(store);
			const purged = await manager.purgeArchivedSession("archived-a");

			assert.equal(purged, true, "archived session should be purged by the test setup");
			assert.ok(
				fs.existsSync(sharedWorktree),
				"SHARED_WORKTREE_GUARD_PURGE_SINGLE_REGRESSION: archived session purge removed a worktree path still referenced by a non-archived session cwd",
			);
			assert.equal(fakeGitState.commands.some(call => call.args[0] === "worktree"), false);
		} finally {
			fs.rmSync(tmp, { recursive: true, force: true });
		}
	});

	it("purging an archived multi-repo session must keep shared repoWorktrees and may clean unshared ones", async () => {
		const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "shared-wt-guard-purge-multi-"));
		try {
			const root = path.join(tmp, "project");
			const api = path.join(root, "api");
			const web = path.join(root, "web");
			fs.mkdirSync(path.join(api, ".git"), { recursive: true });
			fs.mkdirSync(path.join(web, ".git"), { recursive: true });

			const branch = "session/shared-multi";
			const apiWorktree = path.join(tmp, "project-wt", "session-shared", "api");
			const webWorktree = path.join(tmp, "project-wt", "session-shared", "web");
			makeWorktree(apiWorktree);
			makeWorktree(webWorktree);

			const store = new SessionStore(stateRoot);
			store.put(makeSession("archived-multi", {
				archived: true,
				archivedAt: Date.now(),
				repoPath: root,
				branch,
				worktreePath: path.join(tmp, "project-wt", "session-shared"),
				repoWorktrees: { api: apiWorktree, web: webWorktree },
			}));
			store.put(makeSession("live-api-owner", {
				cwd: apiWorktree,
				branch: "session/live-api-owner",
				repoWorktrees: { api: equivalentPath(apiWorktree) },
			}));

			const manager = makeManager(store);
			const purged = await manager.purgeArchivedSession("archived-multi");

			assert.equal(purged, true, "archived multi-repo session should be purged by the test setup");
			assert.ok(
				fs.existsSync(apiWorktree),
				"SHARED_WORKTREE_GUARD_PURGE_MULTI_REGRESSION: archived multi-repo purge removed a repoWorktrees path still referenced by a non-archived session",
			);
			assert.equal(fs.existsSync(webWorktree), false, "unshared multi-repo worktree should remain cleanable");
			assert.deepEqual(
				fakeGitState.commands.filter(call => call.args[0] === "worktree").map(call => call.args[2]),
				[webWorktree],
			);
		} finally {
			fs.rmSync(tmp, { recursive: true, force: true });
		}
	});

	it("manual orphan listing must not report a worktree path referenced by live repoWorktrees", async () => {
		const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "shared-wt-guard-list-"));
		try {
			const repo = path.join(tmp, "repo");
			const sharedWorktree = path.join(tmp, "repo-wt", "session-shared-api");
			fs.mkdirSync(sharedWorktree, { recursive: true });

			const store = new SessionStore(stateRoot);
			store.put(makeSession("live-repo-owner", {
				cwd: path.join(tmp, "elsewhere"),
				branch: "session/live-different-branch",
				repoWorktrees: { api: equivalentPath(sharedWorktree) },
			}));

			const porcelain = `worktree ${repo}\nbranch refs/heads/master\n\nworktree ${sharedWorktree}\nbranch refs/heads/session/stale-branch\n`;
			const manager = makeManager(store, fakeGitWorktreeListRunner(porcelain));
			const orphans = await manager.listOrphanedSessionWorktrees(repo);

			assert.equal(
				orphans.some((entry: { path: string }) => path.resolve(entry.path) === path.resolve(sharedWorktree)),
				false,
				`SHARED_WORKTREE_GUARD_ORPHAN_LIST_REGRESSION: manual orphan listing reported a path referenced by live repoWorktrees: ${JSON.stringify(orphans)}`,
			);
		} finally {
			fs.rmSync(tmp, { recursive: true, force: true });
		}
	});

	it("goal archive must not remove a multi-repo worktree referenced by a live session resolver", async () => {
		const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "shared-wt-guard-goal-archive-"));
		try {
			const root = path.join(tmp, "project");
			const api = path.join(root, "api");
			const web = path.join(root, "web");
			fs.mkdirSync(path.join(api, ".git"), { recursive: true });
			fs.mkdirSync(path.join(web, ".git"), { recursive: true });

			const branch = "goal/archive-shared";
			const apiWorktree = path.join(tmp, "project-wt", "goal-archive", "api");
			const webWorktree = path.join(tmp, "project-wt", "goal-archive", "web");
			makeWorktree(apiWorktree);
			makeWorktree(webWorktree);

			const goalState = path.join(tmp, "goal-state");
			const goalStore = new GoalStore(goalState, undefined, { persistence: "json" });
			const goalManager = new GoalManager(goalStore, undefined, undefined, {
				commandRunner: fakeGitRunner,
				remotePolicy: { skipRemotePush: true },
			});
			goalManager.setLiveSessionResolver(() => [makeSession("live-api-owner", {
				cwd: equivalentPath(apiWorktree),
				branch: "session/live-api-owner",
			})]);
			goalStore.put({
				id: "goal-archive",
				title: "goal archive",
				cwd: path.join(tmp, "project-wt", "goal-archive"),
				state: "complete",
				team: false,
				spec: "",
				createdAt: Date.now(),
				updatedAt: Date.now(),
				repoPath: root,
				branch,
				worktreePath: path.join(tmp, "project-wt", "goal-archive"),
				repoWorktrees: { api: apiWorktree, web: webWorktree },
			});

			const archived = await goalManager.archiveGoal("goal-archive");
			await Promise.resolve();
			assert.equal(archived, true, "goal should be archived by the test setup");
			assert.ok(
				fs.existsSync(apiWorktree),
				"SHARED_WORKTREE_GUARD_GOAL_ARCHIVE_REGRESSION: goal archive removed a repoWorktrees path still referenced by a live session resolver",
			);
			assert.equal(fs.existsSync(webWorktree), false, "unshared goal repoWorktree should remain cleanable");
			assert.deepEqual(
				fakeGitState.commands.filter(call => call.args[0] === "worktree").map(call => call.args[2]),
				[webWorktree],
			);
		} finally {
			fs.rmSync(tmp, { recursive: true, force: true });
		}
	});

	it("recovery ownership promotes a missing team marker before archive replay preserves every multi-repo artifact", async () => {
		for (const initialTeam of [false, undefined] as const) {
			fakeGitState.commands.length = 0;
			const tmp = fs.mkdtempSync(path.join(os.tmpdir(), `recovered-team-marker-${String(initialTeam)}-`));
			try {
				const root = path.join(tmp, "project");
				const api = path.join(root, "api");
				const web = path.join(root, "web");
				fs.mkdirSync(path.join(api, ".git"), { recursive: true });
				fs.mkdirSync(path.join(web, ".git"), { recursive: true });
				const apiWorktree = path.join(tmp, "project-wt", "recovered-team", "api");
				const webWorktree = path.join(tmp, "project-wt", "recovered-team", "web");
				makeWorktree(apiWorktree);
				makeWorktree(webWorktree);

				const goalState = path.join(tmp, "goal-state");
				const goalStore = new GoalStore(goalState, undefined, { persistence: "json" });
				const goalManager = new GoalManager(goalStore, undefined, undefined, {
					commandRunner: fakeGitRunner,
					remotePolicy: { skipRemotePush: false },
				});
				let reconciliation = 0;
				goalManager.setGoalArchiveReconciler(async (goalId) => {
					reconciliation++;
					if (goalStore.get(goalId)?.team !== true) {
						assert.equal(await goalStore.updateStrict(goalId, { team: true }), true, "strict marker publication must acknowledge before cleanup");
						const fresh = new GoalStore(goalState, undefined, { persistence: "json" });
						assert.equal(fresh.get(goalId)?.team, true, "strict marker is durable before session archive acknowledgement");
					}
					return reconciliation === 1
						? { archivedSessionIds: ["exact-teamGoalId-owner"], teamRemoved: true }
						: { archivedSessionIds: [], suppressedSessionIds: [], teamRemoved: false, teamEntryRetained: false };
				});
				goalStore.put({
					id: `recovered-team-${String(initialTeam)}`,
					title: "recovered team",
					cwd: path.join(tmp, "project-wt", "recovered-team"),
					state: "complete",
					...(initialTeam === undefined ? {} : { team: initialTeam }),
					spec: "",
					createdAt: Date.now(),
					updatedAt: Date.now(),
					repoPath: root,
					branch: "goal/recovered-team",
					worktreePath: path.join(tmp, "project-wt", "recovered-team"),
					repoWorktrees: { api: apiWorktree, web: webWorktree },
				});

				const goalId = `recovered-team-${String(initialTeam)}`;
				assert.equal(await goalManager.archiveGoal(goalId), true);
				assert.equal(await goalManager.archiveGoal(goalId), true, "operator replay must invoke reconciliation again");
				assert.equal(reconciliation, 2);
				assert.equal(goalStore.get(goalId)?.team, true);
				assert.ok(fs.existsSync(apiWorktree));
				assert.ok(fs.existsSync(webWorktree));
				assert.deepEqual(fakeGitState.commands, [], "marker promotion forbids worktree, local-branch, and remote push-delete cleanup");
			} finally {
				fs.rmSync(tmp, { recursive: true, force: true });
			}
		}
	});

	it("quiesce detaches runtime after bridge-stop failure without archiving or deleting evidence", async () => {
		const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "archived-team-quiesce-"));
		try {
			const repo = makeRepo(tmp);
			const worktree = path.join(tmp, "repo-wt", "quiesced-session");
			makeWorktree(worktree);
			const store = new SessionStore(stateRoot);
			const persisted = makeSession("quiesced-session", {
				archived: false,
				projectId: "project-evidence",
				teamGoalId: "archived-team-goal",
				repoPath: repo,
				branch: "session/quiesced-evidence",
				worktreePath: worktree,
				cwd: worktree,
				messageQueue: [{ text: "durable queued evidence", createdAt: 1 }],
			});
			store.put(persisted);
			await store.flushAsync();
			const manager = makeManager(store);
			const stop = vi.fn(async () => { throw new Error("injected bridge stop failure"); });
			const unsubscribe = vi.fn();
			const close = vi.fn();
			const abortAllWaits = vi.fn();
			const cleanupBg = vi.fn();
			const removeToken = vi.fn();
			const removeSecret = vi.fn();
			const closeExtensions = vi.fn(async () => {});
			const cleanupMcp = vi.fn(async () => {});
			manager.cancelPendingAutoRetry = vi.fn();
			manager.purgeVerifierPromptRows = vi.fn();
			manager.closeExtensionChannelsForSession = closeExtensions;
			manager.cleanupScopedMcpManagersForSessionScope = cleanupMcp;
			manager._untrackConnectedSession = vi.fn();
			manager.bgProcessManager = { abortAllWaits, cleanup: cleanupBg };
			manager.sandboxTokenStore = { removeSession: removeToken };
			manager.sessionSecretStore = { remove: removeSecret };
			const live: any = {
				...persisted,
				status: "idle",
				statusVersion: 0,
				dormant: false,
				lifecycleFenced: false,
				clients: new Set([{ close }]),
				rpcClient: { getState: vi.fn(async () => ({ success: true })), stop },
				unsubscribe,
			};
			manager.sessions.set(persisted.id, live);
			const generationBefore = store.getGeneration();

			await assert.rejects(
				() => manager.quiesceSessionRuntime(persisted.id),
				/runtime was detached after its bridge stop failed: injected bridge stop failure/,
			);
			assert.equal(await manager.quiesceSessionRuntime(persisted.id), true, "second quiesce is an idempotent no-op after cleanup");

			assert.equal(live.lifecycleFenced, true, "replacement dispatch is fenced before bridge stop");
			assert.equal(live.dormant, true);
			assert.equal(live.status, "terminated");
			assert.equal(manager.getSession(persisted.id), undefined);
			assert.equal(stop.mock.calls.length, 1);
			assert.equal(unsubscribe.mock.calls.length, 1);
			assert.equal(close.mock.calls.length, 1);
			assert.equal(abortAllWaits.mock.calls.length, 1);
			assert.equal(cleanupBg.mock.calls.length, 1);
			assert.deepEqual(removeToken.mock.calls[0], [persisted.projectId, persisted.id]);
			assert.deepEqual(removeSecret.mock.calls[0], [persisted.id]);
			assert.equal(closeExtensions.mock.calls.length, 1);
			assert.equal(cleanupMcp.mock.calls.length, 1);
			assert.equal(store.getGeneration(), generationBefore, "quiesce performs no archive or metadata save");
			assert.equal(store.get(persisted.id)?.archived, false);
			assert.deepEqual(store.get(persisted.id)?.messageQueue, persisted.messageQueue);
			assert.ok(fs.existsSync(worktree));
			assert.deepEqual(fakeGitState.commands, [], "quiesce performs no worktree, local branch, or remote branch deletion");
		} finally {
			fs.rmSync(tmp, { recursive: true, force: true });
		}
	});

	it("team goal archive retry preserves multi-repo recovery evidence after ownership rows are gone", async () => {
		const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "team-goal-archive-retry-"));
		try {
			const root = path.join(tmp, "project");
			const api = path.join(root, "api");
			const web = path.join(root, "web");
			fs.mkdirSync(path.join(api, ".git"), { recursive: true });
			fs.mkdirSync(path.join(web, ".git"), { recursive: true });

			const apiWorktree = path.join(tmp, "project-wt", "team-goal", "api");
			const webWorktree = path.join(tmp, "project-wt", "team-goal", "web");
			makeWorktree(apiWorktree);
			makeWorktree(webWorktree);

			const goalStore = new GoalStore(path.join(tmp, "goal-state"), undefined, { persistence: "json" });
			const goalManager = new GoalManager(goalStore, undefined, undefined, {
				commandRunner: fakeGitRunner,
				remotePolicy: { skipRemotePush: true },
			});
			let reconciliation = 0;
			goalManager.setGoalArchiveReconciler(async () => reconciliation++ === 0
				? { archivedSessionIds: ["lead"], teamRemoved: true }
				: { archivedSessionIds: [], suppressedSessionIds: [], teamRemoved: false, teamEntryRetained: false });
			goalStore.put({
				id: "team-goal",
				title: "team goal",
				cwd: path.join(tmp, "project-wt", "team-goal"),
				state: "complete",
				team: true,
				spec: "",
				createdAt: Date.now(),
				updatedAt: Date.now(),
				repoPath: root,
				branch: "goal/team-goal",
				worktreePath: path.join(tmp, "project-wt", "team-goal"),
				repoWorktrees: { api: apiWorktree, web: webWorktree },
			});

			assert.equal(await goalManager.archiveGoal("team-goal"), true);
			assert.equal(await goalManager.archiveGoal("team-goal"), true, "archived retry should replay reconciliation");
			assert.equal(reconciliation, 2);
			assert.ok(fs.existsSync(apiWorktree));
			assert.ok(fs.existsSync(webWorktree));
			assert.deepEqual(fakeGitState.commands, [], "durable team mode must suppress generic worktree/branch cleanup on retry");
		} finally {
			fs.rmSync(tmp, { recursive: true, force: true });
		}
	});

	it("setup failure must not clean a worktree path already owned by another live persisted session", () => {
		const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "shared-wt-guard-setup-failure-"));
		try {
			const repo = makeRepo(tmp);
			const sharedWorktree = path.join(tmp, "repo-wt", "session-shared-setup");
			const branch = "session/setup-failed";
			makeWorktree(sharedWorktree);

			const store = new SessionStore(stateRoot);
			const failedSession = makeSession("setup-failed", {
				cwd: sharedWorktree,
				repoPath: repo,
				branch,
				worktreePath: sharedWorktree,
			});
			store.put(failedSession);
			store.put(makeSession("live-owner", {
				cwd: equivalentPath(sharedWorktree),
				branch: "session/live-owner",
				worktreePath: undefined,
			}));

			const sessions = new Map<string, any>();
			sessions.set(failedSession.id, {
				id: failedSession.id,
				title: failedSession.title,
				cwd: failedSession.cwd,
				status: "preparing",
				statusVersion: 0,
				createdAt: failedSession.createdAt,
				lastActivity: failedSession.lastActivity,
				clients: new Set(),
			});

			handleSetupFailure(
				sessions.get(failedSession.id),
				{ mode: "worktree", repoPath: repo, worktreePath: sharedWorktree, branch } as any,
				new Error("intentional setup failure repro"),
				makePipelineContext(store, sessions),
			);

			assert.ok(
				fs.existsSync(sharedWorktree),
				"SHARED_WORKTREE_GUARD_SETUP_FAILURE_REGRESSION: setup-failure cleanup removed a worktree path already referenced by another non-archived persisted session",
			);
			assert.equal(fakeGitState.commands.some(call => call.args[0] === "worktree"), false);
		} finally {
			fs.rmSync(tmp, { recursive: true, force: true });
		}
	});
});

function makePipelineContext(store: any, sessions: Map<string, any>): any {
	return {
		roleManager: null,
		toolManager: null,
		mcpManager: null,
		goalManager: {},
		taskManager: {},
		projectConfigStore: null,
		sandboxManager: null,
		sandboxTokenStore: null,
		sessionSecretStore: { remove: () => {} },
		groupPolicyStore: null,
		configCascade: null,
		costTracker: {},
		store,
		commandRunner: fakeGitRunner,
		remoteGitPolicy: { skipRemotePush: true },
		searchIndex: {},
		sessions,
		assemblePrompt: () => undefined,
		applySandboxWiring: async () => true,
		handleAgentLifecycle: () => {},
		trackCostFromEvent: () => {},
		broadcast: () => {},
		tryAutoSelectModel: async () => {},
		tryApplyDefaultThinkingLevel: async () => {},
		buildWorkflowList: () => "",
		resolveInitialModel: () => undefined,
		resolveInitialThinkingLevel: () => undefined,
		prStatusStore: {},
	};
}
