// AUTO-GENERATED by scripts/testing-v2/codemod.mjs — do not edit the legacy source.
// Source: tests/tool-startup-resilience.test.ts
// Bucket: v2-core | Method: codemod | Classification: clean

import { afterEach, beforeEach, describe, it } from "vitest";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import { parseToolsDir } from "../../src/server/agent/builtin-config.ts";
import { computeToolActivationArgs, type EffectiveTool } from "../../src/server/agent/tool-activation.ts";
import { ToolManager, __resetToolScanCache } from "../../src/server/agent/tool-manager.ts";
import { __setToolModuleLoadProbeForTesting, preflightConfigExtensionFile } from "../../src/server/agent/tool-extension-preflight.ts";

const roots: string[] = [];

beforeEach(() => {
	// These ToolManager tests own fallback/diagnostic/cascade decisions. Model
	// module-load outcomes deterministically instead of launching a fresh Node +
	// TypeScript loader for every fixture; the real probe has one canary below.
	__setToolModuleLoadProbeForTesting((extensionPath) => {
		const source = fs.readFileSync(extensionPath, "utf-8");
		const thrown = source.match(/^\s*throw new Error\(['\"]([^'\"]+)/m)?.[1];
		return thrown ? `module load failed: ${thrown}` : undefined;
	});
});

afterEach(() => {
	__setToolModuleLoadProbeForTesting(undefined);
	__resetToolScanCache();
	for (const root of roots.splice(0)) {
		try { fs.rmSync(root, { recursive: true, force: true }); } catch { /* ignore */ }
	}
});

function tempRoot(): string {
	const root = fs.mkdtempSync(path.join(os.tmpdir(), "tool-startup-resilience-"));
	roots.push(root);
	return root;
}

function writeFile(file: string, content: string): void {
	fs.mkdirSync(path.dirname(file), { recursive: true });
	fs.writeFileSync(file, content, "utf-8");
}

function writeTool(toolsDir: string, groupDir: string, fileName: string, opts: {
	name: string;
	description: string;
	provider?: string;
}): void {
	writeFile(path.join(toolsDir, groupDir, fileName), [
		`name: ${opts.name}`,
		`description: ${opts.description}`,
		"group: Agent",
		opts.provider ?? "provider:\n  type: bobbit-extension\n  extension: extension.ts",
		"",
	].join("\n"));
}

function extensionPaths(args: string[]): string[] {
	const out: string[] = [];
	for (let i = 0; i < args.length - 1; i++) {
		if (args[i] === "--extension") out.push(path.normalize(args[i + 1]));
	}
	return out;
}

function nonBuiltinExtensionPaths(args: string[]): string[] {
	return extensionPaths(args).filter((p) => !p.endsWith(path.join("_builtins", "extension.ts")));
}

function captureToolDiagnostics(fn: () => void): string {
	const messages: string[] = [];
	const originalWarn = console.warn;
	const originalError = console.error;
	console.warn = (...args: unknown[]) => { messages.push(args.map(String).join(" ")); };
	console.error = (...args: unknown[]) => { messages.push(args.map(String).join(" ")); };
	try {
		fn();
	} finally {
		console.warn = originalWarn;
		console.error = originalError;
	}
	return messages.join("\n");
}

function makeAgentFixture(): {
	configDir: string;
	builtinToolsDir: string;
	configToolsDir: string;
	builtinAgentExtension: string;
	configAgentExtension: string;
} {
	const root = tempRoot();
	const configDir = path.join(root, "project", ".bobbit", "config");
	const configToolsDir = path.join(configDir, "tools");
	const builtinToolsDir = path.join(root, "defaults", "tools");
	const builtinAgentExtension = path.join(builtinToolsDir, "agent", "extension.ts");
	const configAgentExtension = path.join(configToolsDir, "agent", "extension.ts");

	writeTool(builtinToolsDir, "agent", "session_prompt.yaml", {
		name: "session_prompt",
		description: "bundled session prompt",
	});
	writeFile(builtinAgentExtension, "export default function extension() { return {}; }\n");
	fs.mkdirSync(configToolsDir, { recursive: true });

	return { configDir, builtinToolsDir, configToolsDir, builtinAgentExtension, configAgentExtension };
}

describe("tool startup resilience", () => {
	it("accepts a valid TypeScript extension when the module-load probe succeeds", () => {
		const root = tempRoot();
		const groupDir = "agent";
		const extension = "extension.ts";
		writeFile(path.join(root, groupDir, extension), "export default function extension() { return {}; }\n");
		assert.equal(preflightConfigExtensionFile({ toolName: "canary", groupDir, baseDir: root, extension }), undefined);
	});

	it("rejects a broken active config agent override and falls back to bundled session_prompt", () => {
		const fixture = makeAgentFixture();
		writeTool(fixture.configToolsDir, "agent", "session_prompt.yaml", {
			name: "session_prompt",
			description: "broken config session prompt override",
		});
		writeFile(fixture.configAgentExtension, [
			"import './missing-local-gateway.js';",
			"export default function extension() { return {}; }",
			"",
		].join("\n"));

		__resetToolScanCache();
		const tm = new ToolManager(fixture.configDir, fixture.builtinToolsDir);

		assert.equal(
			tm.getToolByName("session_prompt")?.description,
			"bundled session prompt",
			"invalid config-level agent override must not shadow bundled session_prompt",
		);

		const provider = tm.getToolProviders().get("session_prompt");
		assert.ok(provider, "session_prompt must still have a provider via bundled fallback");
		assert.equal(path.resolve(provider.baseDir), path.resolve(fixture.builtinToolsDir));

		const result = computeToolActivationArgs([{ kind: "yaml", name: "session_prompt" }], tm);
		const activeExtensions = nonBuiltinExtensionPaths(result.args);
		assert.ok(
			activeExtensions.some((p) => path.resolve(p) === path.resolve(fixture.builtinAgentExtension)),
			`expected bundled agent extension activation, got ${JSON.stringify(activeExtensions)}`,
		);
		assert.ok(
			!activeExtensions.some((p) => path.resolve(p) === path.resolve(fixture.configAgentExtension)),
			"broken config agent extension must not become runtime activation",
		);
	});

	it("ignores dot-prefixed and disabled/archive config tool-group directories", () => {
		const archiveNames = [".agent", "agent.disabled", "agent.disabled-20260630", "agent.disabled_backup"];

		for (const archiveName of archiveNames) {
			const fixture = makeAgentFixture();
			writeTool(fixture.configToolsDir, archiveName, "session_prompt.yaml", {
				name: "session_prompt",
				description: `archived override from ${archiveName}`,
			});
			writeTool(fixture.configToolsDir, archiveName, "archived_only.yaml", {
				name: `archived_only_${archiveName.replace(/[^a-z0-9]/gi, "_")}`,
				description: `archived-only tool from ${archiveName}`,
			});
			writeFile(path.join(fixture.configToolsDir, archiveName, "extension.ts"), "export default function extension() { return {}; }\n");

			__resetToolScanCache();
			const tm = new ToolManager(fixture.configDir, fixture.builtinToolsDir);
			assert.equal(
				tm.getToolByName("session_prompt")?.description,
				"bundled session prompt",
				`archived group ${archiveName} must not override bundled tools`,
			);
			assert.ok(
				!tm.getAllToolNames().some((name) => name.startsWith("archived_only_")),
				`archived group ${archiveName} must not contribute custom tools`,
			);

			const apiNames = parseToolsDir(fixture.configToolsDir).map((tool) => tool.name);
			assert.deepEqual(apiNames, [], `parseToolsDir must ignore archived group ${archiveName} for /api/tools consistency`);
		}
	});

	it("exposes diagnostics for a broken config override while bundled fallback wins", () => {
		const fixture = makeAgentFixture();
		writeTool(fixture.configToolsDir, "agent", "session_prompt.yaml", {
			name: "session_prompt",
			description: "broken config session prompt override",
		});
		writeFile(fixture.configAgentExtension, [
			"import './missing-local-gateway.js';",
			"export default function extension() { return {}; }",
			"",
		].join("\n"));

		__resetToolScanCache();
		const tm = new ToolManager(fixture.configDir, fixture.builtinToolsDir);
		const tools = tm.getAvailableTools();
		const diagnostics = tm.getToolDiagnostics();

		assert.equal(tools.find((tool) => tool.name === "session_prompt")?.description, "bundled session prompt");
		assert.equal(diagnostics.length, 1);
		assert.equal(diagnostics[0].toolName, "session_prompt");
		assert.equal(diagnostics[0].code, "missing-local-import");
		assert.match(diagnostics[0].message, /missing-local-gateway|agent[\\/]extension\.ts/i);
	});

	it("catches TypeScript module-load failures before activating a config override", () => {
		const fixture = makeAgentFixture();
		const configExtension = path.join(fixture.configToolsDir, "agent", "extension.ts");
		writeTool(fixture.configToolsDir, "agent", "session_prompt.yaml", {
			name: "session_prompt",
			description: "throwing config session prompt override",
		});
		writeFile(configExtension, "throw new Error('boom during module load');\nexport default function extension() { return {}; }\n");

		__resetToolScanCache();
		const tm = new ToolManager(fixture.configDir, fixture.builtinToolsDir);
		const diagnostics = tm.getToolDiagnostics();
		const result = computeToolActivationArgs([{ kind: "yaml", name: "session_prompt" }], tm);

		assert.equal(tm.getToolByName("session_prompt")?.description, "bundled session prompt");
		assert.equal(diagnostics.length, 1);
		assert.equal(diagnostics[0].code, "module-load-failed");
		assert.match(diagnostics[0].message, /boom during module load|extension\.ts/i);
		assert.ok(
			!nonBuiltinExtensionPaths(result.args).some((p) => path.resolve(p) === path.resolve(configExtension)),
			"throwing config extension must not become runtime activation",
		);
	});

	it("falls back from invalid config _builtins and shell extension files before launch", () => {
		const fixture = makeAgentFixture();
		const builtinBuiltinsExtension = path.join(fixture.builtinToolsDir, "_builtins", "extension.ts");
		const configBuiltinsExtension = path.join(fixture.configToolsDir, "_builtins", "extension.ts");
		const builtinShellExtension = path.join(fixture.builtinToolsDir, "shell", "extension.ts");
		const configShellExtension = path.join(fixture.configToolsDir, "shell", "extension.ts");

		writeTool(fixture.builtinToolsDir, "shell", "bash.yaml", {
			name: "bash",
			description: "bundled bash",
			provider: "provider:\n  type: builtin\n  tool: bash",
		});
		writeFile(builtinBuiltinsExtension, "export default function extension() { return {}; }\n");
		writeFile(builtinShellExtension, "export default function extension() { return {}; }\n");
		writeFile(configBuiltinsExtension, "throw new Error('broken config builtins');\nexport default function extension() { return {}; }\n");
		writeTool(fixture.configToolsDir, "shell", "bash.yaml", {
			name: "bash",
			description: "config bash with broken extension",
			provider: "provider:\n  type: builtin\n  tool: bash",
		});
		writeFile(configShellExtension, "throw new Error('broken config shell');\nexport default function extension() { return {}; }\n");

		__resetToolScanCache();
		const tm = new ToolManager(fixture.configDir, fixture.builtinToolsDir);
		const result = computeToolActivationArgs([{ kind: "yaml", name: "bash" }], tm);
		const activeExtensions = extensionPaths(result.args);
		const diagnostics = tm.getToolDiagnostics();

		assert.ok(activeExtensions.some((p) => path.resolve(p) === path.resolve(builtinBuiltinsExtension)));
		assert.ok(activeExtensions.some((p) => path.resolve(p) === path.resolve(builtinShellExtension)));
		assert.ok(!activeExtensions.some((p) => path.resolve(p) === path.resolve(configBuiltinsExtension)));
		assert.ok(!activeExtensions.some((p) => path.resolve(p) === path.resolve(configShellExtension)));
		assert.ok(diagnostics.some((d) => d.groupDir === "_builtins" && /broken config builtins/.test(d.message)));
		assert.ok(diagnostics.some((d) => d.groupDir === "shell" && /broken config shell/.test(d.message)));
		assert.equal(tm.getToolByName("bash")?.description, "bundled bash");
		assert.equal(
			tm.getLocalTools().some((tool) => tool.name === "bash"),
			false,
			"config cascade local tools must skip direct group-extension failures so /api/tools shows the bundled fallback",
		);
	});

	it("keeps valid same-group overrides while falling back only invalid tools", () => {
		const fixture = makeAgentFixture();
		const validExtension = path.join(fixture.configToolsDir, "agent", "valid-extension.ts");
		writeTool(fixture.configToolsDir, "agent", "session_prompt.yaml", {
			name: "session_prompt",
			description: "broken config session prompt override",
		});
		writeTool(fixture.configToolsDir, "agent", "valid_agent_tool.yaml", {
			name: "valid_agent_tool",
			description: "valid config agent tool",
			provider: "provider:\n  type: bobbit-extension\n  extension: valid-extension.ts",
		});
		writeFile(fixture.configAgentExtension, [
			"import './missing-local-gateway.js';",
			"export default function extension() { return {}; }",
			"",
		].join("\n"));
		writeFile(validExtension, "export default function extension() { return {}; }\n");

		__resetToolScanCache();
		const tm = new ToolManager(fixture.configDir, fixture.builtinToolsDir);
		const result = computeToolActivationArgs([
			{ kind: "yaml", name: "session_prompt" },
			{ kind: "yaml", name: "valid_agent_tool" },
		], tm);
		const activeExtensions = nonBuiltinExtensionPaths(result.args);

		assert.equal(tm.getToolByName("session_prompt")?.description, "bundled session prompt");
		assert.equal(tm.getToolByName("valid_agent_tool")?.description, "valid config agent tool");
		assert.ok(activeExtensions.some((p) => path.resolve(p) === path.resolve(fixture.builtinAgentExtension)));
		assert.ok(activeExtensions.some((p) => path.resolve(p) === path.resolve(validExtension)));
		assert.ok(!activeExtensions.some((p) => path.resolve(p) === path.resolve(fixture.configAgentExtension)));
	});

	it("preserves valid copied TypeScript overrides that import Bobbit dependencies", () => {
		const fixture = makeAgentFixture();
		writeTool(fixture.configToolsDir, "agent", "session_prompt.yaml", {
			name: "session_prompt",
			description: "valid copied config session prompt override",
		});
		writeFile(fixture.configAgentExtension, [
			"import { Type } from '@sinclair/typebox';",
			"const schema = Type.Object({ ok: Type.Boolean() });",
			"export default function extension() { return { schema }; }",
			"",
		].join("\n"));

		__resetToolScanCache();
		const tm = new ToolManager(fixture.configDir, fixture.builtinToolsDir);
		const result = computeToolActivationArgs([{ kind: "yaml", name: "session_prompt" }], tm);
		const activeExtensions = nonBuiltinExtensionPaths(result.args);

		assert.deepEqual(tm.getToolDiagnostics(), []);
		assert.equal(tm.getToolByName("session_prompt")?.description, "valid copied config session prompt override");
		assert.ok(activeExtensions.some((p) => path.resolve(p) === path.resolve(fixture.configAgentExtension)));
	});

	it("preserves valid TypeScript overrides that import project-local packages", () => {
		const fixture = makeAgentFixture();
		const projectRoot = path.dirname(path.dirname(fixture.configDir));
		const pkgDir = path.join(projectRoot, "node_modules", "project-local-tool-dep");
		writeFile(path.join(pkgDir, "package.json"), JSON.stringify({ type: "module", exports: "./index.js" }));
		writeFile(path.join(pkgDir, "index.js"), "export const projectLocalOk = true;\n");
		writeTool(fixture.configToolsDir, "agent", "session_prompt.yaml", {
			name: "session_prompt",
			description: "valid project-local package override",
		});
		writeFile(fixture.configAgentExtension, [
			"import { projectLocalOk } from 'project-local-tool-dep';",
			"if (!projectLocalOk) throw new Error('project local package import failed');",
			"export default function extension() { return { projectLocalOk }; }",
			"",
		].join("\n"));

		__resetToolScanCache();
		const tm = new ToolManager(fixture.configDir, fixture.builtinToolsDir);
		const result = computeToolActivationArgs([{ kind: "yaml", name: "session_prompt" }], tm);
		const activeExtensions = nonBuiltinExtensionPaths(result.args);

		assert.deepEqual(tm.getToolDiagnostics(), []);
		assert.equal(tm.getToolByName("session_prompt")?.description, "valid project-local package override");
		assert.ok(activeExtensions.some((p) => path.resolve(p) === path.resolve(fixture.configAgentExtension)));
	});

	it("does not depend on dev-only esbuild for runtime preflight", () => {
		const source = fs.readFileSync(path.resolve("src/server/agent/tool-extension-preflight.ts"), "utf-8");
		assert.doesNotMatch(source, /\besbuild\b/);
	});

	it("omits and diagnoses a broken config-only extension instead of activating it", () => {
		const root = tempRoot();
		const configDir = path.join(root, "project", ".bobbit", "config");
		const configToolsDir = path.join(configDir, "tools");
		const builtinToolsDir = path.join(root, "defaults", "tools");
		const customExtension = path.join(configToolsDir, "custom", "extension.ts");

		writeTool(configToolsDir, "custom", "broken_custom.yaml", {
			name: "broken_custom",
			description: "broken config-only extension tool",
			provider: "provider:\n  type: bobbit-extension\n  extension: extension.ts",
		});
		writeFile(customExtension, [
			"import './missing-local-helper.js';",
			"export default function extension() { return {}; }",
			"",
		].join("\n"));

		__resetToolScanCache();
		const tm = new ToolManager(configDir, builtinToolsDir);
		let result: ReturnType<typeof computeToolActivationArgs> | undefined;
		const diagnostics = captureToolDiagnostics(() => {
			assert.equal(
				tm.getToolProviders().has("broken_custom"),
				false,
				"broken config-only extension must not expose a runtime provider",
			);
			const allowed: EffectiveTool[] = [{ kind: "yaml", name: "broken_custom" }];
			result = computeToolActivationArgs(allowed, tm);
		});

		assert.ok(result, "activation args should be computed without throwing");
		assert.ok(
			!nonBuiltinExtensionPaths(result!.args).some((p) => path.resolve(p) === path.resolve(customExtension)),
			"broken config-only extension must not become runtime activation",
		);
		assert.match(
			diagnostics,
			/broken_custom|missing-local-helper|custom[\\/]extension\.ts/i,
			"broken config-only extension must emit a clear diagnostic",
		);
	});
});
