// AUTO-GENERATED by scripts/testing-v2/codemod.mjs — do not edit the legacy source.
// Source: tests/transcript-reader.test.ts
// Bucket: v2-core | Method: codemod | Classification: clean

import { describe, it } from "vitest";
import assert from "node:assert/strict";
import { EventEmitter } from "node:events";
import type { WorkerOptions } from "node:worker_threads";
import {
	createTranscriptRegexPoolForTests,
	createTranscriptResultHandle,
	measureTranscriptCorrelationOperationsForTests,
	readTranscript,
	readOrphanedBeforeCompaction,
	parseJsonl,
	READ_SESSION_AGENT_ENVELOPE_MAX_BYTES,
	resolveOffset,
	TranscriptReaderError,
	TranscriptRegexSearchError,
	type ReadTranscriptEnvelope,
	type SafeRegexClock,
	type SafeRegexWorkerLike,
} from "../../src/server/agent/transcript-reader.js";

function makeJsonl(messages: Array<{ role: string; content: any; ts?: string }>): string {
	return messages
		.map((m) => JSON.stringify({ type: "message", ts: m.ts, message: { role: m.role, content: m.content } }))
		.join("\n") + "\n";
}

const sample = makeJsonl([
	{ role: "user", content: "hello world", ts: "2026-05-04T00:00:00Z" },
	{ role: "assistant", content: [{ type: "text", text: "hi there" }] },
	{ role: "user", content: "this contains an ERROR" },
	{ role: "assistant", content: [{ type: "tool_use", name: "bash", input: { cmd: "ls" } }] },
	{ role: "user", content: "another line" },
	{ role: "assistant", content: [{ type: "text", text: "second error in transcript" }] },
	{ role: "user", content: "final" },
]);

const memoryTranscript = (content: string) => ({ readContent: async () => content });

type FakeRegexCommand = { kind?: string; pattern?: string; caseSensitive?: boolean; messageIndex?: number; text?: string };

class FakeRegexWorker extends EventEmitter implements SafeRegexWorkerLike {
	readonly commands: FakeRegexCommand[] = [];
	terminateCount = 0;

	constructor(private readonly receive: (worker: FakeRegexWorker, command: FakeRegexCommand) => void) {
		super();
	}

	postMessage(value: unknown): void {
		const command = value as FakeRegexCommand;
		this.commands.push(command);
		this.receive(this, command);
	}

	respond(value: Record<string, unknown>): void {
		this.emit("message", value);
	}

	async terminate(): Promise<number> {
		this.terminateCount++;
		return 1;
	}
}

class DeferredTerminationRegexWorker extends FakeRegexWorker {
	private resolveTermination!: (code: number) => void;
	private readonly termination = new Promise<number>((resolve) => {
		this.resolveTermination = resolve;
	});

	override terminate(): Promise<number> {
		this.terminateCount++;
		return this.termination;
	}

	completeTermination(code = 1): void {
		this.resolveTermination(code);
	}
}

function protocolRegexWorker(
	matcher: (pattern: string, text: string, caseSensitive: boolean) => boolean = (pattern, text, caseSensitive) =>
		caseSensitive ? text.includes(pattern) : text.toLocaleLowerCase().includes(pattern.toLocaleLowerCase()),
): FakeRegexWorker {
	let pattern = "";
	let caseSensitive = false;
	let messageIndex = -1;
	let chunks: string[] | undefined;
	return new FakeRegexWorker((worker, command) => {
		queueMicrotask(() => {
			switch (command.kind) {
				case "init":
					pattern = command.pattern ?? "";
					caseSensitive = !!command.caseSensitive;
					worker.respond({ kind: "ready" });
					break;
				case "segment_start":
					messageIndex = command.messageIndex ?? -1;
					chunks = [];
					worker.respond({ kind: "segment_started" });
					break;
				case "segment_chunk":
					chunks!.push(command.text ?? "");
					worker.respond({ kind: "chunk_accepted" });
					break;
				case "segment_end": {
					const text = chunks!.join("");
					chunks = undefined;
					worker.respond({ kind: "segment_result", messageIndex, matched: matcher(pattern, text, caseSensitive) });
					break;
				}
				case "finish":
					worker.respond({ kind: "done" });
					break;
			}
		});
	});
}

class ManualRegexClock implements SafeRegexClock {
	private current = 0;
	private nextId = 1;
	private readonly timers = new Map<number, { at: number; callback: () => void }>();

	now(): number {
		return this.current;
	}

	setTimer(callback: () => void, delayMs: number): unknown {
		const id = this.nextId++;
		this.timers.set(id, { at: this.current + delayMs, callback });
		return id;
	}

	clearTimer(handle: unknown): void {
		this.timers.delete(handle as number);
	}

	advance(ms: number): void {
		this.current += ms;
		for (;;) {
			const due = [...this.timers.entries()]
				.filter(([, timer]) => timer.at <= this.current)
				.sort((left, right) => left[1].at - right[1].at || left[0] - right[0]);
			if (due.length === 0) return;
			const [id, timer] = due[0];
			this.timers.delete(id);
			timer.callback();
		}
	}
}

describe("transcript-reader / parseJsonl", () => {
	it("skips blank and malformed lines", () => {
		const text = "\n{not json}\n" + JSON.stringify({ type: "message", message: { role: "user", content: "hi" } }) + "\n";
		const out = parseJsonl(text);
		assert.equal(out.length, 1);
		assert.equal(out[0].role, "user");
		assert.equal(out[0].index, 0);
	});

	it("ignores non-message envelopes", () => {
		const text = JSON.stringify({ type: "agent_start" }) + "\n" +
			JSON.stringify({ type: "message", message: { role: "user", content: "x" } });
		const out = parseJsonl(text);
		assert.equal(out.length, 1);
	});

	it("ignores Pi active_tools_change entries interleaved with messages", () => {
		const text = [
			{ type: "message", id: "m1", message: { role: "user", content: "before tools changed" } },
			{ type: "active_tools_change", activeToolNames: ["bash", "read"], reason: "exclude-tools update" },
			{ type: "message", id: "m2", message: { role: "assistant", content: [{ type: "text", text: "after tools changed" }] } },
		].map((entry) => JSON.stringify(entry)).join("\n") + "\n";

		const out = parseJsonl(text);
		assert.equal(out.length, 2);
		assert.deepEqual(out.map((m) => m.role), ["user", "assistant"]);
		assert.deepEqual(out.map((m) => m.index), [0, 1]);
	});
});

describe("transcript-reader / resolveOffset", () => {
	it("non-negative passes through", () => {
		assert.equal(resolveOffset(3, 10), 3);
		assert.equal(resolveOffset(0, 10), 0);
	});
	it("negative indexes from end", () => {
		assert.equal(resolveOffset(-1, 10), 9);
		assert.equal(resolveOffset(-10, 10), 0);
	});
	it("clamps negative beyond start to 0", () => {
		assert.equal(resolveOffset(-20, 5), 0);
	});
});

describe("transcript-reader / readTranscript", () => {
	it("default offset/limit returns first 20", async () => {
		const env = await readTranscript({}, memoryTranscript(sample));
		assert.equal(env.total, 7);
		assert.equal(env.returned, 7);
		assert.equal(env.offsetStart, 0);
		assert.equal(env.offsetEnd, 6);
	});

	it("positive slicing", async () => {
		const env = await readTranscript({ offset: 2, limit: 3 }, memoryTranscript(sample));
		assert.equal(env.returned, 3);
		assert.equal(env.offsetStart, 2);
		assert.equal(env.offsetEnd, 4);
	});

	it("negative offset (tail)", async () => {
		const env = await readTranscript({ offset: -2, limit: 2 }, memoryTranscript(sample));
		assert.equal(env.returned, 2);
		assert.equal(env.offsetStart, 5);
		assert.equal(env.offsetEnd, 6);
	});

	it("offset = -1 returns last message only", async () => {
		const env = await readTranscript({ offset: -1, limit: 1 }, memoryTranscript(sample));
		assert.equal(env.returned, 1);
		assert.equal(env.offsetStart, 6);
	});

	it("out-of-range positive offset returns empty + total", async () => {
		const env = await readTranscript({ offset: 100, limit: 5 }, memoryTranscript(sample));
		assert.equal(env.total, 7);
		assert.equal(env.returned, 0);
		assert.equal(env.offsetStart, -1);
		assert.equal(env.offsetEnd, -1);
		assert.deepEqual(env.messages, []);
	});

	it("compact rendering trims long text and includes tool blocks", async () => {
		const long = "x".repeat(2000);
		const j = makeJsonl([
			{ role: "assistant", content: [
				{ type: "text", text: long },
				{ type: "tool_use", name: "bash", input: { cmd: "echo hi" } },
				{ type: "tool_result", content: "y".repeat(500) },
			] },
		]);
		const env = await readTranscript({}, memoryTranscript(j));
		const m = env.messages[0] as any;
		assert.ok(m.text.length <= 800 + 1, `text length=${m.text.length}`);
		assert.equal(m.toolUses.length, 1);
		assert.equal(m.toolUses[0].name, "bash");
		assert.ok(m.toolUses[0].inputPreview.length <= 200);
		assert.equal(m.toolResults.length, 1);
		assert.ok(m.toolResults[0].preview.length <= 200);
	});

	it("compact redaction omits tool result bodies while preserving metadata", async () => {
		const secret = "UNIQUE_TOOL_RESULT_SECRET\nsecond line";
		const j = makeJsonl([
			{ role: "assistant", content: [{ type: "tool_use", id: "tu-redact", name: "bash", input: { cmd: "cat secret" } }] },
			{ role: "user", ts: "2026-05-04T00:00:01Z", content: [{ type: "tool_result", tool_use_id: "tu-redact", content: secret, is_error: false }] },
		]);

		const env = await readTranscript({ offset: 1, limit: 1, includeToolResults: false }, memoryTranscript(j));
		assert.equal(JSON.stringify(env).includes(secret), false);
		const m = env.messages[0] as any;
		assert.equal(m.index, 1);
		assert.equal(m.role, "user");
		assert.equal(m.ts, "2026-05-04T00:00:01Z");
		const result = m.toolResults[0];
		assert.equal(result.name, "bash");
		assert.equal(result.toolUseId, "tu-redact");
		assert.equal(result.omitted, true);
		assert.equal(result.preview, undefined);
		assert.equal(result.status, "ok");
		assert.equal(result.size.type, "string");
		assert.equal(result.size.chars, secret.length);
		assert.equal(result.size.lines, 2);
		assert.equal(typeof result.size.bytes, "number");
	});

	it("redacts pi-coding-agent message-level toolResult rows", async () => {
		const secret = "PI_MESSAGE_LEVEL_SECRET";
		const j = [
			JSON.stringify({ type: "message", message: { role: "assistant", content: [{ toolCallId: "tu-pi", toolName: "bash", args: { cmd: "run" } }] } }),
			JSON.stringify({ type: "message", message: { role: "toolResult", toolCallId: "tu-pi", toolName: "bash", isError: false, content: secret } }),
		].join("\n") + "\n";

		const compact = await readTranscript({ offset: 1, limit: 1, includeToolResults: false }, memoryTranscript(j));
		assert.equal(JSON.stringify(compact).includes(secret), false);
		const result = (compact.messages[0] as any).toolResults[0];
		assert.equal(result.name, "bash");
		assert.equal(result.toolUseId, "tu-pi");
		assert.equal(result.omitted, true);
		assert.equal(result.size.chars, secret.length);

		const verbose = await readTranscript({ offset: 1, limit: 1, verbose: true, includeToolResults: false }, memoryTranscript(j));
		assert.equal(JSON.stringify(verbose).includes(secret), false);
		assert.equal((verbose.messages[0] as any).content[0].contentOmitted, true);
	});

	it("redacts output-based tool result blocks and removes body aliases", async () => {
		const outputSecret = "OUTPUT_ALIAS_SECRET\nsecond line";
		const resultSecret = "RESULT_ALIAS_SECRET";
		const responseSecret = "RESPONSE_ALIAS_SECRET";
		const textSecret = "TEXT_ALIAS_SECRET";
		const j = makeJsonl([
			{ role: "assistant", content: [{ type: "tool_use", id: "tu-output", name: "bash", input: { cmd: "run" } }] },
			{ role: "user", content: [{
				type: "tool_result",
				tool_use_id: "tu-output",
				output: outputSecret,
				result: resultSecret,
				response: responseSecret,
				text: textSecret,
				is_error: false,
			}] },
		]);

		const compact = await readTranscript({ offset: 1, limit: 1, includeToolResults: false }, memoryTranscript(j));
		for (const secret of [outputSecret, resultSecret, responseSecret, textSecret]) {
			assert.equal(JSON.stringify(compact).includes(secret), false);
		}
		const result = (compact.messages[0] as any).toolResults[0];
		assert.equal(result.name, "bash");
		assert.equal(result.toolUseId, "tu-output");
		assert.equal(result.omitted, true);
		assert.equal(result.preview, undefined);
		assert.equal(result.size.type, "string");
		assert.equal(result.size.chars, outputSecret.length);
		assert.equal(result.size.lines, 2);

		const verbose = await readTranscript({ offset: 1, limit: 1, verbose: true, includeToolResults: false }, memoryTranscript(j));
		for (const secret of [outputSecret, resultSecret, responseSecret, textSecret]) {
			assert.equal(JSON.stringify(verbose).includes(secret), false);
		}
		const block = (verbose.messages[0] as any).content[0];
		assert.equal(block.contentOmitted, true);
		assert.match(block.content, /tool result omitted/);
		assert.equal(block.output, undefined);
		assert.equal(block.result, undefined);
		assert.equal(block.response, undefined);
		assert.equal(block.text, undefined);
		assert.equal(block.resultSize.type, "string");
		assert.equal(block.resultSize.chars, outputSecret.length);
		assert.equal(block.resultSize.lines, 2);
	});

	it("redacts message-level tool result role aliases", async () => {
		for (const role of ["tool_result", "tool"] as const) {
			const id = `tu-${role}`;
			const secret = `ROLE_ALIAS_${role}_SECRET`;
			const body = role === "tool" ? { output: secret } : { content: secret };
			const j = [
				JSON.stringify({ type: "message", message: { role: "assistant", content: [{ toolCallId: id, toolName: "bash", args: { cmd: "run" } }] } }),
				JSON.stringify({ type: "message", message: { role, toolCallId: id, toolName: "bash", isError: false, ...body } }),
			].join("\n") + "\n";

			const compact = await readTranscript({ offset: 1, limit: 1, includeToolResults: false }, memoryTranscript(j));
			assert.equal(JSON.stringify(compact).includes(secret), false);
			const result = (compact.messages[0] as any).toolResults[0];
			assert.equal(result.name, "bash");
			assert.equal(result.toolUseId, id);
			assert.equal(result.omitted, true);
			assert.equal(result.size.chars, secret.length);

			const verbose = await readTranscript({ offset: 1, limit: 1, verbose: true, includeToolResults: false }, memoryTranscript(j));
			assert.equal(JSON.stringify(verbose).includes(secret), false);
			const block = (verbose.messages[0] as any).content[0];
			assert.equal(block.type, "tool_result");
			assert.equal(block.toolUseId, id);
			assert.equal(block.name, "bash");
			assert.equal(block.contentOmitted, true);
			assert.match(block.content, /tool result omitted/);
		}
	});

	it("redacts block-level camel-case tool result variants", async () => {
		const typeSecret = "CAMEL_TYPE_TOOL_RESULT_SENTINEL";
		const roleSecret = "CAMEL_ROLE_TOOL_RESULT_SENTINEL";
		const j = makeJsonl([
			{ role: "assistant", content: [
				{ type: "toolCall", id: "tu-camel-type", name: "bash", input: { cmd: "run" } },
				{ type: "toolCall", id: "tu-camel-role", name: "read", input: { path: "x" } },
			] },
			{ role: "user", content: [
				{ type: "toolResult", tool_use_id: "tu-camel-type", content: typeSecret, isError: false },
				{ type: "text", role: "toolResult", toolCallId: "tu-camel-role", text: roleSecret, isError: true },
			] },
		]);

		const compact = await readTranscript({ offset: 1, limit: 1, includeToolResults: false }, memoryTranscript(j));
		assert.equal(JSON.stringify(compact).includes(typeSecret), false);
		assert.equal(JSON.stringify(compact).includes(roleSecret), false);
		const compactMessage = compact.messages[0] as any;
		assert.equal(compactMessage.text, "");
		assert.equal(compactMessage.toolResults.length, 2);
		assert.equal(compactMessage.toolResults[0].name, "bash");
		assert.equal(compactMessage.toolResults[0].toolUseId, "tu-camel-type");
		assert.equal(compactMessage.toolResults[0].omitted, true);
		assert.equal(compactMessage.toolResults[0].status, "ok");
		assert.equal(compactMessage.toolResults[0].size.chars, typeSecret.length);
		assert.equal(compactMessage.toolResults[1].name, "read");
		assert.equal(compactMessage.toolResults[1].toolUseId, "tu-camel-role");
		assert.equal(compactMessage.toolResults[1].omitted, true);
		assert.equal(compactMessage.toolResults[1].status, "error");
		assert.equal(compactMessage.toolResults[1].size.chars, roleSecret.length);

		const pattern = await readTranscript({ pattern: roleSecret, includeToolResults: false }, memoryTranscript(j));
		assert.equal(pattern.matchCount, 1);
		assert.equal(pattern.messages[0].index, 1);
		assert.equal(JSON.stringify(pattern).includes(roleSecret), false);

		const verbose = await readTranscript({ offset: 1, limit: 1, verbose: true, includeToolResults: false }, memoryTranscript(j));
		assert.equal(JSON.stringify(verbose).includes(typeSecret), false);
		assert.equal(JSON.stringify(verbose).includes(roleSecret), false);
		const blocks = (verbose.messages[0] as any).content;
		assert.equal(blocks[0].type, "toolResult");
		assert.equal(blocks[0].name, "bash");
		assert.equal(blocks[0].contentOmitted, true);
		assert.match(blocks[0].content, /tool result omitted/);
		assert.equal(blocks[0].resultSize.chars, typeSecret.length);
		assert.equal(blocks[1].role, "toolResult");
		assert.equal(blocks[1].name, "read");
		assert.equal(blocks[1].text, undefined);
		assert.equal(blocks[1].contentOmitted, true);
		assert.match(blocks[1].content, /tool result omitted/);
		assert.equal(blocks[1].resultSize.chars, roleSecret.length);
	});

	it("compact opt-in includes tool result previews", async () => {
		const secret = "VISIBLE_TOOL_RESULT_SECRET";
		const j = makeJsonl([
			{ role: "assistant", content: [{ type: "tool_use", id: "tu-include", name: "grep", input: { pattern: "SECRET" } }] },
			{ role: "user", content: [{ type: "tool_result", tool_use_id: "tu-include", content: secret }] },
		]);

		const env = await readTranscript({ offset: 1, limit: 1, includeToolResults: true }, memoryTranscript(j));
		const result = (env.messages[0] as any).toolResults[0];
		assert.equal(result.name, "grep");
		assert.equal(result.preview, secret);
		assert.equal(result.omitted, undefined);
	});

	it("verbose redaction preserves tool result structure with an omission marker", async () => {
		const secret = "VERBOSE_SECRET_TOOL_BODY";
		const j = makeJsonl([
			{ role: "assistant", content: [{ type: "tool_use", id: "tu-verbose", name: "bash", input: { cmd: "echo" } }] },
			{ role: "user", content: [{ type: "tool_result", tool_use_id: "tu-verbose", content: secret, is_error: true }] },
		]);

		const env = await readTranscript({ offset: 1, limit: 1, verbose: true, includeToolResults: false }, memoryTranscript(j));
		assert.equal(JSON.stringify(env).includes(secret), false);
		const block = (env.messages[0] as any).content[0];
		assert.equal(block.type, "tool_result");
		assert.equal(block.tool_use_id, "tu-verbose");
		assert.equal(block.name, "bash");
		assert.equal(block.contentOmitted, true);
		assert.equal(block.status, "error");
		assert.equal(block.resultSize.type, "string");
		assert.match(block.content, /tool result omitted/);
	});

	it("verbose opt-in includes raw tool result content", async () => {
		const secret = "RAW_VERBOSE_TOOL_BODY";
		const j = makeJsonl([
			{ role: "assistant", content: [{ type: "tool_use", id: "tu-raw", name: "read", input: { path: "x" } }] },
			{ role: "user", content: [{ type: "tool_result", tool_use_id: "tu-raw", content: secret }] },
		]);

		const env = await readTranscript({ offset: 1, limit: 1, verbose: true, includeToolResults: true }, memoryTranscript(j));
		const block = (env.messages[0] as any).content[0];
		assert.equal(block.content, secret);
		assert.equal(block.contentOmitted, undefined);
	});

	it("pattern can match omitted tool result text and opt-in exposes the narrow result", async () => {
		const secret = "PATTERN_ONLY_SECRET";
		const j = makeJsonl([
			{ role: "assistant", content: [{ type: "tool_use", id: "tu-pattern", name: "bash", input: { cmd: "run" } }] },
			{ role: "user", content: [{ type: "tool_result", tool_use_id: "tu-pattern", content: secret }] },
		]);

		const redacted = await readTranscript({ pattern: secret, includeToolResults: false }, memoryTranscript(j));
		assert.equal(redacted.matchCount, 1);
		assert.equal(redacted.messages[0].index, 1);
		assert.equal(JSON.stringify(redacted).includes(secret), false);

		const raw = await readTranscript({ offset: 1, limit: 1, verbose: true, includeToolResults: true }, memoryTranscript(j));
		assert.equal((raw.messages[0] as any).content[0].content, secret);
	});

	it("resolves tool names from the full transcript across pagination boundaries", async () => {
		const j = makeJsonl([
			{ role: "assistant", content: [{ type: "tool_use", id: "tu-boundary", name: "bash", input: { cmd: "long" } }] },
			{ role: "user", content: [{ type: "tool_result", tool_use_id: "tu-boundary", content: "boundary output" }] },
		]);

		const env = await readTranscript({ offset: 1, limit: 1, includeToolResults: false }, memoryTranscript(j));
		assert.equal((env.messages[0] as any).toolResults[0].name, "bash");
	});

	it("verbose returns raw content", async () => {
		const env = await readTranscript({ offset: 1, limit: 1, verbose: true }, memoryTranscript(sample));
		const m = env.messages[0] as any;
		assert.ok(Array.isArray(m.content));
		assert.equal(m.content[0].type, "text");
	});

	it("pattern filters to matches and reports matchCount", async () => {
		const env = await readTranscript({ pattern: "error" }, memoryTranscript(sample));
		assert.equal(env.total, 7);
		assert.equal(env.matchCount, 2);
		assert.equal(env.returned, 2);
		const indices = env.messages.map((m) => m.index);
		assert.deepEqual(indices, [2, 5]);
	});

	it("pattern with case_sensitive misses lowercase", async () => {
		const env = await readTranscript({ pattern: "ERROR", caseSensitive: true }, memoryTranscript(sample));
		assert.equal(env.matchCount, 1);
		assert.equal(env.returned, 1);
		assert.equal(env.messages[0].index, 2);
	});

	it("pattern + window: last 1 of 2 matches", async () => {
		const env = await readTranscript({ pattern: "error", offset: -1, limit: 1 }, memoryTranscript(sample));
		assert.equal(env.matchCount, 2);
		assert.equal(env.returned, 1);
		assert.equal(env.messages[0].index, 5);
	});

	it("pattern + context expands neighbours and dedupes", async () => {
		// matches at 2 and 5; ±1 context expands to {1,2,3,4,5,6}
		const env = await readTranscript({ pattern: "error", context: 1 }, memoryTranscript(sample));
		assert.equal(env.matchCount, 2);
		const indices = env.messages.map((m) => m.index);
		assert.deepEqual(indices, [1, 2, 3, 4, 5, 6]);
	});

	it("invalid regex throws invalid_regex", async () => {
		await assert.rejects(
			() => readTranscript({ pattern: "(" }, memoryTranscript(sample)),
			(err: unknown) => err instanceof TranscriptReaderError && err.code === "invalid_regex",
		);
	});

	it("limit out of range throws invalid_params", async () => {
		await assert.rejects(
			() => readTranscript({ limit: 0 }, memoryTranscript(sample)),
			(err: unknown) => err instanceof TranscriptReaderError && err.code === "invalid_params",
		);
		await assert.rejects(
			() => readTranscript({ limit: 1000 }, memoryTranscript(sample)),
			(err: unknown) => err instanceof TranscriptReaderError && err.code === "invalid_params",
		);
	});

	it("context > 5 throws invalid_params", async () => {
		await assert.rejects(
			() => readTranscript({ pattern: "x", context: 6 }, memoryTranscript(sample)),
			(err: unknown) => err instanceof TranscriptReaderError && err.code === "invalid_params",
		);
	});

	it("empty content throws transcript_unavailable", async () => {
		await assert.rejects(
			() => readTranscript({}, memoryTranscript("")),
			(err: unknown) => err instanceof TranscriptReaderError && err.code === "transcript_unavailable",
		);
	});

	it("null content throws transcript_unavailable", async () => {
		await assert.rejects(
			() => readTranscript({}, { readContent: async () => null }),
			(err: unknown) => err instanceof TranscriptReaderError && err.code === "transcript_unavailable",
		);
	});

	it("envelope exposes matchCount only when pattern is set", async () => {
		const noPattern = await readTranscript({}, memoryTranscript(sample));
		assert.equal((noPattern as ReadTranscriptEnvelope).matchCount, undefined);
		const withPattern = await readTranscript({ pattern: "x" }, memoryTranscript(sample));
		assert.equal(typeof withPattern.matchCount, "number");
	});

	it("ignores active_tools_change entries when reading transcript totals and windows", async () => {
		const text = [
			{ type: "active_tools_change", activeToolNames: ["read"] },
			{ type: "message", message: { role: "user", content: "first" } },
			{ type: "active_tools_change", activeToolNames: ["read", "bash"] },
			{ type: "message", message: { role: "assistant", content: [{ type: "text", text: "second" }] } },
			{ type: "active_tools_change", activeToolNames: [] },
		].map((entry) => JSON.stringify(entry)).join("\n") + "\n";

		const env = await readTranscript({ offset: -1, limit: 1 }, memoryTranscript(text));
		assert.equal(env.total, 2);
		assert.equal(env.returned, 1);
		assert.equal(env.offsetStart, 1);
		assert.equal(env.messages[0].role, "assistant");
	});

	it("infers legacy authors sequentially without treating tool output as human/tool-authored", async () => {
		const text = makeJsonl([
			{ role: "user", content: "question" },
			{ role: "assistant", content: [{ type: "text", text: "calling" }] },
			{ role: "user", content: [{ type: "tool_result", content: "output" }] },
		]);
		const env = await readTranscript({}, {
			...memoryTranscript(text),
			authorContext: { session: { id: "target", title: "Target agent" } },
		});
		assert.deepEqual(env.messages.map((message: any) => message.author), [
			{ kind: "user", id: "user:local", label: "User" },
			{ kind: "agent", id: "session:target", label: "Target agent" },
			{ kind: "agent", id: "session:target", label: "Target agent" },
		]);
		assert.notEqual((env.messages[2] as any).author.kind, "tool");
	});

	it("uses a sidecar binding to distinguish a system prompt from a human prompt", async () => {
		const text = JSON.stringify({
			type: "message",
			id: "message-system",
			message: { role: "user", content: "notification" },
		}) + "\n";
		const env = await readTranscript({}, {
			...memoryTranscript(text),
			authorContext: {
				session: { id: "target", title: "Target" },
				sidecarEntries: [{
					schemaVersion: 1,
					type: "prompt-author",
					promptId: "prompt-system",
					dispatchedAt: 100,
					modelText: "notification",
					source: "task-notification",
					author: { kind: "system", id: "system:bobbit", label: "Bobbit" },
					settlement: {
						schemaVersion: 1,
						type: "prompt-author-settlement",
						promptId: "prompt-system",
						settledAt: 110,
						outcome: "echoed",
						messageId: "message-system",
					},
				}],
			},
		});
		assert.deepEqual((env.messages[0] as any).author, {
			kind: "system", id: "system:bobbit", label: "Bobbit",
		});
	});
});

describe("transcript-reader / agent call correlation", () => {
	it("correlates repeated IDs with one forward update and lookup per pair", async () => {
		const pairCount = 4_096;
		const lines: string[] = [];
		for (let index = 0; index < pairCount; index++) {
			lines.push(JSON.stringify({
				type: "message",
				message: {
					role: "assistant",
					content: [{ type: "toolCall", id: "reused-id", name: `tool-${index}`, arguments: { index } }],
				},
			}));
			lines.push(JSON.stringify({
				type: "message",
				message: {
					role: "toolResult",
					toolCallId: "reused-id",
					status: index % 2 === 0 ? "ok" : "error",
					content: `result-${index}`,
				},
			}));
		}
		const text = lines.join("\n") + "\n";

		assert.deepEqual(measureTranscriptCorrelationOperationsForTests(text), {
			callUpdates: pairCount,
			resultLookups: pairCount,
		});

		const sessionId = "repeated-correlation";
		const envelope = await readTranscript({ offset: -1, limit: 1 }, {
			...memoryTranscript(text),
			projection: "agent",
			sessionId,
		});
		const result = (envelope.messages[0] as any).toolResults[0];
		assert.equal(result.name, `tool-${pairCount - 1}`);
		assert.equal(result.status, "error");
		assert.equal(result.handle, createTranscriptResultHandle(
			sessionId,
			pairCount * 2 - 1,
			0,
			`result-${pairCount - 1}`,
		));
		assert.deepEqual((envelope.correlations as any)[result.ref], {
			name: `tool-${pairCount - 1}`,
			messageIndex: pairCount * 2 - 2,
			blockIndex: 0,
		});
	});

	it("uses only lower block indexes when correlating within one message", async () => {
		const text = [
			{
				type: "message",
				message: {
					role: "assistant",
					content: [{ type: "toolCall", id: "same-id", name: "prior-call", arguments: {} }],
				},
			},
			{
				type: "message",
				message: {
					role: "assistant",
					content: [
						{ type: "tool_result", tool_use_id: "same-id", content: "before-call", is_error: true },
						{ type: "toolCall", id: "same-id", name: "same-message-call", arguments: {} },
						{ type: "tool_result", tool_use_id: "same-id", content: "after-call", status: "ok" },
					],
				},
			},
		].map((entry) => JSON.stringify(entry)).join("\n") + "\n";
		const sessionId = "same-message-correlation";

		const envelope = await readTranscript({ offset: 1, limit: 1 }, {
			...memoryTranscript(text),
			projection: "agent",
			sessionId,
		});
		const message = envelope.messages[0] as any;
		assert.equal(message.toolCalls[0].name, "same-message-call");
		assert.deepEqual(message.toolResults.map((result: any) => ({
			name: result.name,
			status: result.status,
			handle: result.handle,
		})), [
			{
				name: "prior-call",
				status: "error",
				handle: createTranscriptResultHandle(sessionId, 1, 0, "before-call"),
			},
			{
				name: "same-message-call",
				status: "ok",
				handle: createTranscriptResultHandle(sessionId, 1, 2, "after-call"),
			},
		]);
		assert.deepEqual((envelope.correlations as any)[message.toolResults[0].ref], {
			name: "prior-call",
			messageIndex: 0,
			blockIndex: 0,
		});
		assert.equal(message.toolResults[1].ref, message.toolCalls[0].ref);
	});
});

describe("transcript-reader / bounded regex worker pool", () => {
	it("pins the production default active worker cap at exactly two", async () => {
		const workers: FakeRegexWorker[] = [];
		const pool = createTranscriptRegexPoolForTests({
			workerFactory: () => {
				const worker = new FakeRegexWorker(() => undefined);
				workers.push(worker);
				return worker;
			},
		});

		const first = pool.search([["first"]], "never").catch((error) => error);
		const second = pool.search([["second"]], "never").catch((error) => error);
		const queued = pool.search([["queued"]], "never").catch((error) => error);

		assert.equal(workers.length, 2, "the third concurrent search must queue behind exactly two workers");
		assert.deepEqual(pool.stats(), { activeWorkers: 2, queuedJobs: 1, queuedCorpusUnits: 6 });
		pool.stop();
		for (const outcome of await Promise.all([first, second, queued])) {
			assert.equal(outcome instanceof TranscriptRegexSearchError && outcome.code, "REGEX_SEARCH_STOPPED");
		}
		assert.deepEqual(workers.map((worker) => worker.terminateCount), [1, 1]);
	});

	it("caps active workers and rejects queued count or corpus overload without spawning", async () => {
		const clock = new ManualRegexClock();
		const workers: FakeRegexWorker[] = [];
		const pool = createTranscriptRegexPoolForTests({
			maxActiveWorkers: 1,
			maxQueuedJobs: 2,
			maxQueuedCorpusUnits: 5,
			wallTimeoutMs: 1_000,
			clock,
			workerFactory: () => {
				const worker = new FakeRegexWorker(() => undefined);
				workers.push(worker);
				return worker;
			},
		});

		const active = pool.search([["active"]], "never", false, 1).catch((error) => error);
		const queuedAtCorpusCap = pool.search([["queued"]], "never", false, 5).catch((error) => error);
		const corpusOverload = await pool.search([["too large"]], "never", false, 1).catch((error) => error);
		const queuedAtCountCap = pool.search([[]], "never", false, 0).catch((error) => error);
		const countOverload = await pool.search([[]], "never", false, 0).catch((error) => error);

		assert.equal(workers.length, 1, "queued and rejected jobs must not construct more workers");
		assert.deepEqual(pool.stats(), { activeWorkers: 1, queuedJobs: 2, queuedCorpusUnits: 5 });
		assert.equal(corpusOverload instanceof TranscriptRegexSearchError && corpusOverload.code, "REGEX_SEARCH_OVERLOADED");
		assert.equal(countOverload instanceof TranscriptRegexSearchError && countOverload.code, "REGEX_SEARCH_OVERLOADED");

		pool.stop();
		for (const outcome of await Promise.all([active, queuedAtCorpusCap, queuedAtCountCap])) {
			assert.equal(outcome instanceof TranscriptRegexSearchError && outcome.code, "REGEX_SEARCH_STOPPED");
		}
		assert.equal(workers[0].terminateCount, 1);
	});

	it("keeps a lifecycle error sink through timeout termination and drains already-queued recovery work", async () => {
		const clock = new ManualRegexClock();
		const workers: FakeRegexWorker[] = [];
		const constructorOptions: WorkerOptions[] = [];
		let settlements = 0;
		const pool = createTranscriptRegexPoolForTests({
			maxActiveWorkers: 1,
			wallTimeoutMs: 25,
			clock,
			workerFactory: (_source, options) => {
				constructorOptions.push(options);
				const worker = workers.length === 0
					? new DeferredTerminationRegexWorker(() => undefined)
					: protocolRegexWorker();
				workers.push(worker);
				return worker;
			},
			yieldToEventLoop: async () => undefined,
		});

		const timedOut = pool.search([["first"]], "first").then(
			(matches) => {
				settlements++;
				return matches;
			},
			(error: unknown) => {
				settlements++;
				return error;
			},
		);
		assert.deepEqual(constructorOptions[0].workerData, { modulePath: constructorOptions[0].workerData!.modulePath });
		assert.equal(Object.prototype.hasOwnProperty.call(constructorOptions[0].workerData!, "pattern"), false);
		assert.equal(Object.prototype.hasOwnProperty.call(constructorOptions[0].workerData!, "segmentsByMessage"), false);
		assert.deepEqual(constructorOptions[0].resourceLimits, {
			maxOldGenerationSizeMb: 64,
			maxYoungGenerationSizeMb: 16,
			stackSizeMb: 4,
		});

		clock.advance(10);
		const recovered = pool.search([["second has needle"]], "needle");
		assert.deepEqual(pool.stats(), { activeWorkers: 1, queuedJobs: 1, queuedCorpusUnits: 17 });
		clock.advance(15);

		const firstWorker = workers[0] as DeferredTerminationRegexWorker;
		assert.equal(firstWorker.terminateCount, 1);
		assert.equal(firstWorker.listenerCount("error"), 1, "late worker failures need a sink until termination settles");
		assert.doesNotThrow(() => firstWorker.emit("error", new Error("late OOM during termination")));
		assert.equal(settlements, 0, "the search must wait for termination and settle exactly once");
		assert.equal(workers.length, 1, "queued work must not start before active worker termination settles");

		firstWorker.completeTermination();
		const timeoutError = await timedOut;
		assert.equal(timeoutError instanceof TranscriptRegexSearchError && timeoutError.code, "REGEX_SEARCH_TIMEOUT");
		assert.equal(settlements, 1);
		assert.equal(firstWorker.listenerCount("error"), 0, "termination completion must remove the lifecycle sink");
		assert.deepEqual(firstWorker.eventNames(), [], "termination completion must not leak worker listeners");

		assert.deepEqual(await recovered, [0]);
		assert.equal(workers.length, 2, "the queued recovery scan must drain without starvation");
		assert.equal(workers[1].terminateCount, 1);
		assert.deepEqual(pool.stats(), { activeWorkers: 0, queuedJobs: 0, queuedCorpusUnits: 0 });
		pool.stop();
	});

	for (const failure of ["error", "exit"] as const) {
		it(`settles ${failure === "error" ? "worker errors" : "premature zero exits"}, terminates, and recovers`, async () => {
			const workers: FakeRegexWorker[] = [];
			const pool = createTranscriptRegexPoolForTests({
				maxActiveWorkers: 1,
				workerFactory: () => {
					const worker = workers.length === 0
						? new FakeRegexWorker((current, command) => {
							if (command.kind === "init") {
								queueMicrotask(() => failure === "error"
									? current.emit("error", new Error("injected worker fault"))
									: current.emit("exit", 0));
							}
						})
						: protocolRegexWorker();
					workers.push(worker);
					return worker;
				},
				yieldToEventLoop: async () => undefined,
			});

			const failedPromise = pool.search([["first"]], "first").catch((error) => error);
			const recovered = pool.search([["recovered"]], "recovered");
			assert.deepEqual(pool.stats(), { activeWorkers: 1, queuedJobs: 1, queuedCorpusUnits: 9 });

			const failed = await failedPromise;
			assert.equal(failed instanceof TranscriptRegexSearchError && failed.code, "REGEX_WORKER_FAILED");
			assert.match(failed.message, failure === "error" ? /injected worker fault/ : /exited before completing \(code 0\)/);
			assert.equal(workers[0].terminateCount, 1);
			assert.deepEqual(await recovered, [0]);
			assert.equal(workers[1].terminateCount, 1);
			assert.deepEqual(pool.stats(), { activeWorkers: 0, queuedJobs: 0, queuedCorpusUnits: 0 });
			pool.stop();
		});
	}

	it("streams one bounded chunk at a time and yields while preserving whole-segment semantics", async () => {
		const chunks: string[] = [];
		let chunksInFlight = 0;
		let maxChunksInFlight = 0;
		let yields = 0;
		let eventLoopTurns = 0;
		let worker: FakeRegexWorker;
		const pool = createTranscriptRegexPoolForTests({
			maxActiveWorkers: 1,
			chunkUnits: 7,
			workerFactory: () => {
				const protocol = protocolRegexWorker((pattern, text) => text === pattern);
				const originalPost = protocol.postMessage.bind(protocol);
				protocol.postMessage = (value: unknown): void => {
					const command = value as FakeRegexCommand;
					if (command.kind === "segment_chunk") {
						chunksInFlight++;
						maxChunksInFlight = Math.max(maxChunksInFlight, chunksInFlight);
						chunks.push(command.text ?? "");
						queueMicrotask(() => { chunksInFlight--; });
					}
					originalPost(value);
				};
				worker = protocol;
				return protocol;
			},
			yieldToEventLoop: () => new Promise((resolve) => {
				yields++;
				setImmediate(() => {
					eventLoopTurns++;
					resolve();
				});
			}),
		});
		const wholeSegment = "prefix-BOUNDARY-crosses-chunks-suffix";
		const manySegments = Array.from({ length: 24 }, (_, index) => `non-match-${index}`);
		const matches = await pool.search([[...manySegments, wholeSegment], ["other"]], wholeSegment);

		assert.deepEqual(matches, [0]);
		assert.equal(chunks.join("").includes(wholeSegment), true);
		assert.equal(chunks.every((chunk) => chunk.length <= 7), true);
		assert.equal(maxChunksInFlight, 1, "the parent must wait for each worker ack");
		assert.equal(eventLoopTurns, yields, "each cooperative transfer yield must advance the event loop");
		assert.ok(yields > manySegments.length, "large and numerous segments must yield repeatedly");
		assert.equal(worker!.terminateCount, 1);
		pool.stop();
	});

	it("rejects oversized patterns before constructing a worker", async () => {
		let workerConstructions = 0;
		const pool = createTranscriptRegexPoolForTests({
			workerFactory: () => {
				workerConstructions++;
				return protocolRegexWorker();
			},
		});
		await assert.rejects(
			() => pool.search([["text"]], "x".repeat(4097)),
			(error: unknown) => error instanceof TranscriptReaderError && error.code === "invalid_params",
		);
		assert.equal(workerConstructions, 0);
		let transcriptReads = 0;
		await assert.rejects(
			() => readTranscript({ pattern: "x".repeat(4097) }, {
				readContent: async () => {
					transcriptReads++;
					return sample;
				},
			}),
			(error: unknown) => error instanceof TranscriptReaderError && error.code === "invalid_params",
		);
		assert.equal(transcriptReads, 0, "oversized patterns must reject before transcript fetch or worker construction");
		pool.stop();
	});
});

describe("transcript-reader / safe regex search", () => {
	const audiences = [
		{
			name: "legacy/direct",
			options: (content: string) => memoryTranscript(content),
		},
		{
			name: "agent",
			options: (content: string) => ({
				...memoryTranscript(content),
				projection: "agent" as const,
				sessionId: "safe-regex-test",
			}),
		},
	] as const;

	for (const audience of audiences) {
		describe(audience.name, () => {
			it("retains supported regex and case-sensitivity semantics", async () => {
				const insensitive = await readTranscript(
					{ pattern: "\\berr(or)?\\b" },
					audience.options(sample),
				);
				assert.equal(insensitive.matchCount, 2);
				assert.deepEqual(insensitive.messages.map((message) => message.index), [2, 5]);

				const sensitive = await readTranscript(
					{ pattern: "\\bERROR\\b", caseSensitive: true },
					audience.options(sample),
				);
				assert.equal(sensitive.matchCount, 1);
				assert.equal(sensitive.messages[0].index, 2);
			});

			it("deterministically rejects syntax errors and unsupported constructs", async () => {
				for (const pattern of ["(", "ERROR(?= here)", "(ERROR)\\1"]) {
					await assert.rejects(
						() => readTranscript({ pattern }, audience.options(sample)),
						(error: unknown) => error instanceof TranscriptReaderError && error.code === "invalid_regex",
					);
				}
			});

			it("searches large omitted result bodies without exposing them", async () => {
				const sentinel = "SAFE_REGEX_RESULT_SENTINEL";
				const resultBody = `prefix-${"x".repeat(256 * 1024)}-${sentinel}`;
				const transcript = makeJsonl([
					{ role: "assistant", content: [{ type: "tool_use", id: "safe-regex-call", name: "bash", input: { cmd: "run" } }] },
					{ role: "user", content: [{ type: "tool_result", tool_use_id: "safe-regex-call", content: resultBody }] },
				]);

				const envelope = await readTranscript(
					{ pattern: sentinel, includeToolResults: false },
					audience.options(transcript),
				);
				assert.equal(envelope.matchCount, 1);
				assert.equal(envelope.messages[0].index, 1);
				assert.equal(JSON.stringify(envelope).includes(sentinel), false);
			});

			it("retains context expansion and filtered pagination", async () => {
				const envelope = await readTranscript(
					{ pattern: "error", context: 1, offset: -2, limit: 2 },
					audience.options(sample),
				);
				assert.equal(envelope.matchCount, 2);
				assert.deepEqual(envelope.messages.map((message) => message.index), [5, 6]);
			});

			it("handles a catastrophic backtracking pattern off the gateway event loop", async () => {
				const transcript = makeJsonl([
					{ role: "user", content: `${"a".repeat(256 * 1024)}!` },
					{ role: "assistant", content: "a".repeat(64) },
				]);
				let eventLoopAdvanced = false;
				const eventLoopTurn = new Promise<void>((resolve) => {
					setImmediate(() => {
						eventLoopAdvanced = true;
						resolve();
					});
				});

				const envelope = await readTranscript(
					{ pattern: "^(a+)+$" },
					audience.options(transcript),
				);
				assert.equal(eventLoopAdvanced, true);
				assert.equal(envelope.matchCount, 1);
				assert.equal(envelope.messages[0].index, 1);
				await eventLoopTurn;
			});
		});
	}
});

describe("transcript-reader / agent filtered pagination metadata", () => {
	it("records the resolved position and count of a completed negative context tail", async () => {
		const text = Array.from({ length: 10 }, (_, index) => ({
			type: "message",
			message: {
				role: index % 2 === 0 ? "assistant" : "user",
				content: index === 2 || index === 8 ? `needle at ${index}` : `row ${index}`,
			},
		})).map((entry) => JSON.stringify(entry)).join("\n") + "\n";

		const envelope = await readTranscript({
			pattern: "needle",
			context: 1,
			offset: -2,
			limit: 2,
		}, {
			...memoryTranscript(text),
			projection: "agent",
			sessionId: "filtered-tail",
		});

		assert.equal(envelope.matchCount, 2);
		assert.equal(envelope.pageStart, 4);
		assert.equal(envelope.pageCount, 6);
		assert.deepEqual(envelope.messages.map((message) => message.index), [8, 9]);
		assert.equal(envelope.nextOffset, undefined);
	});
});

describe("transcript-reader / agent timestamp budgets", () => {
	const safeTimestampPrefix = "x".repeat(63);
	const oversizedTimestamp = safeTimestampPrefix + "😀" + "y".repeat(100 * 1024);

	it("caps ts/timestamp in normal and summary rows while pagination makes exact progress", async () => {
		const oversizedCalls = Array.from({ length: 64 }, (_, index) => ({
			type: "toolCall",
			id: `call-${index}`,
			name: "read",
			arguments: { path: `fixture-${index}` },
		}));
		const text = [
			{
				type: "message",
				timestamp: oversizedTimestamp,
				message: { role: "assistant", content: oversizedCalls },
			},
			{
				type: "message",
				ts: oversizedTimestamp,
				message: { role: "assistant", content: "next row" },
			},
		].map((entry) => JSON.stringify(entry)).join("\n") + "\n";
		const options = {
			...memoryTranscript(text),
			projection: "agent" as const,
			sessionId: "timestamp-page",
			serializedBudgetBytes: 512,
		};

		const first = await readTranscript({ limit: 2, includeToolResults: false }, options);
		assert.ok(Buffer.byteLength(JSON.stringify(first), "utf8") <= 512);
		assert.equal(first.returned, 1);
		assert.equal(first.offsetStart, 0);
		assert.equal(first.offsetEnd, 0);
		const summary = first.messages[0] as any;
		assert.equal(summary.projectionOmitted, true);
		assert.equal(summary.toolCallCount, oversizedCalls.length);
		assert.equal(summary.ts, safeTimestampPrefix);
		assert.equal(summary.tsTruncated, true);
		assert.equal(first.nextOffset, 1);
		assert.ok(first.nextOffset! > first.offsetEnd, "page continuation must advance past the summarized row");
		assert.deepEqual(first.continuationRequest, { kind: "page", offset: 1 });

		const second = await readTranscript({ offset: first.nextOffset, limit: 1, includeToolResults: false }, options);
		assert.ok(Buffer.byteLength(JSON.stringify(second), "utf8") <= 512);
		assert.equal(second.returned, 1);
		assert.equal(second.offsetStart, 1);
		assert.equal(second.offsetEnd, 1);
		assert.equal(second.nextOffset, undefined);
		const normal = second.messages[0] as any;
		assert.equal(normal.projectionOmitted, undefined);
		assert.equal(normal.text, "next row");
		assert.equal(normal.ts, safeTimestampPrefix);
		assert.equal(normal.tsTruncated, true);
	});

	it("omits invalid timestamp scalars only from the agent projection", async () => {
		const invalidTimestamp = "\ud800";
		const text = JSON.stringify({
			type: "message",
			ts: invalidTimestamp,
			message: { role: "assistant", content: "answer" },
		}) + "\n";

		const agent = await readTranscript({ limit: 1 }, {
			...memoryTranscript(text),
			projection: "agent",
			sessionId: "invalid-timestamp",
		});
		assert.equal((agent.messages[0] as any).ts, null);
		assert.equal((agent.messages[0] as any).tsInvalid, true);

		const legacy = await readTranscript({ limit: 1 }, memoryTranscript(text));
		assert.equal((legacy.messages[0] as any).ts, invalidTimestamp);
		assert.equal((legacy.messages[0] as any).tsInvalid, undefined);
	});

	it("keeps a huge-timestamp result slice canonical, bounded, and progressing", async () => {
		const body = "slice-body-".repeat(4096);
		const text = JSON.stringify({
			type: "message",
			ts: oversizedTimestamp,
			message: {
				role: "toolResult",
				toolCallId: "call-result",
				name: "read",
				status: "ok",
				content: body,
			},
		}) + "\n";
		const options = {
			...memoryTranscript(text),
			projection: "agent" as const,
			sessionId: "timestamp-result-slice",
			serializedBudgetBytes: 1200,
		};
		const page = await readTranscript({ limit: 1, includeToolResults: false }, options);
		const metadata = (page.messages[0] as any).toolResults[0];

		const first = await readTranscript({
			resultHandle: metadata.handle,
			resultCursor: 0,
			resultLimit: 8192,
		}, options);
		assert.ok(Buffer.byteLength(JSON.stringify(first), "utf8") <= 1200);
		assert.ok(Buffer.byteLength(JSON.stringify(first), "utf8") <= READ_SESSION_AGENT_ENVELOPE_MAX_BYTES);
		const firstRow = first.messages[0] as any;
		const firstResult = firstRow.toolResults[0];
		assert.equal(firstRow.ts, safeTimestampPrefix);
		assert.equal(firstRow.tsTruncated, true);
		assert.equal(firstResult.name, "read");
		assert.equal(firstResult.status, "ok");
		assert.deepEqual(firstResult.size, metadata.size);
		assert.equal(firstResult.handle, metadata.handle);
		assert.equal(firstResult.omitted, false);
		assert.equal(firstResult.excerpt.start, 0);
		assert.ok(firstResult.excerpt.end > firstResult.excerpt.start);
		assert.equal(firstResult.excerpt.nextCursor, firstResult.excerpt.end);
		assert.equal(firstResult.excerpt.complete, false);
		assert.equal(first.partial, true);
		assert.equal(first.truncatedBy, "transport_budget");
		assert.deepEqual(first.continuationRequest, {
			kind: "result_slice",
			result_handle: metadata.handle,
			result_cursor: firstResult.excerpt.end,
			result_limit: 8192,
		});

		const second = await readTranscript({
			resultHandle: metadata.handle,
			resultCursor: firstResult.excerpt.nextCursor,
			resultLimit: 8192,
		}, options);
		assert.ok(Buffer.byteLength(JSON.stringify(second), "utf8") <= 1200);
		const secondResult = (second.messages[0] as any).toolResults[0];
		assert.equal(secondResult.name, firstResult.name);
		assert.equal(secondResult.status, firstResult.status);
		assert.deepEqual(secondResult.size, firstResult.size);
		assert.equal(secondResult.handle, firstResult.handle);
		assert.equal(secondResult.excerpt.start, firstResult.excerpt.nextCursor);
		assert.ok(secondResult.excerpt.end > secondResult.excerpt.start, "slice continuation must advance");
		assert.equal(
			firstResult.excerpt.text + secondResult.excerpt.text,
			body.slice(0, secondResult.excerpt.end),
			"continued slices must be exact and non-overlapping",
		);
	});
});

describe("transcript-reader / pre-compaction authors", () => {
	it("adds the same inferred author to the verbose envelope and renderable message", async () => {
		const text = [
			{ type: "message", id: "old-user", message: { role: "user", content: "before" } },
			{ type: "message", id: "old-agent", message: { role: "assistant", content: "answer" } },
			{ type: "message", id: "first-kept", message: { role: "user", content: "after" } },
		].map((entry) => JSON.stringify(entry)).join("\n") + "\n";
		const env = await readOrphanedBeforeCompaction(
			{ compactionId: "compaction-1", verbose: true },
			{
				...memoryTranscript(text),
				firstKeptEntryId: "first-kept",
				authorContext: { session: { id: "target", title: "Target" } },
			},
		);
		const assistant = env.messages[1] as any;
		assert.deepEqual(assistant.author, { kind: "agent", id: "session:target", label: "Target" });
		assert.deepEqual(assistant.message.author, assistant.author);
	});
});
