// AUTO-GENERATED by scripts/testing-v2/codemod.mjs — do not edit the legacy source.
// Source: tests/worktree-inventory.test.ts
// Bucket: v2-core | Method: codemod | Classification: clean

import { describe, it } from "vitest";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { WorktreeInventoryService, classifyPoolReclaimCandidate, isContainerInternalWorktreePath } from "../../src/server/agent/worktree-inventory.ts";

function makeCtx(rootPath: string, opts?: { worktreeRoot?: string; liveSessions?: any[]; archivedSessions?: any[]; goals?: any[]; teams?: any[]; staff?: any[]; components?: any[] }) {
	return {
		project: { id: "p1", name: "Project", rootPath },
		projectConfigStore: {
			get: (key: string) => key === "worktree_root" ? opts?.worktreeRoot : undefined,
			getComponents: () => opts?.components ?? [],
		},
		sessionStore: { getLive: () => opts?.liveSessions ?? [], getArchived: () => opts?.archivedSessions ?? [], get: (id: string) => [...(opts?.liveSessions ?? []), ...(opts?.archivedSessions ?? [])].find(s => s.id === id) },
		goalStore: { getAll: () => opts?.goals ?? [] },
		teamStore: { getAll: () => opts?.teams ?? [] },
		staffStore: { getAll: () => opts?.staff ?? [] },
	};
}

function makeService(ctx: any, porcelain: string | ((repoPath: string, args: readonly string[]) => string), pools = new Map()) {
	return new WorktreeInventoryService({
		projectContextManager: { visible: function* () { yield ctx; }, all: function* () { yield ctx; } } as any,
		sessionManager: {
			listSessions: () => [],
			getAllWorktreePools: () => pools,
			listArchivedSessionWorktrees: async () => { throw new Error("inventory must not use legacy archived scanner"); },
		} as any,
		execGit: async (repoPath, args) => args[0] === "worktree" ? (typeof porcelain === "function" ? porcelain(repoPath, args) : porcelain) : "",
		clock: () => 1,
	});
}

function tmpProject() {
	const root = fs.mkdtempSync(path.join(os.tmpdir(), "wt-inventory-"));
	const repo = path.join(root, "repo");
	fs.mkdirSync(path.join(repo, ".git"), { recursive: true });
	return { root, repo };
}

describe("worktree inventory classifier", () => {
	it("protects a live referenced worktree", async () => {
		const { root, repo } = tmpProject();
		try {
			const wt = path.join(root, "repo-wt", "session-live");
			fs.mkdirSync(wt, { recursive: true });
			const ctx = makeCtx(repo, { liveSessions: [{ id: "s1", title: "Live", cwd: wt, worktreePath: wt, repoPath: repo, branch: "session/live" }] });
			const service = makeService(ctx, `worktree ${repo}\nbranch refs/heads/master\n\nworktree ${wt}\nbranch refs/heads/session/live\n`);
			const report = await service.scan();
			const item = report.items.find(i => i.path === wt)!;
			assert.equal(item.classification, "protected-in-use");
			assert.equal(item.reason, "referenced-by-live-session");
			assert.equal(item.actionable, false);
		} finally { fs.rmSync(root, { recursive: true, force: true }); }
	});

	it("maps archived-session owned git worktrees to ready cleanup rows", async () => {
		const { root, repo } = tmpProject();
		try {
			const wt = path.join(root, "repo-wt", "session-arch");
			fs.mkdirSync(wt, { recursive: true });
			const archived = { id: "a1", title: "Archived", projectId: "p1", repoPath: repo, worktreePath: wt, branch: "session/arch", archived: true };
			const service = makeService(makeCtx(repo, { archivedSessions: [archived] }), `worktree ${repo}\nbranch refs/heads/master\n\nworktree ${wt}\nbranch refs/heads/session/arch\n`);
			const report = await service.scan();
			const item = report.items.find(i => i.legacy?.archivedSession?.sessionId === "a1")!;
			assert.equal(item.classification, "archived-owned");
			assert.equal(item.disposition, "ready-to-clean");
			assert.equal(item.defaultSelected, true);
		} finally { fs.rmSync(root, { recursive: true, force: true }); }
	});

	it("scans archived session repo paths even when they are outside configured project repos", async () => {
		const { root, repo } = tmpProject();
		try {
			const archivedRepo = path.join(root, "archived-repo");
			fs.mkdirSync(path.join(archivedRepo, ".git"), { recursive: true });
			const wt = path.join(root, "archived-repo-wt", "session-arch");
			fs.mkdirSync(wt, { recursive: true });
			const archived = { id: "a1", title: "Archived", projectId: "p1", repoPath: archivedRepo, worktreePath: wt, branch: "session/arch", archived: true };
			const service = makeService(makeCtx(repo, { archivedSessions: [archived] }), (repoPath) => repoPath === archivedRepo ? `worktree ${archivedRepo}\nbranch refs/heads/master\n\nworktree ${wt}\nbranch refs/heads/session/arch\n` : `worktree ${repo}\nbranch refs/heads/master\n`);
			const report = await service.scan();
			const item = report.items.find(i => i.legacy?.archivedSession?.sessionId === "a1")!;
			assert.equal(item.repoPath, archivedRepo);
			assert.equal(item.gitWorktreeMetadataExists, true);
			assert.equal(item.classification, "archived-owned");
			assert.equal(item.actionable, true);
			const legacy = await service.legacyArchivedSessionWorktrees();
			assert.equal(legacy.items.find(candidate => candidate.sessionId === "a1")?.status, "removable");
		} finally { fs.rmSync(root, { recursive: true, force: true }); }
	});

	it("keeps already-cleaned archived rows non-destructive even when the branch still exists", async () => {
		const { root, repo } = tmpProject();
		try {
			const missingWt = path.join(root, "repo-wt", "missing-session-arch");
			const archived = { id: "a1", title: "Archived", projectId: "p1", repoPath: repo, worktreePath: missingWt, branch: "session/arch", archived: true };
			const service = makeService(makeCtx(repo, { archivedSessions: [archived] }), `worktree ${repo}\nbranch refs/heads/master\n`);
			const report = await service.scan();
			const item = report.items.find(i => i.legacy?.archivedSession?.sessionId === "a1")!;
			assert.equal(item.classification, "already-cleaned");
			assert.equal(item.willDeleteBranch, false);
			const legacy = await service.legacyArchivedSessionWorktrees(true);
			assert.equal(legacy.items.find(candidate => candidate.sessionId === "a1")?.willDeleteBranch, false);
		} finally { fs.rmSync(root, { recursive: true, force: true }); }
	});

	it("preserves archived delegate shared-worktree disposition through the legacy adapter", async () => {
		const { root, repo } = tmpProject();
		try {
			const wt = path.join(root, "repo-wt", "delegate-shared");
			const archived = { id: "delegate1", title: "Archived delegate", projectId: "p1", repoPath: repo, worktreePath: wt, delegateOf: "parent", archived: true };
			const service = makeService(makeCtx(repo, { archivedSessions: [archived] }), `worktree ${repo}\nbranch refs/heads/master\n`);
			const report = await service.scan();
			const inventoryItem = report.items.find(candidate => candidate.legacy?.archivedSession?.sessionId === "delegate1")!;
			assert.equal(inventoryItem.classification, "protected-in-use");
			assert.equal(inventoryItem.reason, "delegate-shared-worktree");
			const legacy = await service.legacyArchivedSessionWorktrees(true);
			const item = legacy.items.find(candidate => candidate.sessionId === "delegate1")!;
			assert.equal(item.status, "skipped");
			assert.equal(item.reason, "delegate-shared-worktree");
			assert.equal(item.disposition, "ineligible");
			assert.equal(item.reasonCategory, "shared-delegate");
			assert.equal(item.actionable, false);
		} finally { fs.rmSync(root, { recursive: true, force: true }); }
	});

	it("keeps archived worktree cleanup actionable while blocking branch deletion for live references", async () => {
		const { root, repo } = tmpProject();
		try {
			const wt = path.join(root, "repo-wt", "session-arch-shared-branch");
			fs.mkdirSync(wt, { recursive: true });
			const archived = { id: "a1", title: "Archived", projectId: "p1", repoPath: repo, worktreePath: wt, branch: "session/shared", archived: true };
			const live = { id: "live", title: "Live", cwd: repo, repoPath: repo, branch: "session/shared" };
			const service = makeService(makeCtx(repo, { liveSessions: [live], archivedSessions: [archived] }), `worktree ${repo}\nbranch refs/heads/master\n\nworktree ${wt}\nbranch refs/heads/session/shared\n`);
			const report = await service.scan();
			const item = report.items.find(candidate => candidate.legacy?.archivedSession?.sessionId === "a1")!;
			assert.equal(item.classification, "archived-owned");
			assert.equal(item.actionable, true);
			assert.equal(item.willDeleteBranch, false);
			assert.equal(item.branchDeleteBlockedReason, "branch-referenced-by-live-record");
		} finally { fs.rmSync(root, { recursive: true, force: true }); }
	});

	it("reports unowned session git worktrees through the legacy adapter", async () => {
		const { root, repo } = tmpProject();
		try {
			const wt = path.join(root, "repo-wt", "session-orphan");
			fs.mkdirSync(wt, { recursive: true });
			const service = makeService(makeCtx(repo), `worktree ${repo}\nbranch refs/heads/master\n\nworktree ${wt}\nbranch refs/heads/session/orphan\n`);
			const legacy = await service.legacyOrphanedWorktrees();
			assert.deepEqual(legacy.worktrees, [{ path: wt, branch: "session/orphan", repoPath: repo }]);
		} finally { fs.rmSync(root, { recursive: true, force: true }); }
	});

	it("honors configured worktree_root and keeps filesystem-only directories non-actionable", async () => {
		const { root, repo } = tmpProject();
		try {
			const stale = path.join(repo, ".custom-wt", "session-stale");
			fs.mkdirSync(stale, { recursive: true });
			const service = makeService(makeCtx(repo, { worktreeRoot: ".custom-wt" }), `worktree ${repo}\nbranch refs/heads/master\n`);
			const report = await service.scan();
			const item = report.items.find(i => i.path === stale)!;
			assert.equal(item.classification, "stale-filesystem-only");
			assert.equal(item.actionable, false);
		} finally { fs.rmSync(root, { recursive: true, force: true }); }
	});

	it("scans the actual git root for nested single-repo projects", async () => {
		const { root, repo } = tmpProject();
		try {
			const nestedProjectRoot = path.join(repo, "packages", "app");
			fs.mkdirSync(nestedProjectRoot, { recursive: true });
			const wt = path.join(root, "repo-wt", "session-nested");
			fs.mkdirSync(wt, { recursive: true });
			const service = makeService(makeCtx(nestedProjectRoot), (repoPath) => {
				assert.equal(repoPath, repo);
				return `worktree ${repo}\nbranch refs/heads/master\n\nworktree ${wt}\nbranch refs/heads/session/nested\n`;
			});
			const report = await service.scan();
			const item = report.items.find(i => i.path === wt)!;
			assert.equal(item.repoPath, repo);
			assert.equal(item.worktreeRoot, path.join(root, "repo-wt"));
			assert.equal(item.classification, "unowned-git-worktree");
		} finally { fs.rmSync(root, { recursive: true, force: true }); }
	});

	it("protects durable multi-repo team-agent component worktrees", async () => {
		const { root, repo } = tmpProject();
		try {
			const apiRepo = path.join(repo, "api");
			const webRepo = path.join(repo, "web");
			fs.mkdirSync(path.join(apiRepo, ".git"), { recursive: true });
			fs.mkdirSync(path.join(webRepo, ".git"), { recursive: true });
			const container = path.join(root, "repo-wt", "session-team-agent");
			const apiWt = path.join(container, "api");
			fs.mkdirSync(apiWt, { recursive: true });
			const components = [{ name: "api", repo: "api" }, { name: "web", repo: "web" }];
			const teams = [{ id: "team1", agents: [{ sessionId: "agent1", branch: "session/team-agent", worktreePath: container }] }];
			const service = makeService(makeCtx(repo, { components, teams }), (repoPath) => repoPath === apiRepo
				? `worktree ${apiRepo}\nbranch refs/heads/master\n\nworktree ${apiWt}\nbranch refs/heads/session/team-agent\n`
				: `worktree ${repoPath}\nbranch refs/heads/master\n`);
			const report = await service.scan();
			const item = report.items.find(i => i.path === apiWt)!;
			assert.equal(item.classification, "protected-in-use");
			assert.equal(item.reason, "referenced-by-live-team");
			assert.equal(item.actionable, false);
		} finally { fs.rmSync(root, { recursive: true, force: true }); }
	});

	it("keeps pool candidates diagnostic and guards container paths", async () => {
		assert.equal(isContainerInternalWorktreePath("/workspace-wt/session-x"), true);
		const verdict = classifyPoolReclaimCandidate({ resolvedWorktreeRoot: "/tmp/repo-wt", candidatePath: "/tmp/repo-wt/pool-_pool-a", branch: "pool/_pool-a", gitMetadataExists: true });
		assert.equal(verdict.eligible, true);
		const active = classifyPoolReclaimCandidate({ resolvedWorktreeRoot: "/tmp/repo-wt", candidatePath: "/tmp/repo-wt/pool-_pool-a", branch: "pool/_pool-a", gitMetadataExists: true, activeWorktreePaths: new Set(["/tmp/repo-wt/pool-_pool-a"]) });
		assert.equal(active.eligible, false);
		assert.equal(active.reason, "referenced-by-live-session");

		const { root, repo } = tmpProject();
		try {
			const wt = path.join(root, "repo-wt", "pool-_pool-a");
			fs.mkdirSync(wt, { recursive: true });
			const pools = new Map([["p1", { snapshotEntries: () => ({ entries: [{ branchName: "pool/_pool-a", worktreePath: wt, createdAt: 1 }], target: 1, filling: false }) }]]);
			const service = makeService(makeCtx(repo), `worktree ${repo}\nbranch refs/heads/master\n\nworktree ${wt}\nbranch refs/heads/pool/_pool-a\n`, pools);
			const report = await service.scan();
			const item = report.items.find(i => i.path === wt)!;
			assert.equal(item.classification, "pool-entry");
			assert.equal(item.defaultSelected, false);
			assert.equal(report.counts.poolEntries, 1);
		} finally { fs.rmSync(root, { recursive: true, force: true }); }
	});

	it("classifies multi-repo pool entries as pool-entry instead of branch-referenced live records", async () => {
		const { root, repo } = tmpProject();
		try {
			const apiRepo = path.join(repo, "packages", "api");
			fs.mkdirSync(path.join(apiRepo, ".git"), { recursive: true });
			const container = path.join(root, "repo-wt", "pool-_pool-multi");
			const apiWt = path.join(container, "packages", "api");
			fs.mkdirSync(apiWt, { recursive: true });
			const components = [{ name: "api", repo: "packages/api" }];
			const pools = new Map([["p1", { snapshotEntries: () => ({ entries: [{ branchName: "pool/_pool-multi", worktreePath: container, worktrees: [{ repo: "packages/api", repoPath: apiRepo, worktreePath: apiWt }], createdAt: 1 }], target: 1, filling: false }) }]]);
			const service = makeService(makeCtx(repo, { components }), `worktree ${apiRepo}\nbranch refs/heads/master\n\nworktree ${apiWt}\nbranch refs/heads/pool/_pool-multi\n`, pools);
			const report = await service.scan();
			const item = report.items.find(i => i.path === apiWt)!;
			assert.equal(item.classification, "pool-entry");
			assert.equal(item.reason, "safe-pool-entry");
			assert.equal(item.defaultSelected, false);
			assert.equal(report.counts.poolEntries, 1);
		} finally { fs.rmSync(root, { recursive: true, force: true }); }
	});
});
