// AUTO-GENERATED by scripts/testing-v2/codemod.mjs — do not edit the legacy source.
// Source: tests/model-state-meta-resolver.test.ts
// Bucket: v2-core | Method: codemod | Classification: clean

/**
 * Unit tests for the exact metadata boundary used by live model-state frames.
 * The resolver may return only an assembled registry row, an exact direct Pi
 * row, or an explicit unavailable result with no fabricated capabilities.
 */
import { describe, it } from "vitest";
import assert from "node:assert/strict";
import path from "node:path";
import { createMemFs } from "../../../tests2/harness/mem-fs.js";

const memfs = createMemFs();
const stateDir = path.resolve("/memfs/model-meta-resolver");

const { PreferencesStore } = await import("../../../src/server/agent/preferences-store.ts");
const {
	getAvailableModels,
	invalidateModelCache,
	resolveAuthoritativeModelCapacity,
	resolveModelStateMeta,
} = await import("../../../src/server/agent/model-registry.ts");

const prefs = new PreferencesStore(stateDir, memfs);

const AUTHORITATIVE_CAPACITY_ROWS = [
	["openai", "gpt-5.4"],
	["openai", "gpt-5.5"],
	["openai", "gpt-5.6-luna"],
	["openai", "gpt-5.6-sol"],
	["openai", "gpt-5.6-terra"],
	["openai-codex", "gpt-5.6-luna"],
	["openai-codex", "gpt-5.6-sol"],
	["openai-codex", "gpt-5.6-terra"],
] as const;

describe("resolveModelStateMeta", () => {
	it("returns the exact assembled cache row", async () => {
		invalidateModelCache();
		const models = await getAvailableModels(prefs);
		const row = models.find(m => m.provider === "anthropic" && m.id === "claude-opus-4-5");
		assert.ok(row);

		assert.deepEqual(resolveModelStateMeta(row.provider, row.id), {
			contextWindow: row.contextWindow,
			...(row.modelCapacity !== undefined ? { modelCapacity: row.modelCapacity } : {}),
			maxTokens: row.maxTokens,
			reasoning: row.reasoning,
			...(row.thinkingLevelMap ? { thinkingLevelMap: row.thinkingLevelMap } : {}),
			input: row.input,
			source: "cache",
		});
	});

	it("returns exact composed custom metadata from the cache", async () => {
		try {
			prefs.set("customProviders", [{
				id: "private",
				name: "Private Provider",
				type: "manual",
				baseUrl: "http://127.0.0.1:9999",
				models: [{ id: "model-o1-lookalike", name: "Private Exact Model" }],
			}]);
			invalidateModelCache();
			const models = await getAvailableModels(prefs);
			const row = models.find(m => m.provider === "Private Provider" && m.id === "model-o1-lookalike");
			assert.ok(row);
			const meta = resolveModelStateMeta(row.provider, row.id);
			assert.deepEqual(meta, {
				contextWindow: row.contextWindow,
				maxTokens: row.maxTokens,
				reasoning: row.reasoning,
				input: row.input,
				source: "cache",
			});
		} finally {
			prefs.remove("customProviders");
			invalidateModelCache();
		}
	});

	it("returns the exact direct Pi row when the cache is empty", () => {
		invalidateModelCache();
		assert.deepEqual(resolveModelStateMeta("anthropic", "claude-opus-4-5"), {
			contextWindow: 200_000,
			maxTokens: 64_000,
			reasoning: true,
			input: ["text", "image"],
			source: "catalog",
		});
	});

	it("enriches all and only the reviewed exact built-in rows without changing the target", async () => {
		invalidateModelCache();
		const models = await getAvailableModels(prefs);

		for (const [provider, id] of AUTHORITATIVE_CAPACITY_ROWS) {
			const row = models.find((model) => model.provider === provider && model.id === id);
			assert.ok(row, `expected built-in ${provider}/${id}`);
			assert.equal(row.contextWindow, 272_000, `${provider}/${id} must keep the Pi compaction target`);
			assert.equal(row.modelCapacity, 1_050_000, `${provider}/${id} capacity`);

			const cached = resolveModelStateMeta(provider, id);
			assert.equal(cached.source, "cache");
			assert.equal(cached.contextWindow, 272_000);
			assert.equal(cached.modelCapacity, 1_050_000);
		}
		assert.deepEqual(
			models
				.filter((model) => model.modelCapacity !== undefined)
				.map((model) => `${model.provider}/${model.id}`)
				.sort(),
			AUTHORITATIVE_CAPACITY_ROWS.map(([provider, id]) => `${provider}/${id}`).sort(),
			"no unreviewed built-in row may gain capacity",
		);

		invalidateModelCache();
		for (const [provider, id] of AUTHORITATIVE_CAPACITY_ROWS) {
			const direct = resolveModelStateMeta(provider, id);
			assert.equal(direct.source, "catalog", `${provider}/${id} direct fallback`);
			assert.equal(direct.contextWindow, 272_000);
			assert.equal(direct.modelCapacity, 1_050_000);
		}
	});

	it("fails closed for target drift, aliases, snapshots, and family lookalikes", () => {
		const omissions = [
			["openai", "gpt-5.4", 271_999, "target drift"],
			["openai-codex", "gpt-5.4", 272_000, "unreviewed Codex generation"],
			["openai-codex", "gpt-5.5", 272_000, "unreviewed Codex generation"],
			["aigw", "gpt-5.6-sol", 272_000, "AIGW route alias"],
			["custom", "gpt-5.6-sol", 272_000, "custom provider alias"],
			["OpenAI", "gpt-5.6-sol", 272_000, "provider case mismatch"],
			["openai", "gpt-5.4-2026-08-22", 272_000, "snapshot"],
			["openai", "gpt-5.6-sol-extra", 272_000, "family lookalike"],
		] as const;

		for (const [provider, id, target, description] of omissions) {
			assert.equal(
				resolveAuthoritativeModelCapacity(provider, id, target),
				undefined,
				description,
			);
		}
	});

	it("does not attach capacity to non-authoritative resolver fallbacks", () => {
		for (const [provider, id] of [
			["openai-codex", "gpt-5.4"],
			["aigw", "gpt-5.6-sol"],
			["openrouter", "openai/gpt-5.6-sol"],
			["openai", "gpt-5.6-sol-extra"],
		] as const) {
			invalidateModelCache();
			assert.equal("modelCapacity" in resolveModelStateMeta(provider, id), false, `${provider}/${id}`);
		}
	});

	it("returns unavailable without fabricated family metadata", () => {
		for (const provider of ["custom", "aigw", "", undefined]) {
			invalidateModelCache();
			assert.deepEqual(
				resolveModelStateMeta(provider, "totally-unknown-o1-claude-model"),
				{ source: "unavailable" },
			);
		}
	});
});
