// AUTO-GENERATED by scripts/testing-v2/codemod.mjs — do not edit the legacy source.
// Source: tests/reviewer-resume-shutdown-state.test.ts
// Bucket: v2-core | Method: codemod | Classification: clean

import { test } from "vitest";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { SessionManager, sessionNeedsRestartRedrive } from "../../../src/server/agent/session-manager.ts";

function sessionManagerSource(): string {
	return fs.readFileSync(path.join(process.cwd(), "src/server/agent/session-manager.ts"), "utf-8");
}

function shutdownBody(source: string): string {
	const start = source.indexOf("\tasync shutdown(): Promise<void> {");
	assert.notEqual(start, -1, "precondition: SessionManager.shutdown() must exist");
	const end = source.indexOf("\n// ── Sandbox credential auto-resolution", start);
	assert.notEqual(end, -1, "precondition: SessionManager.shutdown() section must be bounded before sandbox credential code");
	return source.slice(start, end);
}

function makeShutdownSession(id: string, status: any, extra: Record<string, unknown> = {}) {
	return {
		id,
		title: id,
		status,
		streamingStartedAt: undefined,
		clients: new Set<any>(),
		rpcClient: { stop: async () => {} },
		unsubscribe: () => {},
		promptQueue: { length: 0 },
		...extra,
	};
}

test("restart re-drive predicate covers busy states but not idle/terminal states", () => {
	assert.equal(sessionNeedsRestartRedrive("idle"), false);
	assert.equal(sessionNeedsRestartRedrive("terminated"), false);
	assert.equal(sessionNeedsRestartRedrive("streaming"), true);
	assert.equal(sessionNeedsRestartRedrive("preparing"), true);
	assert.equal(sessionNeedsRestartRedrive("aborting"), true);
	assert.equal(sessionNeedsRestartRedrive("starting"), true, "fresh active startup should still be redriven");
});

test("restore-startup starting uses the persisted interrupted-turn bit", () => {
	assert.equal(
		sessionNeedsRestartRedrive({ status: "starting", restoreStartupWasStreaming: false }),
		false,
		"rapid shutdown during cold restore of a previously idle session must not create a false boot re-prompt",
	);
	assert.equal(
		sessionNeedsRestartRedrive({ status: "starting", restoreStartupWasStreaming: true }),
		true,
		"rapid shutdown during cold restore of a truly interrupted session must preserve re-drive",
	);
});

test("shutdown persists re-drive state from session lifecycle state", async () => {
	const updates: Record<string, any> = {};
	const manager: any = new SessionManager();
	manager._testStore = {
		update: (id: string, update: any) => { updates[id] = update; },
		get: () => undefined,
		flush: () => {},
	};
	manager.closeExtensionChannelsForSession = async () => {};
	manager.cancelPendingAutoRetry = () => {};
	manager._untrackConnectedSession = () => {};

	manager.sessions.set("restored-idle", makeShutdownSession("restored-idle", "starting", { restoreStartupWasStreaming: false }));
	manager.sessions.set("restored-active", makeShutdownSession("restored-active", "starting", { restoreStartupWasStreaming: true }));
	manager.sessions.set("fresh-starting", makeShutdownSession("fresh-starting", "starting"));
	manager.sessions.set("preparing", makeShutdownSession("preparing", "preparing"));
	manager.sessions.set("idle", makeShutdownSession("idle", "idle"));

	await manager.shutdown();

	assert.equal(updates["restored-idle"].wasStreaming, false);
	assert.equal(updates["restored-idle"].streamingStartedAt, undefined);
	assert.equal(updates["restored-active"].wasStreaming, true);
	assert.equal(typeof updates["restored-active"].streamingStartedAt, "number");
	assert.equal(updates["fresh-starting"].wasStreaming, true);
	assert.equal(updates.preparing.wasStreaming, true);
	assert.equal(updates.idle.wasStreaming, false);
});

test("shutdown releases sessions whose project context was removed without recreating a store", async () => {
	let getOrCreateCalls = 0;
	let stopCalls = 0;
	let closeCalls = 0;
	const unrelatedStore = {
		get: () => undefined,
		update: () => assert.fail("shutdown must not write a removed project's session into another project store"),
		flush: () => {},
	};
	const manager: any = new SessionManager({
		projectContextManager: {
			all: () => [{
				project: { id: "surviving-project" },
				sessionStore: unrelatedStore,
				costTracker: { flush: () => {} },
			}],
			getOrCreate: () => {
				getOrCreateCalls++;
				throw new Error("removed project context must not be recreated during shutdown");
			},
		} as any,
	});
	const client = { close: () => { closeCalls++; } };
	const session = makeShutdownSession("removed-project-session", "streaming", {
		projectId: "removed-project",
		clients: new Set([client]),
		rpcClient: { stop: async () => { stopCalls++; } },
	});
	manager.sessions.set(session.id, session);

	await manager.shutdown();

	assert.equal(getOrCreateCalls, 0, "shutdown must not lazily recreate a removed project context");
	assert.equal(stopCalls, 1, "the orphaned runtime must still stop");
	assert.equal(closeCalls, 1, "attached clients must still close");
	assert.equal(manager.sessions.has(session.id), false, "the orphaned session must be released");
});

test("shutdown uses the centralized restart re-drive predicate, not exact streaming", () => {
	const source = sessionManagerSource();
	const body = shutdownBody(source);

	assert.match(
		body,
		/wasStreaming:\s*needsRestartRedrive\s*[,}]/,
		"shutdown must persist the centralized restart re-drive predicate into the legacy wasStreaming field.",
	);
	assert.doesNotMatch(
		body,
		/wasStreaming:\s*session\.status\s*===\s*["']streaming["']\s*[,}]/,
		"SessionManager.shutdown() must mark active/busy reviewer statuses as interrupted for restart re-drive, not only status === \"streaming\".",
	);
});
