// AUTO-GENERATED by scripts/testing-v2/codemod.mjs — do not edit the legacy source.
// Source: tests/seed-default-workflows.test.ts
// Bucket: v2-core | Method: codemod | Classification: clean

import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { describe, it } from "vitest";
import YAML from "yaml";

import { buildDefaultWorkflows, RALPH_LOOP_DESCRIPTION } from "../../../src/server/state-migration/seed-default-workflows.ts";

type VerifyStep = {
	name: string;
	type: string;
	role?: string;
	phase?: number;
	command?: string;
	run?: string;
	expect?: string;
	optional?: boolean;
	prompt?: string;
	timeout?: number;
	failureGuidance?: string;
};

type Workflow = {
	id: string;
	gates: Array<{ id: string; description?: string; depends_on?: string[]; verify?: VerifyStep[] }>;
};

// Keep the test focused on the persisted workflow behavior rather than the
// helper's exported TypeScript declaration. The server and per-component
// derivation are the public consumers of this capability argument.
type CapabilityAwareDefaultBuilder = (
	componentName: string,
	supportedCommands?: Iterable<string>,
) => Record<string, Workflow>;
const buildCapabilityAwareDefaults = buildDefaultWorkflows as CapabilityAwareDefaultBuilder;

const IMPLEMENTATION_WORKFLOW_IDS = ["general", "feature", "bug-fix", "quick-fix"] as const;
const EXPECTED_REVIEWS = [
	{ name: "Spec and regression conformance", role: "spec-auditor" },
	{ name: "Integrated implementation review", role: "code-reviewer" },
	{ name: "Security review", role: "security-reviewer" },
];
type ImplementationPhasePolicy = {
	commands: Record<"check" | "unit" | "browser" | "e2e", number>;
	reviews: number;
	qa: number;
};
const DEFAULT_IMPLEMENTATION_PHASES: ImplementationPhasePolicy = {
	commands: { check: 1, unit: 1, browser: 1, e2e: 1 },
	reviews: 2,
	qa: 3,
};
const PROJECT_IMPLEMENTATION_PHASES: ImplementationPhasePolicy = {
	commands: { check: 1, unit: 1, browser: 2, e2e: 3 },
	reviews: 3,
	qa: 4,
};
const SUPERSEDED_REVIEW_NAMES = [
	/code quality/i,
	/bug hunt/i,
	/verifiable bug hunt/i,
	/systems (?:interaction )?review/i,
	/regression coverage/i,
];
const SUPERSEDED_REVIEW_ROLES = new Set(["bug-hunter", "verifiable-bug-hunter", "systems-reviewer", "regression-reviewer"]);

function findGate(workflow: Workflow, id: string) {
	const gate = workflow.gates.find((candidate) => candidate.id === id);
	assert.ok(gate, `gate ${id} should exist in workflow ${workflow.id}`);
	return gate;
}

function assertRevisionReadyContentReviewPrompt(prompt: string, source: string): void {
	const policy = prompt.replace(/\s+/g, " ");
	const message = `${source} must turn each blocking content finding into an author-ready revision packet`;

	// Keep these assertions intentionally order-independent: the workflow prose may
	// present the packet fields in a different sequence without weakening policy.
	assert.match(policy, /(?:revision|author)[ -]ready/i, message);
	assert.match(policy, /block(?:ing|er)/i, message);
	assert.match(policy, /(?:artifact )?(?:section|heading|paragraph|requirement|acceptance criterion|diagram|test plan)/i, message);
	assert.match(policy, /(?:goal[- ]linked|goal (?:requirement|scope)|gap|contradiction)/i, message);
	assert.match(policy, /(?:implementation|user) consequence/i, message);
	assert.match(policy, /(?:replacement|addition|wording|outline|contract|data[- ]flow|state sequence|acceptance criterion|test[- ]plan case)/i, message);
	assert.match(policy, /(?:cross[- ]section|consistency)/i, message);
	assert.match(policy, /(?:constraints?|references?)/i, message);
	assert.match(policy, /(?:credible|multiple).{0,160}alternatives?|alternatives?.{0,160}(?:credible|multiple)/i, message);
	assert.match(policy, /trade-?offs?/i, message);
	assert.match(policy, /(?:required|blocker)/i, message);
	assert.match(policy, /(?:optional|bounded improvement)/i, message);
}

function assertDesignOrAnalysisReviewPrompt(prompt: string, source: string): void {
	assertRevisionReadyContentReviewPrompt(prompt, source);
	const policy = prompt.replace(/\s+/g, " ");
	assert.match(policy, /implementable contracts?/i, `${source} must provide implementable contracts`);
	assert.match(policy, /testable acceptance criteria/i, `${source} must provide testable acceptance criteria`);
	assert.match(policy, /(?:do not|must not|not).{0,160}(?:exhaustive pseudocode|formal proof|speculative hardening)/i, `${source} must keep revisions proportionate to the approved goal`);
}

function assertDocumentationReviewPrompt(prompt: string, source: string): void {
	assertRevisionReadyContentReviewPrompt(prompt, source);
	const policy = prompt.replace(/\s+/g, " ");
	assert.match(policy, /documentation (?:path|file|location)/i, `${source} must identify the documentation location to revise`);
	assert.match(policy, /(?:section|heading)/i, `${source} must identify the documentation section to revise`);
	assert.match(policy, /(?:stale|missing) (?:claim|documentation|content)|(?:claim|documentation|content).{0,80}(?:stale|missing)/i, `${source} must identify the stale or missing claim`);
	assert.match(policy, /(?:replacement wording|proposed wording|replacement outline|proposed outline)/i, `${source} must propose concrete documentation text or outline`);
	assert.match(policy, /examples?/i, `${source} must include relevant examples when needed`);
	assert.match(policy, /links?/i, `${source} must include relevant links when needed`);
	assert.match(policy, /(?:verify|verification).{0,160}(?:documented behavior|documentation).{0,160}(?:implementation|implemented)|(?:implementation|implemented).{0,160}(?:verify|verification).{0,160}(?:documented behavior|documentation)/i, `${source} must explain how to verify documentation matches implementation`);
}

function assertDownstreamDocumentationStageScope(workflows: Record<string, Workflow>, source: string): void {
	for (const workflowId of ["general", "feature", "bug-fix"] as const) {
		const implementation = findGate(workflows[workflowId], "implementation");
		const documentation = findGate(workflows[workflowId], "documentation");
		const codeReview = implementation.verify?.find((step) => step.role === "code-reviewer");
		const prompt = codeReview?.prompt?.replace(/\s+/g, " ") ?? "";

		assert.deepEqual(documentation.depends_on, ["implementation"], `${source}.${workflowId} Documentation must remain downstream of implementation`);
		assert.match(prompt, /(?:runs?|occurs?|happens?).{0,100}(?:before|ahead of).{0,100}(?:mandatory|downstream) documentation (?:gate|stage)/i, `${source}.${workflowId} code review must identify the later Documentation stage`);
		assert.match(prompt, /documentation[- ]only.{0,160}(?:gap|omission|issue).{0,160}(?:ignore|out of scope|non[- ]blocking|(?:must )?not fail)|(?:ignore|out of scope|non[- ]blocking|(?:must )?not fail).{0,160}documentation[- ]only/i, `${source}.${workflowId} code review must defer documentation-only findings`);
		assert.match(prompt, /(?:missing|outdated).{0,120}docs?|docs?.{0,120}(?:missing|outdated)/i, `${source}.${workflowId} code review must include missing or outdated docs as deferred examples`);
		assert.match(prompt, /README.{0,120}design[- ]doc|design[- ]doc.{0,120}README/i, `${source}.${workflowId} code review must include README and design-doc updates as deferred examples`);
		assert.match(prompt, /code comments?|comments?.{0,80}code/i, `${source}.${workflowId} code review must include code comments as deferred examples`);
		assert.match(prompt, /(?:concrete )?implementation defects?.{0,120}(?:in scope|review|still)|(?:in scope|review|still).{0,120}(?:concrete )?implementation defects?/i, `${source}.${workflowId} code review must retain concrete implementation defects`);
	}

	const quickFix = findGate(workflows["quick-fix"], "implementation");
	const quickFixPrompt = quickFix.verify?.find((step) => step.role === "code-reviewer")?.prompt?.replace(/\s+/g, " ") ?? "";
	assert.ok(!workflows["quick-fix"].gates.some((gate) => gate.id === "documentation"), `${source}.quick-fix must not gain a Documentation gate`);
	assert.doesNotMatch(quickFixPrompt, /(?:before|ahead of).{0,100}downstream documentation (?:gate|stage)/i, `${source}.quick-fix must not inherit the downstream Documentation-stage rationale`);
}

function assertDeferredToLaterStage(prompt: string, artifact: RegExp, source: string): void {
	const policy = prompt.replace(/\s+/g, " ");
	const genericDeferral = "(?:defer|do not (?:require|demand|block|fail)|not (?:a )?(?:blocker|requirement)|out of scope|belongs? to|handled by)";
	// "Leave X to that QA step rather than failing this review" is equally clear,
	// but a bare "leave X" is not: it must name a later owner. Keep the
	// independent artifact requirement below so this cannot accept a generic QA
	// disclaimer in place of optional phase-3 QA or another named later stage.
	const stageOwner = "(?:that|a|the|later|downstream).{0,100}(?:QA|step|stage|gate)";
	const failureContrast = "(?:rather than|instead of).{0,100}(?:fail(?:ing)?|block(?:ing)?|require|demand).{0,100}(?:this|current|review|stage|gate)";
	const artifactPattern = artifact.source;
	const explicitHandoff = `(?:leave.{0,180}${artifactPattern}.{0,180}(?:to|for).{0,100}${stageOwner}|${artifactPattern}.{0,180}leave.{0,180}(?:to|for).{0,100}${stageOwner})`;
	const genericOrContrast = `(?:${genericDeferral}|${failureContrast})`;
	// Stage-scope prompts can enumerate several named downstream gates before
	// their single non-blocking instruction. Keep that complete policy paragraph
	// associated without demanding a particular sentence order or compact prose.
	const policyWindow = 300;
	const message = `${source} must defer ${artifact.source} to its owning later stage rather than fail the current review`;

	assert.match(policy, new RegExp(`${genericOrContrast}.{0,${policyWindow}}${artifactPattern}|${artifactPattern}.{0,${policyWindow}}${genericOrContrast}|${explicitHandoff}`, "i"), message);
}

function assertCompleteGateStageOwnership(
	workflows: Record<string, Workflow>,
	source: string,
	optionalQaPhase = DEFAULT_IMPLEMENTATION_PHASES.qa,
): void {
	for (const workflowId of IMPLEMENTATION_WORKFLOW_IDS) {
		const implementation = findGate(workflows[workflowId], "implementation");
		const specPrompt = implementation.verify?.find((step) => step.role === "spec-auditor")?.prompt ?? "";
		const securityPrompt = implementation.verify?.find((step) => step.role === "security-reviewer")?.prompt ?? "";

		// Implementation reviews must not block on work owned by optional QA or publication.
		const optionalQa = new RegExp(`(?:optional.{0,100}(?:phase[- ]?${optionalQaPhase}|later).{0,100}(?:QA|agent QA)|(?:QA|agent QA).{0,100}optional.{0,100}(?:phase[- ]?${optionalQaPhase}|later))`, "i");
		assertDeferredToLaterStage(specPrompt, optionalQa, `${source}.${workflowId}.implementation Spec review optional QA`);
		assertDeferredToLaterStage(specPrompt, /(?:ready[- ]to[- ]merge|publication).{0,160}(?:push|base(?:[- ]sync)?|pull request|PR)|(?:push|base(?:[- ]sync)?|pull request|PR).{0,160}(?:ready[- ]to[- ]merge|publication)/i, `${source}.${workflowId}.implementation Spec review publication`);

		const hasDocumentationGate = workflowId !== "quick-fix";
		if (hasDocumentationGate) {
			assertDeferredToLaterStage(securityPrompt, /(?:downstream|later).{0,100}documentation (?:gate|stage)|documentation[- ]only.{0,120}(?:gap|omission|issue)/i, `${source}.${workflowId}.implementation Security review documentation-only work`);
			assert.match(securityPrompt.replace(/\s+/g, " "), /(?:documentation[- ]only.{0,160}(?:defer|out of scope|non[- ]blocking|(?:must )?not fail|leave)|(?:defer|out of scope|non[- ]blocking|(?:must )?not fail|leave).{0,160}documentation[- ]only)/i, `${source}.${workflowId}.implementation Security review must not fail early for documentation-only work`);
		} else {
			assert.doesNotMatch(securityPrompt, /(?:before|ahead of|downstream|later).{0,120}documentation (?:gate|stage)/i, `${source}.${workflowId}.implementation Security review must not invent a downstream Documentation stage`);
			assert.doesNotMatch(securityPrompt, /documentation[- ]only.{0,160}(?:out of scope|non[- ]blocking|(?:must )?not fail)/i, `${source}.${workflowId}.implementation Security review must not inherit the Documentation-stage carveout`);
		}
	}

	const bugFixAnalysis = findGate(workflows["bug-fix"], "issue-analysis").verify?.find((step) => step.name === "Analysis quality")?.prompt ?? "";
	assert.match(bugFixAnalysis, /test plan/i, `${source}.bug-fix Analysis quality must still own a test plan`);
	for (const [label, artifact] of [
		["reproducing-test execution", /reproducing[- ]test/i],
		["implementation", /implementation (?:owns?|gate|work|changes?|fix(?:es)?)/i],
		["test execution", /(?:write|run|execute(?:d)?|execution of).{0,80}tests?/i],
		["documentation", /\bdocumentation\b/i],
		["publication", /(?:ready[- ]to[- ]merge|publication).{0,160}(?:push|base(?:[- ]sync)?|pull request|PR)|(?:push|base(?:[- ]sync)?|pull request|PR).{0,160}(?:ready[- ]to[- ]merge|publication)/i],
	] as const) {
		assertDeferredToLaterStage(bugFixAnalysis, artifact, `${source}.bug-fix Analysis quality ${label}`);
	}

	for (const workflowId of ["general", "feature", "bug-fix"] as const) {
		const documentationPrompt = findGate(workflows[workflowId], "documentation").verify?.find((step) => step.name === "Documentation coverage")?.prompt ?? "";
		assertDeferredToLaterStage(documentationPrompt, /(?:ready[- ]to[- ]merge|publication).{0,160}(?:push|base(?:[- ]sync)?|pull request|PR)|(?:push|base(?:[- ]sync)?|pull request|PR).{0,160}(?:ready[- ]to[- ]merge|publication)/i, `${source}.${workflowId}.documentation publication`);
	}
	assert.ok(!workflows["quick-fix"].gates.some((gate) => gate.id === "documentation"), `${source}.quick-fix must retain its Documentation-gate exclusion`);
}

function assertUnconditionalSpecDocumentationScope(workflows: Record<string, Workflow>, source: string): void {
	const conditionalDocumentationDeferral = /(?:ignore|defer).{0,100}documentation[- ]only.{0,180}\bonly when\b.{0,180}(?:downstream|later).{0,100}documentation|\bonly when\b.{0,180}(?:downstream|later).{0,100}documentation.{0,180}(?:ignore|defer).{0,100}documentation[- ]only/i;

	for (const workflowId of IMPLEMENTATION_WORKFLOW_IDS) {
		const implementation = findGate(workflows[workflowId], "implementation");
		const specPrompt = implementation.verify?.find((step) => step.role === "spec-auditor")?.prompt?.replace(/\s+/g, " ") ?? "";

		assert.match(specPrompt, /ignore documentation[- ]only (?:gap|omission|issue|artifact)/i, `${source}.${workflowId}.implementation Spec review must unconditionally ignore documentation-only gaps`);
		assert.doesNotMatch(specPrompt, conditionalDocumentationDeferral, `${source}.${workflowId}.implementation Spec review must not make documentation-only scope depend on a downstream Documentation stage`);
	}
}

function assertProjectReadyToMergeChecks(workflows: Record<string, Workflow>, source: string): void {
	for (const workflowId of IMPLEMENTATION_WORKFLOW_IDS) {
		const verify = findGate(workflows[workflowId], "ready-to-merge").verify ?? [];
		const prRaisedIndex = verify.findIndex((step) => step.name === "PR raised");
		const checksIndex = verify.findIndex((step) => step.name === "PR checks pass");
		assert.ok(prRaisedIndex >= 0, `${source}.${workflowId}.ready-to-merge must verify that the PR was raised`);
		assert.ok(checksIndex > prRaisedIndex, `${source}.${workflowId}.ready-to-merge must wait for PR checks after verifying that the PR was raised`);

		const checks = verify[checksIndex];
		assert.equal(checks.type, "command");
		assert.equal(checks.phase, 1);
		assert.equal(checks.timeout, 3600);
		assert.equal(checks.run, 'gh pr checks "{{branch}}" --watch --interval 10');
		const guidance = checks.failureGuidance?.replace(/\s+/g, " ") ?? "";
		assert.match(guidance, /transient.{0,120}retry and re-signal/i);
		assert.match(guidance, /re-signal.{0,120}earliest passed gate/i);
		assert.match(guidance, /Implementation.{0,100}source code.{0,100}tests/i);
		assert.match(guidance, /Documentation.{0,100}documentation-only/i);
		assert.match(guidance, /Design\/Issue Analysis.{0,100}assumptions change/i);
	}
}

function assertImplementationReviewPolicy(
	workflows: Record<string, Workflow>,
	source: string,
	phases = DEFAULT_IMPLEMENTATION_PHASES,
) {
	for (const workflowId of IMPLEMENTATION_WORKFLOW_IDS) {
		const implementation = findGate(workflows[workflowId], "implementation");
		const verify = implementation.verify ?? [];
		const reviews = verify.filter((step) => step.type === "llm-review");

		assert.deepEqual(
			reviews.map(({ name, role, phase }) => ({ name, role, phase })),
			EXPECTED_REVIEWS.map(({ name, role }) => ({ name, role, phase: phases.reviews })),
			`${source}.${workflowId}.implementation must contain exactly the three consolidated reviews in policy order and phase`,
		);

		for (const step of verify) {
			for (const supersededName of SUPERSEDED_REVIEW_NAMES) {
				assert.doesNotMatch(step.name, supersededName, `${source}.${workflowId}.implementation must not retain ${supersededName}`);
			}
			assert.ok(!step.role || !SUPERSEDED_REVIEW_ROLES.has(step.role), `${source}.${workflowId}.implementation must not retain superseded reviewer role ${step.role}`);
		}

		const build = verify.find((step) => step.name === "Build");
		assert.ok(build, `${source}.${workflowId}.implementation must retain Build`);
		assert.equal(build.type, "command");
		assert.ok(build.phase === undefined || build.phase === 0, `${source}.${workflowId}.implementation Build must run in phase 0`);

		for (const [command, phase] of Object.entries(phases.commands)) {
			const step = verify.find((candidate) => candidate.type === "command" && candidate.command === command);
			assert.ok(step, `${source}.${workflowId}.implementation must run ${command}`);
			assert.equal(step.phase, phase, `${source}.${workflowId}.implementation ${command} must run in phase ${phase}`);
		}

		for (const qaStep of verify.filter((step) => step.type === "agent-qa")) {
			assert.equal(qaStep.optional, true, `${source}.${workflowId}.implementation QA must be optional`);
			assert.equal(qaStep.phase, phases.qa, `${source}.${workflowId}.implementation QA must run in phase ${phases.qa}`);
		}
	}

	const bugFixSteps = findGate(workflows["bug-fix"], "implementation").verify ?? [];
	const reproducingSuccess = bugFixSteps.find((step) => step.type === "command" && step.expect === "success" && step.run?.includes("test_command"));
	assert.ok(reproducingSuccess, `${source}.bug-fix.implementation must run the reproducing test after the fix`);
	assert.equal(reproducingSuccess.phase, 1, `${source}.bug-fix reproducing-test success command must run in phase 1`);
}

describe("consolidated implementation review defaults", () => {
	it("accepts explicit later-stage handoffs but rejects an ambiguous leave instruction", () => {
		const optionalQa = /optional phase[- ]?3 QA/i;

		assert.doesNotThrow(() => assertDeferredToLaterStage(
			"When optional phase-3 QA is configured, leave missing QA execution to that QA step rather than failing this review.",
			optionalQa,
			"clear QA handoff",
		));
		assert.doesNotThrow(() => assertDeferredToLaterStage(
			"Leave optional phase-3 QA execution to the later QA stage.",
			optionalQa,
			"clear leading QA handoff",
		));
		assert.doesNotThrow(() => assertDeferredToLaterStage(
			"Optional phase-3 QA is not a blocker in this phase; instead of failing the current review, reserve it for phase 3.",
			optionalQa,
			"clear failure contrast",
		));
		assert.throws(() => assertDeferredToLaterStage(
			"Leave optional phase-3 QA out.",
			optionalQa,
			"ambiguous QA instruction",
		));
	});

	it("seeds exactly three phase-2 implementation reviews with the required roles and execution phases", () => {
		assertImplementationReviewPolicy(buildDefaultWorkflows("myproj"), "seeded defaults");
	});

	it("omits unavailable structural commands without disturbing reviews or supported commands", () => {
		const workflows = buildCapabilityAwareDefaults("minimal-app", ["build", "unit"]);

		for (const workflowId of IMPLEMENTATION_WORKFLOW_IDS) {
			const implementation = findGate(workflows[workflowId], "implementation");
			const structuralCommands = (implementation.verify ?? [])
				.filter((step) => step.type === "command" && step.command)
				.map((step) => step.command)
				.sort();
			const reviews = (implementation.verify ?? [])
				.filter((step) => step.type === "llm-review")
				.map(({ name, role, phase }) => ({ name, role, phase }));

			assert.deepEqual(structuralCommands, ["build", "unit"], `${workflowId} must retain only declared component commands`);
			assert.deepEqual(
				reviews,
				EXPECTED_REVIEWS.map(({ name, role }) => ({ name, role, phase: 2 })),
				`${workflowId} must preserve the three required phase-2 reviews`,
			);
		}
	});

	it("keeps the active project workflow config parseable with serialized expensive verification phases", () => {
		const repoRoot = path.resolve(import.meta.dirname, "..", "..", "..");
		const project = YAML.parse(fs.readFileSync(path.join(repoRoot, ".bobbit", "config", "project.yaml"), "utf8")) as {
			workflows?: Record<string, Workflow>;
		};
		assert.ok(project.workflows, "project.yaml must define workflows");
		assertImplementationReviewPolicy(project.workflows, ".bobbit/config/project.yaml", PROJECT_IMPLEMENTATION_PHASES);
		assertProjectReadyToMergeChecks(project.workflows, ".bobbit/config/project.yaml");

		const prReview = project.workflows["pr-review"];
		assert.ok(prReview, "PR Review must remain a purpose-built workflow");
		assert.ok(findGate(prReview, "fetch-pr"), "PR Review must retain its PR fetch gate");
		const humanSignoff = project.workflows["human-signoff-test"];
		assert.ok(humanSignoff, "Human Sign-off Test must remain present");
		assert.ok(humanSignoff.gates.some((gate) => gate.verify?.some((step) => step.type === "human-signoff")), "Human Sign-off Test must retain its human sign-off step");
	});

	it("limits documentation-only implementation findings to workflows with a downstream Documentation stage", () => {
		assertDownstreamDocumentationStageScope(buildDefaultWorkflows("myproj"), "seeded defaults");

		const project = YAML.parse(fs.readFileSync(path.join(path.resolve(import.meta.dirname, "..", "..", ".."), ".bobbit", "config", "project.yaml"), "utf8")) as {
			workflows?: Record<string, Workflow>;
		};
		assert.ok(project.workflows, "project.yaml must define workflows");
		assertDownstreamDocumentationStageScope(project.workflows, ".bobbit/config/project.yaml");
	});

	it("keeps every review at its owning gate and mirrors that boundary in project.yaml", () => {
		assertCompleteGateStageOwnership(buildDefaultWorkflows("myproj"), "seeded defaults");

		const project = YAML.parse(fs.readFileSync(path.join(path.resolve(import.meta.dirname, "..", "..", ".."), ".bobbit", "config", "project.yaml"), "utf8")) as {
			workflows?: Record<string, Workflow>;
		};
		assert.ok(project.workflows, "project.yaml must define workflows");
		assertCompleteGateStageOwnership(project.workflows, ".bobbit/config/project.yaml", PROJECT_IMPLEMENTATION_PHASES.qa);
	});

	it("keeps the phase-2 prompts implementation-ready", () => {
		const workflows = buildDefaultWorkflows("myproj");
		for (const workflowId of IMPLEMENTATION_WORKFLOW_IDS) {
			const reviews = findGate(workflows[workflowId], "implementation").verify?.filter((step) => step.type === "llm-review") ?? [];
			const spec = reviews.find((step) => step.role === "spec-auditor")?.prompt ?? "";
			const code = reviews.find((step) => step.role === "code-reviewer")?.prompt ?? "";
			const security = reviews.find((step) => step.role === "security-reviewer")?.prompt ?? "";

			for (const requirement of [/goal/i, /(?:design|analysis)/i, /implementation/i, /tests?/i]) {
				assert.match(spec, requirement, `${workflowId} spec review must compare all implementation inputs`);
			}
			assert.match(spec, /ignore documentation[- ]only (?:gap|omission|issue|artifact)/i, `${workflowId} spec review must exclude documentation-only gaps`);
			assert.match(spec, /implementation-ready.*remediation/is, `${workflowId} spec review must require actionable blockers`);
			for (const concern of [/correctness/i, /error handling/i, /edge.*mixed/is, /concurrency.*lifecycle/is, /cross-layer/i, /maintainability/i, /regression coverage/i]) {
				assert.match(code, concern, `${workflowId} code review must cover integrated implementation risks`);
			}
			assert.match(code, /deduplicat.*root cause/is, `${workflowId} code review must deduplicate by root cause`);
			assert.match(code, /minimal (?:implementation )?fix(?:es)?.*focused tests?/is, `${workflowId} code review must prescribe a minimal fix and focused test`);
			for (const risk of [/trust boundar/i, /auth/i, /validation/i, /injection/i, /secrets/i, /(?:destructive|resource ownership)/i, /dependency/i, /races/i]) {
				assert.match(security, risk, `${workflowId} security review must cover changed security risks`);
			}
			assert.match(security, /remediation.*(?:abuse|regression) tests?/is, `${workflowId} security review must require a remediation test`);
		}
	});

	it("unconditionally excludes documentation-only gaps from every phase-2 spec review", () => {
		assertUnconditionalSpecDocumentationScope(buildDefaultWorkflows("myproj"), "seeded defaults");

		const project = YAML.parse(fs.readFileSync(path.join(path.resolve(import.meta.dirname, "..", "..", ".."), ".bobbit", "config", "project.yaml"), "utf8")) as {
			workflows?: Record<string, Workflow>;
		};
		assert.ok(project.workflows, "project.yaml must define workflows");
		assertUnconditionalSpecDocumentationScope(project.workflows, ".bobbit/config/project.yaml");
	});

	it("makes first-phase design and issue-analysis reviews revision-ready", () => {
		const workflows = buildDefaultWorkflows("myproj");
		for (const workflowId of ["general", "feature"] as const) {
			const reviewSteps = findGate(workflows[workflowId], "design-doc").verify ?? [];
			assertDesignOrAnalysisReviewPrompt(
				reviewSteps.find((step) => step.name === "Design review")?.prompt ?? "",
				`${workflowId}.design-doc.Design review`,
			);
			assertDesignOrAnalysisReviewPrompt(
				reviewSteps.find((step) => step.name === "Gap analysis")?.prompt ?? "",
				`${workflowId}.design-doc.Gap analysis`,
			);
		}

		const issueAnalysis = findGate(workflows["bug-fix"], "issue-analysis").verify ?? [];
		assertDesignOrAnalysisReviewPrompt(
			issueAnalysis.find((step) => step.name === "Analysis quality")?.prompt ?? "",
			"bug-fix.issue-analysis.Analysis quality",
		);
		assertDesignOrAnalysisReviewPrompt(
			issueAnalysis.find((step) => step.name === "Gap analysis")?.prompt ?? "",
			"bug-fix.issue-analysis.Gap analysis",
		);
	});

	it("makes documentation reviews revision-ready", () => {
		const workflows = buildDefaultWorkflows("myproj");
		for (const workflowId of ["general", "feature", "bug-fix"] as const) {
			const documentation = findGate(workflows[workflowId], "documentation");
			assertDocumentationReviewPrompt(
				documentation.verify?.find((step) => step.name === "Documentation coverage")?.prompt ?? "",
				`${workflowId}.documentation.Documentation coverage`,
			);
		}
	});

	it("retains the design-time spec gap analysis outside the consolidated implementation reviews", () => {
		const workflows = buildDefaultWorkflows("myproj");
		for (const workflowId of ["general", "feature"]) {
			const review = findGate(workflows[workflowId], "design-doc").verify?.find((step) => step.name === "Gap analysis");
			assert.ok(review, `${workflowId}.design-doc must retain its design-time gap analysis`);
			assert.equal(review.role, "spec-auditor");
		}
		assert.ok(!workflows["quick-fix"].gates.flatMap((gate) => gate.verify ?? []).some((step) => step.name === "Gap analysis"), "quick-fix must not gain a design gap-analysis step");
	});

	it("retains Ralph-loop descriptions for the non-quick-fix implementation gates", () => {
		const workflows = buildDefaultWorkflows("myproj");
		for (const workflowId of ["general", "feature", "bug-fix"]) {
			assert.equal(findGate(workflows[workflowId], "implementation").description, RALPH_LOOP_DESCRIPTION);
		}
	});
});
